src/Common/DataAccessUtilityBase.ts

These methods are no longer used

Remove unused Data Access methods

---

src/Common/Constants.ts
src/Explorer/Explorer.ts
src/Explorer/Panes/AddCollectionPane.html
src/Explorer/Panes/AddCollectionPane.ts
src/Explorer/Panes/AddDatabasePane.html
src/Explorer/Panes/AddDatabasePane.ts
src/Explorer/Panes/CassandraAddCollectionPane.html
src/Explorer/Panes/CassandraAddCollectionPane.ts
src/Explorer/Tree/Collection.ts
src/Explorer/Tree/Database.ts
src/Explorer/Tree/ResourceTreeAdapter.tsx
src/Utils/PricingUtils.ts

- Hide throughput configuration UI in `AddDatabasePane` and `AddCollectionPane`
- Hide Scale settings

Support serverless accounts

---

src/Explorer/Notebook/NotebookRenderer/NotebookReadOnlyRenderer.tsx

Fix NotebookViewer code cell margin

---

src/Explorer/Explorer.ts

Add init message when warming up notebook workspace

Add init message when warming up notebook workspace

---

src/Explorer/Controls/NotebookGallery/GalleryViewerComponent.tsx
src/Explorer/Explorer.ts
src/Explorer/Notebook/NotebookContentClient.ts
src/Explorer/Notebook/NotebookManager.ts
src/Explorer/Notebook/NotebookUtil.test.ts
src/Explorer/Notebook/NotebookUtil.ts
src/Explorer/Panes/CopyNotebookPane.tsx
src/Explorer/Panes/PublishNotebookPaneAdapter.tsx
src/Explorer/Panes/PublishNotebookPaneComponent.test.tsx
src/Explorer/Panes/PublishNotebookPaneComponent.tsx
src/Explorer/Panes/__snapshots__/PublishNotebookPaneComponent.test.tsx.snap
src/Explorer/Tabs/NotebookV2Tab.ts
src/Explorer/Tree/ResourceTreeAdapter.tsx
src/GitHub/GitHubClient.ts
src/GitHub/GitHubContentProvider.ts
src/Utils/Base64Utils.test.ts
src/Utils/Base64Utils.ts
src/explorer.html

Copy To functionality for notebooks

---

package-lock.json
package.json
webpack.config.js

Also updates canvas is unhappy on Windows with the current version.

Turn off HMR

---

src/Explorer/SplashScreen/SplashScreenComponent.tsx

Removing alt text for decorative images.

Screen reader changes

---

src/explorer.html

Added tooltips

---

src/explorer.html

Added aria role for screen readers to read status changes when user press refresh button.

Added alert role for splash loader

---

sampleData/sqlSampleData.json
src/Common/DataAccessUtilityBase.ts
src/Common/DocumentClientUtilityBase.ts
src/Common/MongoProxyClient.ts
src/Common/QueriesClient.ts
src/Common/dataAccess/createCollection.test.ts
src/Common/dataAccess/createCollection.ts
src/Common/dataAccess/createDatabase.ts
src/Contracts/DataModels.ts
src/Explorer/DataSamples/ContainerSampleGenerator.test.ts
src/Explorer/DataSamples/ContainerSampleGenerator.ts
src/Explorer/Panes/AddCollectionPane.ts
src/Utils/arm/generatedClients/2020-04-01/types.ts

- refactored logic in AddCollectionPane to call `createCollection` for all API types
- manually added `analyticalStorageTtl` in `SqlContainerResource` type
- fixed wrong parameter types in `createDatabase`

Move create collection to RP

---

src/Explorer/Panes/AddCollectionPane.html

Aria label was not descriptive enough for close button. Updated aria label.

Updated aria label

---

src/Explorer/Menus/NotificationConsole/NotificationConsoleComponent.tsx
src/Explorer/Menus/NotificationConsole/__snapshots__/NotificationConsoleComponent.test.tsx.snap

Moved img alt text to button aria label

Fixed notification console screen reader issue

---

src/Common/MessageHandler.ts
src/Shared/Telemetry/TelemetryConstants.ts
src/Terminal/index.ts

This reverts commit 83b13de6852902c68038c3a0eee0a8d6ad8c1651.

Revert "Add telemetry for OpenTerminal success/failure (#192)"

---

src/Common/DataAccessUtilityBase.ts
src/Common/DocumentClientUtilityBase.ts
src/Common/dataAccess/createStoredProcedure.ts
src/Common/dataAccess/createTrigger.ts
src/Common/dataAccess/createUserDefinedFunction.ts
src/Common/dataAccess/deleteStoredProcedure.ts
src/Common/dataAccess/deleteTrigger.ts
src/Common/dataAccess/deleteUserDefinedFunction.ts
src/Common/dataAccess/readStoredProcedures.ts
src/Common/dataAccess/readTriggers.ts
src/Common/dataAccess/readUserDefinedFunctions.ts
src/Common/dataAccess/updateStoredProcedure.ts
src/Common/dataAccess/updateTrigger.ts
src/Common/dataAccess/updateUserDefinedFunction.ts
src/Contracts/DataModels.ts
src/Contracts/ViewModels.ts
src/Explorer/Tabs/ScriptTabBase.ts
src/Explorer/Tabs/StoredProcedureTab.ts
src/Explorer/Tabs/TriggerTab.ts
src/Explorer/Tabs/UserDefinedFunctionTab.ts
src/Explorer/Tree/Collection.ts
src/Explorer/Tree/StoredProcedure.ts
src/Explorer/Tree/Trigger.ts
src/Explorer/Tree/UserDefinedFunction.ts

- Splits and refactors out all CRUD methods for triggers/UDFS/sprocs
- Does not yet at ARM code paths
- Use SDK typings for above where possible

Split all script data access methods

---

src/Explorer/Panes/AddCollectionPane.html
src/Explorer/Panes/DeleteCollectionConfirmationPane.html

Bug link: https://msdata.visualstudio.com/CosmosDB/_workitems/edit/836345/

Fix aria-labels in AddCollectionPane and DeleteCollectionConfirmationPane

---

src/Explorer/Panes/ContextualPaneBase.ts

Bug link: https://msdata.visualstudio.com/CosmosDB/_workitems/edit/835037/

Reset focus to trigger element when pane is closed

---

src/Explorer/Panes/Tables/AddTableEntityPane.ts

https://msdata.visualstudio.com/CosmosDB/_queries/query/b7017577-e55f-4ce9-a968-0f12c1b1ccaf
Reopen of #225

Focuses add table entity value element when Add Row is clicked

---

.github/workflows/automerge.yml

Community built auto merge Github Action. Please do not use yet. This is for testing.

Add Automerge Action

---

.github/workflows/ci.yml
jest-puppeteer.config.js
test/mongo/container.spec.ts
test/sql/container.spec.ts

E2E tests are failing because as puppeteer is typing into the collectionId input, it will suddenly focus the database input and so fail to find the database later because it searches by ID

Fixes e2e test input focus swapping

---

src/ConfigContext.ts
src/Utils/MessageValidation.test.ts

Missing a case for German national cloud

Fix Blackforest Origin check

---

package-lock.json
package.json
src/Shared/appInsights.ts

@gitanuj I tested terminal with this and it works. Just turning off the correlation headers entirely.

Restore AppInsights fetch telemetry

---

src/Common/dataAccess/createStoredProcedure.ts
src/Common/dataAccess/createTrigger.ts
src/Common/dataAccess/createUserDefinedFunction.ts
src/Common/dataAccess/deleteTrigger.ts
src/Common/dataAccess/deleteUserDefinedFunction.ts
src/Common/dataAccess/readTriggers.ts
src/Common/dataAccess/readUserDefinedFunctions.ts
src/Common/dataAccess/updateStoredProcedure.ts
src/Common/dataAccess/updateTrigger.ts
src/Common/dataAccess/updateUserDefinedFunction.ts
src/Explorer/Tree/UserDefinedFunction.ts

Move UDF and trigger operations to RP

Move UDF and trigger operations to RP

---

src/Explorer/Controls/Settings/SettingsComponent.tsx
src/Explorer/Panes/AddCollectionPane.html

Remove extra error logging for `updateOfferThroughputBeyondLimit` in SettingsComponent.

Remove extra error logging in SettingsComponent

---

src/Explorer/Controls/Settings/SettingsComponent.tsx
src/Explorer/Tabs/SettingsTab.ts
src/Shared/Telemetry/TelemetryConstants.ts

- Also changed error -> error.reason for tracefailure

Added extra logging for mongo index update RP call

---

src/Terminal/index.ts

This is useful to know which terminal is opening.

Record baseUrl for OpenTerminal success/failure telemetry

---

package-lock.json
src/Common/OfferUtility.test.ts
src/Common/OfferUtility.ts
src/Common/dataAccess/readCollectionOffer.ts
src/Common/dataAccess/readDatabaseOffer.ts
src/Contracts/DataModels.ts
src/Explorer/Controls/Settings/SettingsComponent.test.tsx
src/Explorer/Controls/Settings/SettingsComponent.tsx
src/Explorer/Controls/Settings/SettingsSubComponents/ScaleComponent.test.tsx
src/Explorer/Controls/Settings/SettingsSubComponents/ScaleComponent.tsx
src/Explorer/Controls/Settings/TestUtils.tsx
src/Explorer/Tabs/DatabaseSettingsTab.ts

Existing code expects there to be a header for pending offer replacement, but with RP this was moved to the body of the response. This PR updates data access code to handle both cases.

Fix offer update notification for AAD users

---

src/Common/ErrorHandlingUtils.ts
src/Explorer/Tables/DataTable/TableEntityListViewModel.ts

Reverting to old Q based version of TablesEntitiyListViewModel to resolve a production issue

Revert TablesEntitiyListViewModel changes

---

src/Explorer/Tree/AccessibleVerticalList.ts
tsconfig.strict.json

Add;
"./src/Explorer/Tree/AccessibleVerticalList.ts",

Aadd one accessibleVertical file to master

---

src/ConfigContext.ts
src/Contracts/ExplorerContracts.ts
src/Explorer/Explorer.ts
src/HostedExplorerChildFrame.ts
src/Main.tsx
src/applyExplorerBindings.ts
src/hooks/useConfig.ts
src/hooks/useKnockoutExplorer.ts
test/testExplorer/TestExplorer.ts
test/testExplorer/TestExplorerParams.ts
test/testExplorer/TestExplorerUtils.ts
test/testExplorer/testExplorer.html

Minimal functional changes. This is mostly to make it easier to work with Main.tsx and isolating complex hook behavior to one place.

Refactor explorer config into useKnockoutExplorer hook

---

src/Explorer/Menus/CommandBar/CommandBarComponentButtonFactory.ts

Adds a non-functional button behind a feature flag for demo purposes

Region Select Button

---

src/Explorer/Controls/NotebookGallery/CodeOfConductComponent.tsx
src/Explorer/Controls/NotebookGallery/GalleryViewerComponent.less
src/Explorer/Controls/NotebookGallery/GalleryViewerComponent.tsx
src/Explorer/Controls/NotebookGallery/__snapshots__/CodeOfConductComponent.test.tsx.snap

Update Code of Conduct Overlay and other minor changes

---

src/Explorer/Controls/NotebookGallery/GalleryViewerComponent.tsx
src/Explorer/Controls/NotebookViewer/NotebookViewerComponent.tsx
src/Shared/Telemetry/TelemetryConstants.ts
src/Utils/GalleryUtils.ts

Add more telemetry actions and add more data to existing actions
- NotebooksGalleryOfficialSamplesCount
- NotebooksGalleryPublicGalleryCount
- NotebooksGalleryFavoritesCount
- NotebooksGalleryPublishedCount

Telemetry updates

---

test/selfServe/selfServeExample.spec.ts

SelfServe test has been failing. So skipping it for now.

Skip SelfServe e2e test

---

src/Explorer/Controls/NotebookViewer/NotebookViewerComponent.tsx
src/Utils/GalleryUtils.ts

Link Injection adds a cell with a link to the notebook viewer, for a published notebook.
This cell is stripped out before displaying it in hte notebook viewer.
But when the notebook is downloaded, this cell was not being removed before the download.
This PR fixed that bug.

Remove injected cell before download

---

.github/workflows/ci.yml
package-lock.json
package.json
test/mongo/container.spec.ts
test/mongo/mongoIndexPolicy.spec.ts
test/sql/container.spec.ts
test/sql/resourceToken.spec.ts
test/utils/shared.ts
utils/cleanupDBs.js

- Adds account cleanup step that removes old untested accounts. Uses ARM instead of data plane SDK.
- Encodes create timestamp into account name. Mongo doesn't have timestamps via ARM 😢 
- Increases some delays to make the tests a bit more robust

End to End Test Improvements

---

test/mongo/mongoIndexPolicy.spec.ts
test/sql/resourceToken.spec.ts

Uses management client to get keys

Improved resource token test

---

.eslintignore

Three is not any lint errors in AutoPilotUtils.ts

Resolve Lint errors in AutoPilotUtils.ts

---

.eslintignore
src/Common/ThemeUtility.ts
src/Explorer/Tabs/TabsBase.ts

Fix Lint errors in ThemeUtility

Fix Lint errors in ThemeUtility

---

.eslintignore
src/Explorer/Controls/CommandButton/CommandButtonComponent.tsx
src/Explorer/Controls/Notebook/NotebookTerminalComponent.tsx
src/Explorer/Notebook/NotebookComponent/contents/file/text-file.tsx
src/Explorer/Notebook/NotebookContentClient.ts
src/Explorer/Notebook/NotebookUtil.ts
src/Utils/StringUtils.test.ts
src/Utils/StringUtils.ts

Removes StringUtils.ts from .eslintignore and fixes errors

fixed lint issue of StringUtils file

---

.eslintignore
src/Utils/AuthorizationUtils.test.ts
src/Utils/AuthorizationUtils.ts

fixed lint issue of AuthorizationUtils.ts and remove from .eslintIgnore file

Fixed lint issue of AuthorizationUtils

---

.eslintignore
src/Explorer/Graph/GraphExplorerComponent/EditorNeighborsComponent.tsx
src/Explorer/Graph/GraphExplorerComponent/GraphExplorer.tsx
src/Explorer/Graph/GraphExplorerComponent/GraphUtil.test.ts
src/Explorer/Graph/GraphExplorerComponent/GraphUtil.ts
src/Explorer/Graph/GraphExplorerComponent/ReadOnlyNeighborsComponent.tsx

Fixed eslint issue of GraphUtil and removed unused files from eslintIgnore

fixed eslint GraphUtil and removed files from eslintignore

---

.eslintignore
src/Explorer/Tables/DataTable/DataTableUtilities.ts

Fixed lint issue DataTableUtility.ts and removed unused code

Fixed lint issue and remove unused code

---

.eslintignore
src/Explorer/Panes/SettingsPane.ts
src/Shared/StorageUtility.ts
src/Shared/StringUtility.test.ts
src/Shared/StringUtility.ts

Removes StringUtility.ts from .eslintignore and fixes errors

Fix Lint errors in StringUtility.ts

---

src/Explorer/MostRecentActivity/MostRecentActivity.test.ts
src/Explorer/MostRecentActivity/MostRecentActivity.ts
src/Explorer/SplashScreen/SplashScreen.tsx
src/Explorer/Tree/ResourceTreeAdapter.tsx
src/Explorer/Tree/ResourceTreeAdapterForResourceToken.tsx

This changes the public API a bit, so that recording activity (the most common use) is less involved.

MostRecentActivity changes

---

src/Explorer/Tables/DataTable/TableEntityListViewModel.ts

ICM https://portal.microsofticm.com/imp/v3/incidents/details/231058653/home

[Tables] Check for undefined before compare

---

package.json

removed a change that modifed the e2e test suite.

removed change to package.json

---

src/Main.tsx

Fix SplashScreen/Tabs Visible bug

---

src/Common/Constants.ts
src/Contracts/ViewModels.ts
src/Explorer/Controls/Settings/SettingsComponent.tsx
src/Explorer/Controls/Settings/SettingsSubComponents/ThroughputInputComponents/ThroughputInputAutoPilotV3Component.tsx
src/Explorer/Controls/Settings/__snapshots__/SettingsComponent.test.tsx.snap
src/Explorer/Explorer.tsx
src/Explorer/Panes/AddCollectionPane.ts
src/Explorer/Panes/AddCollectionPanel.tsx
src/Explorer/Tabs/DocumentsTab.ts
src/Explorer/Tree/Database.ts
src/Explorer/Tree/StoredProcedure.ts
src/Platform/Hosted/extractFeatures.test.ts
src/Platform/Hosted/extractFeatures.ts
src/UserContext.ts
src/hooks/useKnockoutExplorer.ts

In addition this makes the URL-passed feature flags type safe

Remove Explorer.features

---

package-lock.json
package.json

Remove unused inline-css package

---

.github/workflows/ci.yml
preview/.azure/config
preview/README.md
preview/config.json
preview/index.js
preview/package-lock.json
preview/package.json
src/Common/CosmosClient.ts
src/Common/MessageHandler.ts
src/Common/__snapshots__/CosmosClient.test.ts.snap

Implements an Azure App Service Web App + Storage Account that allows for previewing any data explorer commit in the portal. Hopefully this makes it much easier to share work in progress without having to run the application locally or deploy to staging.
Portal Example URL:
https://ms.portal.azure.com/?dataExplorerSource=https%3A%2F%2Fcosmos-explorer-preview.azurewebsites.net%2Fcommit%2F73615cee5cefc5ce5f65edbe5df6edbc50ce5df7%2Fexplorer.html#@microsoft.onmicrosoft.com/resource/subscriptions/b9c77f10-b438-4c32-9819-eef8a654e478/resourceGroups/stfaul/providers/Microsoft.DocumentDb/databaseAccounts/stfaul-sql/dataExplorer

Automated Preview URLs

---

src/SelfServe/SelfServe.tsx
src/i18n.ts

This PR
- sets debug = true for i18n package (in prod and in development env)
- Ensures resource bundle loading happens only after i18n is initialized

Set debug = true for i18n

---

src/Explorer/Explorer.tsx
src/Explorer/SplashScreen/SplashScreen.tsx
src/Main.tsx
src/hooks/useObservableState.ts
src/hooks/useTabs.ts

This PR is just about moving the tabs array. I'm hoping to let it bake for a bit before merging the rest of the tabs in react work.
Preview here: https://ms.portal.azure.com/?dataExplorerSource=https%3A%2F%2Fcosmos-explorer-preview.azurewebsites.net%2Fcommit%2Fda809beb82bb54dc82da18eda41caaf7b9b6597f%2Fexplorer.html#@microsoft.onmicrosoft.com/resource/subscriptions/b9c77f10-b438-4c32-9819-eef8a654e478/resourceGroups/stfaul/providers/Microsoft.DocumentDb/databaseAccounts/stfaul-sql/dataExplorer

Move tabs state out into React

---

preview/index.js
preview/package-lock.json
preview/package.json
src/Explorer/Menus/NotificationConsole/NotificationConsoleComponent.tsx
src/Platform/Hosted/extractFeatures.ts

The idea here is to be able to use @southpolesteve's server to go to a URL like [https://cosmos-explorer-preview.azurewebsites.net/pull/625](https://ms.portal.azure.com/?dataExplorerSource=https%3A%2F%2Fcosmos-explorer-preview.azurewebsites.net%2Fcommit%2F8e0da246477ec31344bce81ff4c332d8b683a07c%2Fexplorer.html%3Ffeature.prUrl%3Dhttps%253A%252F%252Fgithub.com%252FAzure%252Fcosmos-explorer%252Fpull%252F625#@microsoft.onmicrosoft.com/resource/subscriptions/b9c77f10-b438-4c32-9819-eef8a654e478/resourceGroups/stfaul/providers/Microsoft.DocumentDb/databaseAccounts/stfaul-sql/dataExplorer) and end up here:

Pull request preview URLs

---

.github/PULL_REQUEST_TEMPLATE.md
src/Platform/Hosted/extractFeatures.ts

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/644)

Fix preview URL branch display, include link in new PRs

---

src/Explorer/Menus/NotificationConsole/NotificationConsoleComponent.tsx

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/651?feature.someFeatureFlagYouMightNeed=true)

Add rel='noreferrer'

---

src/Explorer/Explorer.tsx
src/Explorer/Panes/ExecuteSprocParamsPanel/__snapshots__/index.test.tsx.snap
src/Explorer/Panes/ExecuteSprocParamsPanel/index.test.tsx
src/Explorer/Panes/ExecuteSprocParamsPanel/index.tsx
src/Explorer/Tabs/StoredProcedureTab.ts

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/549)

Address TODO in Explorer

---

src/Contracts/ViewModels.ts
src/hooks/useKnockoutExplorer.ts

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/659?feature.someFeatureFlagYouMightNeed=true)

Fix feature flags in Portal

---

src/hooks/useDatabaseAccounts.tsx
src/hooks/useSubscriptions.tsx

Alpha sort subscriptions and accounts in dropdown

---

src/Explorer/Controls/NotebookGallery/GalleryViewerComponent.tsx

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/commit/591ce5ec94a100d3fb8d3a15a65d210b1408c4c7/gallery.html)

Hide favorite button from Standalone gallery

---

preview/index.js

Remove southpolesteve's subscription and account from URL

---

src/Explorer/Tabs/StoredProcedureTab.html
src/Explorer/Tabs/TabsBase.ts
src/Explorer/Tabs/TabsManager.html

Misc fixes from #500 that I'd like to merge separately

Misc fixes from #500

---

src/ConfigContext.ts
src/Juno/JunoClient.test.ts
src/Juno/JunoClient.ts
src/Platform/Hosted/extractFeatures.ts

Verified that the juno endpoint override works for
- Standalone DE
- DE running in Portal
- Standalone gallery
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/700)

Add a feature flag to override Juno endpoint

---

package-lock.json
package.json

Remove unused @types/prop-types

---

.github/workflows/ci.yml
.github/workflows/cleanup.yml
test/mongo/container.spec.ts
test/sql/resourceToken.spec.ts
test/utils/shared.ts

Retry E2E tests up to 3 times

---

.github/workflows/ci.yml

Disable Emulator Test

---

src/Explorer/Tree/Collection.ts

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/722?feature.someFeatureFlagYouMightNeed=true)

Lazy load SchemaAnalyzerTab

---

src/Explorer/Explorer.tsx
src/Explorer/Notebook/NotebookManager.tsx
src/Explorer/Tabs/GalleryTab.tsx

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/721)

Remove 'any' from existing lazy loaded tabs

---

src/Explorer/Controls/DiffEditor/DiffEditorComponent.ts
src/Explorer/Controls/Editor/EditorComponent.ts
src/Explorer/Controls/Editor/EditorReact.tsx
src/Explorer/Controls/JsonEditor/JsonEditorComponent.ts
src/Explorer/Controls/Settings/SettingsSubComponents/IndexingPolicyComponent.tsx
src/Explorer/LazyMonaco.ts
src/Explorer/Tabs/ScriptTabBase.ts
webpack.config.js

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/720)
Before:
After:

Lazy loaded Monaco

---

src/GitHub/GitHubConnector.ts
src/GitHub/GitHubOAuthService.test.ts
src/GitHub/GitHubOAuthService.ts

Use postRobot to listen for GitHub OAuth messages

---

src/Bindings/ReactBindingHandler.ts
src/Common/Splitter.ts
src/Explorer/Controls/InputTypeahead/InputTypeahead.ts
src/Explorer/Notebook/NotebookComponent/__mocks__/rx-jupyter.ts
src/Explorer/Notebook/NotebookContentClient.ts
src/Explorer/Tree/AccessibleVerticalList.ts
src/NotebookWorkspaceManager/NotebookWorkspaceResourceProviderMockClients.ts
src/Terminal/index.ts
tsconfig.strict.json

Now they meet noUnusedParameters
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/604)

Get our previously strict files a bit tighter

---

src/Explorer/Explorer.tsx

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/774)

Fix isFixedCollectionWithSharedThroughputSupported flag

---

.github/workflows/ci.yml
test/mongo/container32.spec.ts

Add Mongo 3.2 End to End Test

---

src/Common/Tooltip/InfoTooltip.tsx
src/Explorer/Controls/Dialog.tsx
src/Explorer/Controls/Header/GalleryHeaderComponent.tsx
src/Explorer/Notebook/NotebookRenderer/Prompt.tsx
src/Explorer/Notebook/NotebookRenderer/decorators/CellLabeler.tsx
src/hooks/useGraphPhoto.tsx
tsconfig.strict.json

Fixed typescript error of following files.
InfoToolTip.tsx,
Dialog.tsx, 
GallaryHeaderComponent.tsx
Prompt.tsx, 
CellLabeler.tsx
useGraphPhooto.tsx
files

fixed typescript errors of InfoToolTip, Dialog, GallaryHeaderComponent

---

src/SelfServe/SelfServeUtils.test.tsx
src/SelfServe/SelfServeUtils.tsx
src/i18n.ts

This PR
- The validations for min of number input was a 'not' check. This meant that if this value was set to 0, it was a false positive. Now changed the check to see if it is undefined
- Removed temporary debug flag on i18n

Fixes for selfserve

---

src/Main.tsx
src/applyExplorerBindings.ts

Remove show div after applyExplorerBindings

---

src/Explorer/Controls/Accordion/AccordionComponent.tsx
src/Explorer/Notebook/SchemaAnalyzer/SchemaAnalyzerHeader.tsx
tsconfig.strict.json

Fixed typescript strict of accordianComponent.tsx and schemaAnalyserHeader.tsx file

fixed typescript strict of accordianComponent.tsx and schemaAnalyser

---

src/Explorer/Controls/Dialog.tsx
src/Explorer/Controls/NotebookGallery/GalleryViewerComponent.tsx
src/Explorer/Controls/NotebookGallery/__snapshots__/GalleryViewerComponent.test.tsx.snap
src/Explorer/Controls/NotebookViewer/NotebookViewerComponent.tsx
src/Explorer/Controls/Settings/__snapshots__/SettingsComponent.test.tsx.snap
src/Explorer/Explorer.tsx
src/Explorer/Panes/GitHubReposPanel/__snapshots__/GitHubReposPanel.test.tsx.snap
src/Explorer/Panes/StringInputPane/__snapshots__/StringInputPane.test.tsx.snap
src/Explorer/Panes/__snapshots__/DeleteDatabaseConfirmationPanel.test.tsx.snap
src/Main.tsx

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/806)

Move <Dialog/> state to zustand

---

src/Common/EntityValue.tsx
src/ConfigContext.ts
src/hooks/useConfig.ts
tsconfig.strict.json

fixed typescript strict error of EntityValue.tsx

fixed ts strict error of EntityValue.tsx

---

src/SelfServe/SelfServeComponent.tsx
src/SelfServe/SelfServeTypes.ts
src/Shared/Telemetry/TelemetryConstants.ts

Added telemetry for
- Component Load
- Save

Added self serve component telemetry

---

src/Explorer/ContextMenuButtonFactory.ts
src/Explorer/Controls/Settings/__snapshots__/SettingsComponent.test.tsx.snap
src/Explorer/Explorer.tsx
src/Explorer/Menus/CommandBar/CommandBarComponentAdapter.tsx
src/Explorer/Menus/CommandBar/CommandBarComponentButtonFactory.test.ts
src/Explorer/Menus/CommandBar/CommandBarComponentButtonFactory.tsx
src/Explorer/Panes/GitHubReposPanel/__snapshots__/GitHubReposPanel.test.tsx.snap
src/Explorer/Panes/StringInputPane/__snapshots__/StringInputPane.test.tsx.snap
src/Explorer/Panes/__snapshots__/DeleteDatabaseConfirmationPanel.test.tsx.snap
src/Explorer/SplashScreen/SplashScreen.test.ts
src/Explorer/SplashScreen/SplashScreen.tsx
src/Explorer/Tree/Collection.test.ts
src/Main.tsx

Removed
Explorer.addCollectionText
Explorer.collectionTitle
Explorer.collectionTreeNodeAltText
Explorer.deleteCollectionText
Explorer.deleteDatabaseText
Explorer.refreshTreeTitle

remove explorer api properties

---

src/Common/DatabaseAccountUtility.ts
src/Contracts/DataModels.ts
src/Explorer/Explorer.tsx
src/Explorer/Notebook/SchemaAnalyzer/SchemaAnalyzerUtils.ts
src/Explorer/Tree/ResourceTreeAdapter.tsx

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/826)

Hide hosted shells and schema analyzer if VNET, Firewall or Private endpoints is enabled

---

src/Contracts/ViewModels.ts
src/Explorer/Controls/Settings/__snapshots__/SettingsComponent.test.tsx.snap
src/Explorer/Explorer.tsx
src/Explorer/Panes/CassandraAddCollectionPane/CassandraAddCollectionPane.tsx
src/Explorer/Panes/GitHubReposPanel/__snapshots__/GitHubReposPanel.test.tsx.snap
src/Explorer/Panes/StringInputPane/__snapshots__/StringInputPane.test.tsx.snap
src/Explorer/Panes/UploadItemsPane/__snapshots__/UploadItemsPane.test.tsx.snap
src/Explorer/Panes/__snapshots__/DeleteDatabaseConfirmationPanel.test.tsx.snap
src/Shared/AddCollectionUtility.ts
src/UserContext.ts
src/hooks/useKnockoutExplorer.ts

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/840?feature.someFeatureFlagYouMightNeed=true)

Remove Explorer.collectionCreationDefaults

---

src/Explorer/SplashScreen/SplashScreen.tsx

Open Query SQL Only

---

src/Explorer/Explorer.tsx

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/849?feature.someFeatureFlagYouMightNeed=true)

Fix Enable Synapse Link

---

src/Explorer/Panes/GraphStylingPanel/GraphStylingPanel.tsx
src/Explorer/Panes/UploadItemsPane/__snapshots__/UploadItemsPane.test.tsx.snap

https://user-images.githubusercontent.com/81285216/120617947-363cb580-c478-11eb-9e4b-dc413462a913.mp4

Fixed graph style panel close issue

---

src/Explorer/Panes/AddDatabasePanel/AddDatabasePanel.tsx
src/Explorer/Panes/AddDatabasePanel/__snapshots__/AddDatabasePanel.test.tsx.snap

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/861?feature.someFeatureFlagYouMightNeed=true)

Hide provision throughput checkbox for serverless account

---

src/Explorer/Graph/GraphExplorerComponent/GraphUtil.test.ts
src/global.d.ts

Remove window.jQuery

---

src/Explorer/Controls/Settings/__snapshots__/SettingsComponent.test.tsx.snap
src/Explorer/Explorer.tsx
src/Explorer/Panes/GitHubReposPanel/__snapshots__/GitHubReposPanel.test.tsx.snap
src/Explorer/Panes/StringInputPane/__snapshots__/StringInputPane.test.tsx.snap
src/Explorer/Panes/__snapshots__/DeleteDatabaseConfirmationPanel.test.tsx.snap
src/Explorer/Tree/ResourceTokenCollection.ts
src/RouteHandlers/TabRouteHandler.ts
src/UserContext.ts
src/hooks/useKnockoutExplorer.ts

Remove Explorer.configure

---

src/Explorer/Controls/Settings/SettingsComponent.tsx
src/Explorer/Controls/Settings/SettingsSubComponents/ConflictResolutionComponent.test.tsx
src/Explorer/Controls/Settings/SettingsSubComponents/ConflictResolutionComponent.tsx
src/Explorer/Controls/Settings/SettingsSubComponents/ScaleComponent.test.tsx
src/Explorer/Controls/Settings/SettingsSubComponents/ScaleComponent.tsx
src/Explorer/Controls/Settings/SettingsSubComponents/SubSettingsComponent.test.tsx
src/Explorer/Controls/Settings/SettingsSubComponents/SubSettingsComponent.tsx
src/Explorer/Controls/Settings/__snapshots__/SettingsComponent.test.tsx.snap
src/Explorer/Explorer.tsx
src/Explorer/Menus/CommandBar/CommandBarComponentButtonFactory.test.ts
src/Explorer/Menus/CommandBar/CommandBarComponentButtonFactory.tsx
src/Utils/CloudUtils.ts

Remove Settings Component dependency on Explorer

---

src/Explorer/Explorer.tsx
src/Explorer/OpenActions/OpenActions.tsx

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/888?feature.someFeatureFlagYouMightNeed=true)

remove_Explorer.openCassandraAddCollectionPane

---

src/Explorer/Tabs/QueryTab/QueryTabComponent.tsx
src/Platform/Hosted/Components/ConnectExplorer.tsx

Fix Incorrect Image Links

---

src/Explorer/Controls/TreeComponent/TreeComponent.tsx
src/Explorer/Controls/TreeComponent/__snapshots__/TreeComponent.test.tsx.snap
src/Explorer/Tree/__snapshots__/ResourceTreeAdapter.test.tsx.snap
src/Explorer/Tree/__snapshots__/ResourceTreeAdapterForResourceToken.test.tsx.snap

Resolves https://msdata.visualstudio.com/CosmosDB/_workitems/edit/1104089
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/895?feature.someFeatureFlagYouMightNeed=true)

Add tree and treeitem roles to Resource Tree

---

src/ConfigContext.ts
src/Utils/AuthorizationUtils.ts
src/hooks/useAADAuth.ts
src/hooks/useDatabaseAccounts.tsx
src/hooks/useDirectories.tsx
src/hooks/useGraphPhoto.tsx
src/hooks/useSubscriptions.tsx

This will allow us to test out alternative login authorities in non-public clouds
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/896?feature.someFeatureFlagYouMightNeed=true)

Allow dynamic MSAL Authority

---

src/Explorer/Controls/Editor/EditorReact.tsx
src/Explorer/Tabs/QueryTab/QueryTabComponent.tsx

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/907)

Fix for QueryTab Load More

---

package-lock.json
package.json
src/Explorer/Controls/NotebookViewer/NotebookViewerComponent.tsx
src/Explorer/Notebook/NotebookClientV2.ts
src/Explorer/Notebook/NotebookComponent/NotebookComponent.less
src/Explorer/Notebook/NotebookRenderer/NotebookReadOnlyRenderer.less
src/Explorer/Notebook/NotebookRenderer/NotebookReadOnlyRenderer.tsx
src/Explorer/Notebook/NotebookRenderer/NotebookRenderer.less
src/Explorer/Notebook/NotebookRenderer/NotebookRenderer.tsx
src/Explorer/Notebook/notebookClientV2.test.ts

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/901?feature.someFeatureFlagYouMightNeed=true)
This change reverts the editor to Code Mirror

Switch notebook editor from Monaco back to Code Mirror

---

package-lock.json
package.json
src/GitHub/GitHubConnector.ts

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/910)

TypeScript 4.3

---

.eslintignore
src/Explorer/Controls/QueriesGridReactComponent/QueriesGridComponent.tsx
src/Explorer/Controls/Tabs/TabComponent.tsx
src/Explorer/Graph/GraphExplorerComponent/EditorNeighborsComponent.tsx

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/923?feature.someFeatureFlagYouMightNeed=true)

resolve_eslint_QueriesGridComponent

---

.eslintignore
src/Explorer/Tables/Constants.ts
src/GalleryViewer/GalleryViewer.tsx

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/914?feature.someFeatureFlagYouMightNeed=true)

resolve_eslint_Tables.Constants

---

src/Explorer/Notebook/NotebookRenderer/StatusBar.tsx

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/936?feature.someFeatureFlagYouMightNeed=true)

Fix notebooks not rendering

---

src/GitHub/GitHubConnector.ts

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/937?feature.someFeatureFlagYouMightNeed=true)

Fix connect to GitHub

---

configs/mpac.json
src/Common/Constants.ts
src/ConfigContext.ts
src/Explorer/Explorer.tsx
src/Platform/Hosted/extractFeatures.ts
src/hooks/useKnockoutExplorer.ts

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/938?feature.someFeatureFlagYouMightNeed=true)

Cleanup Schema Analyzer feature flag

---

src/Platform/Hosted/Components/SwitchAccount.tsx
src/Platform/Hosted/Components/SwitchSubscription.tsx
tsconfig.strict.json

Fixed TypeScript strict issues 1

---

src/Explorer/Notebook/NotebookManager.tsx
src/Explorer/Panes/PanelContainerComponent.tsx
src/Explorer/Panes/Tables/AddTableEntityPanel.tsx
src/Explorer/Panes/Tables/Validators/EntityTableHelper.tsx
src/Explorer/Panes/Tables/__snapshots__/AddTableEntityPanel.test.tsx.snap
src/Explorer/Tabs/QueryTablesTab.tsx
src/hooks/useSidePanel.ts

- removed `PanelContainerComponent` from `AddTableEntityPanel`
- added input validation to prevent empty property name and property type

Fix AddTableEntityPanel

---

less/resourceTree.less
less/tree.less

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/953?feature.someFeatureFlagYouMightNeed=true)
https://user-images.githubusercontent.com/79906609/126635782-6ef877e0-3969-45e5-867f-054f2556e777.mp4

Fixed resourse tree collapse issue

---

src/Explorer/Panes/PanelComponent.less
src/Explorer/Panes/Tables/AddTableEntityPanel.tsx
src/Explorer/Panes/Tables/EditTableEntityPanel.tsx
src/Explorer/Panes/Tables/Validators/EntityTableHelper.tsx
src/Explorer/Panes/Tables/__snapshots__/EditTableEntityPanel.test.tsx.snap
src/Explorer/Tabs/QueryTablesTab.tsx

- replaced `PanelContainerComponent` with `RightPaneForm` and refactored code accordingly
- adjusted some CSS

Clean up EditTableEntityPanel

---

src/Explorer/Notebook/NotebookManager.tsx
src/Explorer/Notebook/useNotebook.ts

Add initializeGitHubRepos function in useNotebooks store

---

src/Common/ResourceTreeContainer.tsx
src/Platform/Hosted/extractFeatures.ts

Turn off react resource tree

---

src/Explorer/Controls/Dialog.tsx
src/Explorer/Controls/QueriesGridReactComponent/QueriesGridComponent.tsx
src/Explorer/DataSamples/DataSamplesUtil.test.ts
src/Explorer/DataSamples/DataSamplesUtil.ts
src/Explorer/Explorer.tsx
src/Explorer/Notebook/NotebookComponent/epics.ts
src/Explorer/Notebook/NotebookManager.tsx
src/Explorer/Tables/DataTable/TableCommands.ts
src/Explorer/Tabs/ConflictsTab.ts
src/Explorer/Tabs/DocumentsTab.ts
src/Explorer/Tabs/MongoDocumentsTab.ts
src/Explorer/Tabs/NotebookV2Tab.ts
src/Explorer/Tree/ConflictId.ts
src/Explorer/Tree/DocumentId.ts
src/Explorer/Tree/ResourceTree.tsx
src/Explorer/Tree/ResourceTreeAdapter.tsx
src/Explorer/Tree/StoredProcedure.ts
src/Explorer/Tree/Trigger.ts
src/Explorer/Tree/UserDefinedFunction.ts
src/Utils/GalleryUtils.test.ts
src/Utils/GalleryUtils.ts
tsconfig.strict.json

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/965?feature.someFeatureFlagYouMightNeed=true)

Replace window.confirm and window.alert with modal dialog

---

src/Common/Constants.ts
src/Explorer/ContextMenuButtonFactory.tsx
src/Explorer/Menus/CommandBar/CommandBarComponentButtonFactory.test.ts
src/Explorer/Menus/CommandBar/CommandBarComponentButtonFactory.tsx
src/Explorer/SplashScreen/SplashScreen.tsx
src/Explorer/Tree/ResourceTree.tsx
src/Platform/Hosted/extractFeatures.ts

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/978)

Disable notebooks temporarily

---

.github/workflows/ci.yml
test/mongo/container.spec.ts

Disable Notebooks Test

---

src/Platform/Hosted/extractFeatures.ts

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/983)

Fix notebooksTemporarilyDown feature flag

---

webpack.config.js

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/988?feature.someFeatureFlagYouMightNeed=true)

Polyfill Buffer

---

.eslintignore
src/Controls/Heatmap/Heatmap.test.ts
src/Controls/Heatmap/Heatmap.ts

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/986?feature.someFeatureFlagYouMightNeed=true)

resolve_eslint_Contracts

---

src/Explorer/Panes/AddCollectionPanel.tsx

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/989?feature.someFeatureFlagYouMightNeed=true)

Move synapse link out of advanced section in add collection panel

---

src/SelfServe/SqlX/SqlX.rp.ts
src/SelfServe/SqlX/SqlX.tsx

Bug Fixes for the recent SQLx Approximate Cost Calculation - error in region name passed to fetch prices API when multiple space characters in string. Replaced .replace usage with .split followed by .join

Sqlx approx cost bug fixes

---

jest.config.js

Temporarily lower test coverage threshold to make the unit tests pass in master.

Temporarily lower test coverage threshold

---

src/Common/MongoProxyClient.test.ts
src/Common/MongoProxyClient.ts
src/Explorer/Tabs/QueryTab/QueryTabComponent.tsx
src/Platform/Hosted/extractFeatures.test.ts

https://user-images.githubusercontent.com/81285216/133415325-b60a48df-f2ce-415e-9546-5fee0b68878f.mp4

Fix execute query keyboard focus moves to hidden element under 'Results' section of executed Query 1 blade

---

src/Common/MongoProxyClient.test.ts
src/Common/MongoProxyClient.ts
src/Common/Tooltip/InfoTooltip.tsx
src/Explorer/Controls/ThroughputInput/__snapshots__/ThroughputInput.test.tsx.snap
src/Explorer/Panes/SettingsPane/SettingsPane.tsx
src/Explorer/Panes/SettingsPane/__snapshots__/SettingsPane.test.tsx.snap
src/Platform/Hosted/extractFeatures.test.ts

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1081?feature.someFeatureFlagYouMightNeed=true)
https://user-images.githubusercontent.com/79906609/133393485-d16f846d-44dc-430f-ae36-168d4c5eb4b1.mp4

fixed setting keyboard accessibility issue

---

src/Explorer/Panes/DeleteCollectionConfirmationPane/DeleteCollectionConfirmationPane.tsx
src/Explorer/Panes/DeleteCollectionConfirmationPane/__snapshots__/DeleteCollectionConfirmationPane.test.tsx.snap
src/Explorer/Panes/DeleteDatabaseConfirmationPanel.tsx
src/Explorer/Panes/__snapshots__/DeleteDatabaseConfirmationPanel.test.tsx.snap

Fix delete container and database labels appearing text are not associated with the edit fields

---

src/Explorer/Tabs/UserDefinedFunctionTabContent.tsx

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1068?feature.someFeatureFlagYouMightNeed=true)
fixed UDF body association with JSON edit field issue

fixed UDF body association with JSON edit field issue

---

src/Explorer/Controls/TreeComponent/TreeComponent.tsx

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1093?feature.someFeatureFlagYouMightNeed=true)

Tooltip is not provided for 'More' control present on the page.

---

src/Explorer/Menus/NotificationConsole/NotificationConsoleComponent.tsx
src/Explorer/Menus/NotificationConsole/__snapshots__/NotificationConsoleComponent.test.tsx.snap

fixed incorrect notification console expand collapsed screen reader issue
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1095?feature.someFeatureFlagYouMightNeed=true)
https://user-images.githubusercontent.com/79906609/133990236-399eefb2-6c17-4be6-ad53-84570d07592c.mp4

fixed incorrect notification console expand collapsed screen reader issue

---

src/Explorer/Panes/PanelComponent.less

fixed horizontal scrollbar issue on 400% resize mode
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1099?feature.someFeatureFlagYouMightNeed=true)
https://user-images.githubusercontent.com/79906609/134137632-6ba27a3a-59c2-4f57-8ad0-a0700676b8ba.mp4

fixed horizontal scrollbar issue on 400% resize mode

---

src/Explorer/Panes/CassandraAddCollectionPane/CassandraAddCollectionPane.tsx

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1101)

Make these required fields

---

src/SelfServe/SqlX/SqlX.rp.ts
src/SelfServe/SqlX/SqlX.tsx

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1018?feature.someFeatureFlagYouMightNeed=true)

Telemetry added for calculate cost function

---

src/Explorer/Controls/InputTypeahead/InputTypeahead.less
src/Explorer/Controls/InputTypeahead/InputTypeaheadComponent.tsx
src/Explorer/Controls/InputTypeahead/__snapshots__/InputTypeaheadComponent.test.tsx.snap
src/Explorer/Controls/TreeComponent/__snapshots__/TreeComponent.test.tsx.snap

fixed graph input query JAWS screen reader issue
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1108?feature.someFeatureFlagYouMightNeed=true)
https://user-images.githubusercontent.com/79906609/134471388-0fdb75f5-f429-459b-abf4-a76159824e9e.mp4

fixed graph input query JAWS screen reader issue

---

src/Explorer/Controls/Settings/SettingsSubComponents/IndexingPolicyRefresh/__snapshots__/IndexingPolicyRefreshComponent.test.tsx.snap
src/Explorer/Controls/Settings/SettingsSubComponents/ThroughputInputComponents/__snapshots__/ThroughputInputAutoPilotV3Component.test.tsx.snap
src/Explorer/Controls/Settings/SettingsSubComponents/__snapshots__/ScaleComponent.test.tsx.snap
src/Explorer/Controls/Settings/SettingsSubComponents/__snapshots__/SubSettingsComponent.test.tsx.snap
src/Explorer/Controls/Settings/__snapshots__/SettingsRenderUtils.test.tsx.snap
src/Explorer/Controls/TreeComponent/__snapshots__/TreeComponent.test.tsx.snap
src/Explorer/Panes/AddDatabasePanel/AddDatabasePanel.tsx
src/Explorer/SplashScreen/SplashScreen.tsx

https://user-images.githubusercontent.com/81285216/134474398-82c01f9f-1d2e-4bf1-8ef0-9baf40048e7e.mp4

Fix keyboard focus does not retain on 'New Database' button after closing the 'New Database' blade via ESC key

---

less/documentDB.less
src/Explorer/Controls/Settings/SettingsSubComponents/ThroughputInputComponents/__snapshots__/ThroughputInputAutoPilotV3Component.test.tsx.snap
src/Explorer/Controls/Settings/__snapshots__/SettingsRenderUtils.test.tsx.snap
src/Explorer/Controls/TreeComponent/__snapshots__/TreeComponent.test.tsx.snap
src/Explorer/Graph/GraphExplorerComponent/graphExplorer.less
src/Explorer/Panes/Tables/TableQuerySelectPanel/TableQuerySelectPanel.test.tsx
src/Explorer/Panes/Tables/TableQuerySelectPanel/__snapshots__/TableQuerySelectPanel.test.tsx.snap
src/Explorer/Tabs/QueryTab/QueryTabComponent.tsx

Zoomed: 200% to 300%
https://user-images.githubusercontent.com/81285216/134341648-89e1b889-2b95-46cc-ab7c-6c17c19fcb62.mp4

Fix execute Query 'Results' and 'Query status' section controls gets truncated at 200% resize mode of 'Query1' blade

---

src/Explorer/Menus/CommandBar/CommandBarComponentButtonFactory.tsx

Fix new database panel open issue related a11y

---

.eslintignore
.eslintrc.js
src/Explorer/Tree/Trigger.ts
src/GitHub/GitHubOAuthService.ts
src/Juno/JunoClient.test.ts
src/Juno/JunoClient.ts

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1126?feature.someFeatureFlagYouMightNeed=true)
Fixed eslint of following file 
Trigger.ts
GitHubConnector.ts
GitHubOAuthService.ts
JunoClient.ts
JunoClient.test.ts

fixed eslint of Trigger.ts GithubOAuthService.ts etc

---

.eslintignore
src/Explorer/Tables/QueryBuilder/ClauseGroup.ts
src/Explorer/Tables/QueryBuilder/ClauseGroupViewModel.ts

Fix ESLint issues 5: For ClauseGroup and ClauseGroupViewModel files

---

.eslintignore
src/Explorer/Tables/DataTable/DataTableOperations.ts
src/Explorer/Tables/DataTable/TableCommands.ts
src/Explorer/Tables/DataTable/TableEntityCache.ts
src/Explorer/Tables/Entities.ts

ESLint issues are fix for below listed files,
1. TableCommands
2. DataTableOperations
3. Entities
4. TableEntityCache

Fix ESLint issues 6: For TableCommands and other files

---

src/Contracts/DataModels.ts
src/Explorer/Controls/Settings/SettingsComponent.tsx
src/Explorer/Controls/ThroughputInput/ThroughputInput.tsx
src/Explorer/Explorer.tsx
src/Explorer/Menus/CommandBar/CommandBarComponentButtonFactory.tsx
src/Explorer/SplashScreen/SplashScreen.tsx
src/Explorer/Tree/Collection.ts
src/Explorer/Tree/Database.tsx
src/Explorer/useDatabases.ts

1. When calculating the total throughput used, multiply by the number of regions.
2. In settings tab, load all collection and database offers before calculating the total throughput used.
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1156?feature.someFeatureFlagYouMightNeed=true)

Fix throughputcap check

---

src/SelfServe/SqlX/SqlX.rp.ts
src/SelfServe/SqlX/SqlX.tsx
src/SelfServe/SqlX/SqlxTypes.ts

- Displays the currency code returned by Fetch Prices API for sqlx cost calculation now.

Sqlx currency code fix

---

src/Explorer/Explorer.tsx

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1157)

Fixed quickstarts for phoenix runtime

---

src/ConfigContext.ts

add juno test3 to allow list

---

less/documentDB.less

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1165?feature.someFeatureFlagYouMightNeed=true)
https://user-images.githubusercontent.com/79906609/143772476-3f5a3e2b-2b14-4f3f-81e8-0d3053ae41e9.mp4

fixed horizontal scroll issue on zoom 400%

---

less/documentDB.less

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1169?feature.someFeatureFlagYouMightNeed=true
)

1413651_Refresh_button_missing

---

src/Explorer/Menus/CommandBar/CommandBarComponentAdapter.tsx
src/Explorer/Menus/CommandBar/CommandBarComponentButtonFactory.tsx
src/Explorer/Tree/ResourceTree.tsx

This PR:
- Hides command bar buttons["New Notebook", "Connect to GitHub""] when phoenix is false.
- Hides Connect status button when phoenix is false.

Hide commandbar btns when phoenix flag is false

---

src/Explorer/OpenFullScreen.tsx

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1173?feature.someFeatureFlagYouMightNeed=true)
Fixed [Issue1](https://msdata.visualstudio.com/CosmosDB/_workitems/edit/1538181/) [Issue2](https://msdata.visualstudio.com/CosmosDB/_workitems/edit/1471930/)
https://user-images.githubusercontent.com/79906609/145664886-679f32db-d077-4f17-89f5-7654a9749638.mp4

fixed screenreader copy issue

---

src/Explorer/Controls/ThroughputInput/ThroughputInput.tsx
src/Explorer/Panes/CassandraAddCollectionPane/CassandraAddCollectionPane.tsx

Fixed [issue](https://msdata.visualstudio.com/CosmosDB/_workitems/edit/1430452/)

fixed unshared collection error for cassandra

---

src/Explorer/Panes/AddCollectionPanel.tsx
src/Explorer/Panes/DeleteCollectionConfirmationPane/DeleteCollectionConfirmationPane.tsx

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1179?feature.someFeatureFlagYouMightNeed=true)
Issue: https://msdata.visualstudio.com/CosmosDB/_workitems/edit/1485813/
https://user-images.githubusercontent.com/79906609/146929917-9148de2a-ac57-40da-90b8-a65219573b80.mp4

Fixed inconsistent use of collection id and name

---

src/Explorer/Tabs/QueryTab/QueryTabComponent.tsx

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1180?feature.someFeatureFlagYouMightNeed=true)
Issue: https://msdata.visualstudio.com/CosmosDB/_workitems/edit/1413653
https://user-images.githubusercontent.com/79906609/147235428-337353f9-02ef-4194-8bdd-166c8eab9507.mp4

Fixed querytab corresponding command bar

---

src/Explorer/Panes/AddCollectionPanel.tsx

Updating large pkey value text to match backend value

---

src/Common/CosmosClient.ts

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1190?feature.someFeatureFlagYouMightNeed=true)

Add headers to unblock merge private preview customers

---

src/Utils/EndpointValidation.ts

Add Mooncake and Fairfax BE and Mongo endpoints to allowed endpoints

---

src/Explorer/Notebook/NotebookContainerClient.ts

Always schedule memory call

---

src/Contracts/DataModels.ts
src/Explorer/Explorer.tsx
src/Explorer/Notebook/NotebookContainerClient.ts
src/Phoenix/PhoenixClient.ts

This PR:
- Adds UX for error Info while connecting to workspace
- Added specific error messages to the pre validation errors.
- Validations considered:
1. MaxAllocationTimeExceeded
2. MaxDbAccountsPerUserExceeded
3. MaxUsersPerDbAccountExceeded
4. AllocationValidationResult
5. RegionNotServicable
6. SubscriptionNotAllowed
Images:

Add UX for error Information for Phoenix workspace connection

---

src/quickstart.html

Fix Emulator Quick Start Links

---

.github/workflows/ci.yml
preview/package.json

Update subscription for preview PRs

---

src/Explorer/Controls/TreeComponent/TreeComponent.tsx
src/Explorer/Controls/TreeComponent/__snapshots__/TreeComponent.test.tsx.snap
src/Explorer/Explorer.tsx
src/Explorer/Menus/CommandBar/CommandBarComponentButtonFactory.tsx
src/Explorer/Panes/AddCollectionPanel.tsx
src/Explorer/Panes/PanelLoadingScreen.tsx
src/Explorer/Panes/__snapshots__/AddCollectionPanel.test.tsx.snap
src/Explorer/SplashScreen/SplashScreen.tsx
src/Explorer/Tabs/DocumentsTab.ts
src/Explorer/Tabs/Tabs.tsx
src/Explorer/Tree/ResourceTree.tsx
src/Explorer/Tutorials/QuickstartTutorial.tsx
src/Main.tsx
src/hooks/useTeachingBubble.ts

This PR covers step 3 (Product UI Tour) of [new quickstart design](https://www.figma.com/file/m6MTakDdn9hhZWmAN9H4mG/COSP-5x5?node-id=395%3A84796).
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1270)

Add teaching bubbles after creating sample DB

---

src/Contracts/ExplorerContracts.ts
src/Explorer/SplashScreen/SplashScreen.tsx
src/Explorer/Tabs/ConnectTab.tsx
src/Explorer/Tabs/Tabs.tsx
src/Explorer/Tutorials/QuickstartTutorial.tsx
src/Main.tsx
src/hooks/useTabs.ts

Design: 
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1273?feature.someFeatureFlagYouMightNeed=true)

Add connect tab for new quick start

---

sampleData/sqlSampleData.json
src/Contracts/ViewModels.ts
src/Explorer/Panes/AddCollectionPanel.tsx
src/Explorer/SplashScreen/SplashScreen.test.ts
src/Explorer/SplashScreen/SplashScreen.tsx
src/Explorer/Tabs/ConnectTab.tsx
src/Explorer/Tabs/Tabs.tsx
src/Explorer/Tree/Collection.ts
src/Explorer/Tree/Database.tsx
src/Explorer/Tree/ResourceTree.tsx
src/Explorer/Tutorials/QuickstartCarousel.tsx
src/Explorer/Tutorials/QuickstartTutorial.tsx
src/Main.tsx
src/Platform/Hosted/extractFeatures.ts
src/Shared/StorageUtility.ts
src/UserContext.ts
src/hooks/useCarousel.ts
src/hooks/useTeachingBubble.ts
test/cassandra/container.spec.ts
test/graph/container.spec.ts
test/mongo/container.spec.ts
test/mongo/container32.spec.ts
test/sql/container.spec.ts
test/tables/container.spec.ts

- store database account id in local storage
- if the database account id is not in local storage, show quick start carousel
- show coach mark in home page only after carousel is closed
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1278?feature.someFeatureFlagYouMightNeed=true)

Add condition for showing quick start carousel

---

src/Contracts/DataModels.ts
src/Explorer/Tutorials/QuickstartCarousel.tsx
src/UserContext.ts
src/hooks/useKnockoutExplorer.ts
test/cassandra/container.spec.ts
test/graph/container.spec.ts
test/mongo/container.spec.ts
test/mongo/container32.spec.ts
test/sql/container.spec.ts
test/tables/container.spec.ts

Only show carousel if the account was created within a week.

Add check of account creation time to show carousel

---

src/Explorer/Panes/AddCollectionPanel.tsx
src/Explorer/SplashScreen/SplashScreen.tsx
src/Explorer/Tutorials/QuickstartCarousel.tsx
src/Explorer/Tutorials/QuickstartTutorial.tsx
src/Shared/Telemetry/TelemetryConstants.ts
src/UserContext.ts

Refer to page 8-11 of [this document](https://microsoftapc.sharepoint.com/:w:/t/AbhinavOpenShare/ERkwgoApnp1JvB1jgKtCL3oBDSBu_NbNX7WaTXOpvwuccg?e=HLZsaz&wdOrigin=TEAMS-ELECTRON.p2p.bim&wdExp=TEAMS-CONTROL&wdhostclicktime=1654036876079) for details.
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1285?feature.someFeatureFlagYouMightNeed=true)

Add telemetry for new quick start

---

package-lock.json
package.json
src/Common/CosmosClient.test.ts
src/Common/CosmosClient.ts
src/Common/dataAccess/createCollection.ts
src/Common/dataAccess/createDatabase.ts
src/Common/dataAccess/readOfferWithSDK.ts
src/Common/dataAccess/updateCollection.ts
src/Common/dataAccess/updateOffer.ts
src/Explorer/SplashScreen/SplashScreen.tsx

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1287?feature.someFeatureFlagYouMightNeed=true)

Upgrade JS SDK version to 3.16.1

---

src/GalleryViewer/GalleryViewer.tsx

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1282)

Fix Official Samples not loading when Gallery tab is opened

---

src/Explorer/SplashScreen/SplashScreen.tsx
src/Explorer/Tabs/Tabs.tsx
src/Explorer/Tutorials/QuickstartTutorial.tsx
src/Main.tsx
src/Shared/Telemetry/TelemetryConstants.ts
src/hooks/useTabs.ts

- Added telemetry when user completes the UI tour
- Changed the home page into a tab that can be activated while other tabs are open
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1299?feature.someFeatureFlagYouMightNeed=true)

Improve quickstart teaching bubble telemetries and make the home page a tab

---

src/Contracts/DataModels.ts
src/Phoenix/PhoenixClient.ts

This PR refactors the text messages displayed on phoenix connection warning/error.

Refactor text messages

---

src/Explorer/Menus/CommandBar/CommandBarComponentAdapter.tsx
src/Explorer/Menus/CommandBar/CommandBarComponentButtonFactory.tsx
src/Explorer/Notebook/useNotebook.ts

Hide connect button id flight notebooks is false and show connect button status only if phoenix features are used"

Hide connect button incase Phoenix Notebooks flight is false

---

.github/workflows/ci.yml

Use my own ms account to upload nuget packages

---

src/Contracts/ViewModels.ts
src/Explorer/Controls/Notebook/NotebookTerminalComponent.tsx
src/Explorer/Controls/Settings/__snapshots__/SettingsComponent.test.tsx.snap
src/Explorer/Explorer.tsx
src/Explorer/Menus/CommandBar/CommandBarComponentButtonFactory.tsx
src/Explorer/Notebook/NotebookContainerClient.ts
src/Explorer/Notebook/useNotebook.ts
src/Explorer/Panes/GitHubReposPanel/__snapshots__/GitHubReposPanel.test.tsx.snap
src/Explorer/Panes/StringInputPane/__snapshots__/StringInputPane.test.tsx.snap
src/Explorer/Tabs/TerminalTab.tsx
src/Phoenix/PhoenixClient.ts
src/Terminal/JupyterLabAppFactory.ts

Add support for psql shell
- add new terminal type
- handle missing documentEndpoint property

Add support for psql shell

---

src/Explorer/Quickstart/QuickstartGuide.tsx
src/Explorer/SplashScreen/SplashScreen.less
src/Explorer/SplashScreen/SplashScreen.tsx
src/UserContext.ts

1. Text changes
2. Added code font for PSQL commands
3. Next step and tip items are not aligned with the main buttons above
4. Video width increased to 90% to align with the command textfields
5. Added links for net step and tip items
For details, please refer to this document: https://microsoft.sharepoint.com/:w:/t/azurepostgres-product-all/ERTPzAakQqtMn0xClwKWLdoBEzQwR--FqcUuF06QEZNeJQ?e=4%3AOI1Tid&at=9&CID=E1413AC1-7B7E-4FFC-A6E7-BCF27A3E5110
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1327?feature.someFeatureFlagYouMightNeed=true)

Quickstart UI changes

---

src/Contracts/ExplorerContracts.ts
src/Explorer/SplashScreen/SplashScreen.tsx
src/UserContext.ts
src/hooks/usePostgres.ts

Add password reset callout

---

docs/enums/selfserve_selfserveutils.bladetype.html
src/Common/CollapsedResourceTree.tsx
src/Common/ResourceTreeContainer.tsx
src/Explorer/Quickstart/Tutorials/MongoQuickstartTutorial.tsx
src/Explorer/SplashScreen/SplashScreen.tsx
src/SelfServe/SelfServeUtils.tsx
src/Utils/APITypeUtils.ts

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1330)

Text changes for API rebranding

---

src/Contracts/DataModels.ts
src/Explorer/Controls/Notebook/NotebookTerminalComponent.tsx
src/Explorer/Explorer.tsx
src/Explorer/Menus/CommandBar/CommandBarComponentButtonFactory.tsx
src/Explorer/Notebook/useNotebook.ts
src/Explorer/Quickstart/PostgreQuickstartCommands.ts
src/Explorer/Quickstart/QuickstartGuide.tsx
src/Explorer/SplashScreen/SplashScreen.tsx
src/Explorer/Tabs/QuickstartTab.tsx
src/Terminal/JupyterLabAppFactory.ts
src/Terminal/index.ts
src/UserContext.ts
src/hooks/useKnockoutExplorer.ts
src/hooks/useTerminal.ts

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1333?feature.someFeatureFlagYouMightNeed=true)

Integrate PSQL shell in quick start guide

---

src/Contracts/ExplorerContracts.ts

Add new message type for opening postgres networking blade

---

src/Explorer/SplashScreen/SplashScreen.tsx
src/UserContext.ts

show introductory video and password reset for first time try postgresql

---

src/Explorer/Quickstart/QuickstartFirewallNotification.tsx
src/Explorer/SplashScreen/SplashScreen.tsx
src/UserContext.ts

- Fix firewall rule screenshot not showing
- Reset password teaching bubble changes (always show unless user clicks on reset, remove close button, some text changes)
- Remove cosmos db intro video for postgres account
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1341?feature.someFeatureFlagYouMightNeed=true)

Postgres fixes

---

src/Explorer/Quickstart/QuickstartCarousel.tsx

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1346?feature.someFeatureFlagYouMightNeed=true)

Fix typo in 'tutorial' in Quick start.

---

src/hooks/useKnockoutExplorer.ts

Empty commit to trigger new build

Empty commit to trigger new build

---

src/Common/dataAccess/deleteDocument.ts
src/Common/dataAccess/getPartitionKeyValue.ts
src/Common/dataAccess/readDocument.ts
src/Common/dataAccess/updateDocument.ts
src/hooks/useKnockoutExplorer.ts

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1362?feature.someFeatureFlagYouMightNeed=true)

Fixes issue when CRUD with no parition key for all APIs

---

less/TableStyles/queryBuilder.less
src/Common/TableEntity.tsx
src/Common/Tooltip/InfoTooltip.tsx
src/Explorer/Controls/Settings/SettingsSubComponents/ThroughputInputComponents/ThroughputInputAutoPilotV3Component.tsx
src/Explorer/Controls/Settings/SettingsSubComponents/ThroughputInputComponents/__snapshots__/ThroughputInputAutoPilotV3Component.test.tsx.snap
src/Explorer/Controls/ThroughputInput/__snapshots__/ThroughputInput.test.tsx.snap
src/Explorer/Panes/PanelInfoErrorComponent.tsx
src/Explorer/Panes/Tables/AddTableEntityPanel.tsx
src/Explorer/Panes/Tables/__snapshots__/AddTableEntityPanel.test.tsx.snap
src/Explorer/Panes/__snapshots__/AddCollectionPanel.test.tsx.snap
src/Explorer/Tables/QueryBuilder/QueryBuilderViewModel.ts
src/Explorer/Tabs/QueryTablesTab.html

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1370?feature.someFeatureFlagYouMightNeed=true)

Defect1711833

---

src/Explorer/Panes/DeleteDatabaseConfirmationPanel.tsx

Gracefully handle database deletion errors.

Show delete database error

---

src/Common/Constants.ts
src/Explorer/DataSamples/ContainerSampleGenerator.test.ts
src/Explorer/DataSamples/ContainerSampleGenerator.ts
src/Explorer/Panes/AddCollectionPanel.tsx
src/Explorer/Panes/__snapshots__/AddCollectionPanel.test.tsx.snap
src/Platform/Hosted/extractFeatures.ts

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1377?feature.someFeatureFlagYouMightNeed=true)

Add hierachical partition key in add containers in SQL

---

src/Contracts/ViewModels.ts
src/Explorer/Tabs/Tabs.tsx
src/Utils/NetworkUtility.ts
src/hooks/useKnockoutExplorer.ts
src/hooks/useTabs.ts

Check if the client IP address is added to the firewall rules for SQL, Gremlin, and Tables accounts, and display warning message if it's not present
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1380?feature.someFeatureFlagYouMightNeed=true)

Improve network settings warning message

---

src/Explorer/Controls/ThroughputInput/ThroughputInput.tsx
src/Explorer/Controls/ThroughputInput/__snapshots__/ThroughputInput.test.tsx.snap

labels have been added for autoscale and manual radiobuttons in add container  dialog
aria label has been added to capacity calculator link

fix for defect 1703851&1703931

---

src/Explorer/Panes/AddCollectionPanel.tsx

remove feature flag and add preview text in the button

---

src/Explorer/Panes/AddCollectionPanel.tsx
src/Explorer/Panes/__snapshots__/AddCollectionPanel.test.tsx.snap

rework for defect-1704149

---

src/Explorer/Panes/__snapshots__/AddCollectionPanel.test.tsx.snap
src/Utils/NetworkUtility.ts
src/hooks/useKnockoutExplorer.ts

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1388?feature.someFeatureFlagYouMightNeed=true)

Remove networking warning message for sql, gremlin, and tables api

---

src/Explorer/Controls/ThroughputInput/ThroughputInput.test.tsx
src/Explorer/Controls/ThroughputInput/ThroughputInput.tsx
src/Explorer/Controls/ThroughputInput/__snapshots__/ThroughputInput.test.tsx.snap
src/Explorer/Panes/AddCollectionPanel.tsx
src/Explorer/Panes/__snapshots__/AddCollectionPanel.test.tsx.snap

autoscale and manual radiobuutton fixes

---

.github/workflows/ci.yml

Set overwrite to true for both blob uploads to storage.

Set overwrite to true for both blob uploads to storage.

---

.github/workflows/ci.yml

Updates user to use for nuget push.

Updates user to use for nuget push.

---

src/Explorer/Controls/NotebookGallery/InfoComponent/InfoComponent.tsx
src/Explorer/Controls/NotebookGallery/InfoComponent/__snapshots__/InfoComponent.test.tsx.snap
src/Explorer/Controls/ThroughputInput/ThroughputInput.test.tsx
src/Explorer/Controls/ThroughputInput/ThroughputInput.tsx
src/Explorer/Controls/ThroughputInput/__snapshots__/ThroughputInput.test.tsx.snap
src/Explorer/Panes/AddCollectionPanel.tsx
src/Explorer/Panes/__snapshots__/AddCollectionPanel.test.tsx.snap
src/Explorer/SplashScreen/SplashScreen.tsx

Defect2236159

---

src/Utils/AuthorizationUtils.ts

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1408?feature.someFeatureFlagYouMightNeed=true)

Change AAD endpoint from /common to /organizations.

---

src/Common/EnvironmentUtility.test.ts
src/Common/OfferUtility.test.ts
src/Common/UrlUtility.test.ts
src/Explorer/Menus/CommandBar/CommandBarComponentButtonFactory.tsx
src/Explorer/Notebook/NotebookComponent/InMemoryContentProviderUtils.test.ts
src/Explorer/Quickstart/Tutorials/MongoQuickstartTutorial.tsx
src/Explorer/Quickstart/Tutorials/SQLQuickstartTutorial.tsx
src/Main.tsx

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1407)

Add additional teaching bubbles in Quickstart

---

package-lock.json
src/Explorer/Tabs/MongoShellTab/MongoShellTabComponent.tsx
src/Platform/Hosted/extractFeatures.ts

Add feature flags to test Legacy Mongo Shell

---

src/Explorer/Tabs/MongoShellTab/MongoShellTabComponent.tsx
src/Explorer/Tabs/MongoShellTab/getMongoShellOrigin.test.ts
src/Explorer/Tabs/MongoShellTab/getMongoShellOrigin.ts
src/Explorer/Tabs/MongoShellTab/getMongoShellUrl.test.ts
src/Explorer/Tabs/MongoShellTab/getMongoShellUrl.ts

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1422?feature.someFeatureFlagYouMightNeed=true)

Fix CORS issue using Mongo Shell from new origin

---

src/Explorer/Menus/CommandBar/CommandBarComponentButtonFactory.test.ts
src/Explorer/Menus/CommandBar/CommandBarComponentButtonFactory.tsx

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1425?feature.someFeatureFlagYouMightNeed=true)

Remove Enable Azure Synapse link button for Tables API

---

src/Explorer/Menus/CommandBar/CommandBarComponentButtonFactory.test.ts
src/Explorer/Menus/CommandBar/CommandBarComponentButtonFactory.tsx

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1427?feature.someFeatureFlagYouMightNeed=true)

Remove Enable Azure synapse link for Cassandra

---

src/Explorer/Graph/NewVertexComponent/NewVertexComponent.test.tsx
src/Explorer/Graph/NewVertexComponent/NewVertexComponent.tsx

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1438?feature.someFeatureFlagYouMightNeed=true)
defect-https://msdata.visualstudio.com/CosmosDB/_workitems/edit/2280403/

role has been corrected to combobox for the dropdown

---

src/Explorer/Tabs/Tabs.tsx

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1434?feature.someFeatureFlagYouMightNeed=true)
defect-https://msdata.visualstudio.com/CosmosDB/_workitems/edit/2280174/

anchor link removed, since interactive elements cannot be nested

---

src/Explorer/Graph/GraphExplorerComponent/GraphExplorer.tsx
src/Explorer/Graph/GraphExplorerComponent/GremlinClient.ts

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1457?feature.someFeatureFlagYouMightNeed=true)
ICM https://portal.microsofticm.com/imp/v3/incidents/details/389245796/home

Fix gremlin timeout

---

src/Explorer/Controls/Settings/SettingsSubComponents/SubSettingsComponent.tsx
src/Explorer/Controls/Settings/SettingsSubComponents/__snapshots__/SubSettingsComponent.test.tsx.snap

ASK 2251011: Expose container type and hashkey version for all containers.  
Adds whether or not a container is Hierarchical to SQL API container settings page.
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1458?feature.someFeatureFlagYouMightNeed=true)

Hierarchical Partitioning - Expose container type and hashkey version for all containers.

---

src/Explorer/ContextMenuButtonFactory.tsx

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1471)

Text fix based on feedback

---

src/Explorer/Panes/DeleteDatabaseConfirmationPanel.tsx

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1495?feature.someFeatureFlagYouMightNeed=true)

Improve error message while deleting a collection

---

src/Explorer/Tabs/QueryTab/QueryTabComponent.tsx

Reset error state if query execution is successful

---

src/Explorer/Controls/Settings/SettingsSubComponents/ThroughputInputComponents/ThroughputInputAutoPilotV3Component.tsx

Fix for softAllowedMaximumThroughput issue when using sdk

---

src/Explorer/QueryCopilot/QueryCopilotTab.tsx
src/Explorer/Tabs/Tabs.tsx
src/hooks/useTabs.ts

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1494?feature.someFeatureFlagYouMightNeed=true)
- Adding spinner for react tabs

[Query Copilot] Adding loading spinner for Copilot tab

---

src/Explorer/Quickstart/QuickstartCarousel.tsx

aria label has been added to close button

---

src/Utils/NetworkUtility.ts

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1517?feature.someFeatureFlagYouMightNeed=true)

Do not show network connection message when securedbyperimeter

---

src/Contracts/ExplorerContracts.ts

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1520?feature.someFeatureFlagYouMightNeed=true)

Add new message type for NPS

---

src/Explorer/QueryCopilot/QueryCopilotTab.tsx

- Add learning bubble on copilot input text if users has not clicked on it for 30 seconds 
[AB#2486830](https://msdata.visualstudio.com/ba574a88-a171-48e0-8fcb-5fef6d23739c/_workitems/edit/2486830)
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1507?feature.someFeatureFlagYouMightNeed=true)

[Query Copilot] Add learning bubble to query copilot input if text

---

src/Explorer/QueryCopilot/QueryCopilotFeedbackModal.tsx
src/Main.tsx
src/Utils/UserUtils.ts
test/sql/resourceToken.spec.ts

- Pass user email to feedback api if user opts in 
[AB#2501550](https://msdata.visualstudio.com/ba574a88-a171-48e0-8fcb-5fef6d23739c/_workitems/edit/2501550)
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1516?feature.someFeatureFlagYouMightNeed=true)

[Query Copilot] Pass user email to query feedback 

---

src/Common/dataAccess/queryDocuments.ts
src/Explorer/QueryCopilot/QueryCopilotTab.tsx

Use sample data client to execute queries in the query copilot tab.
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1522?feature.enablecopilot=true)

Fix issue with executing queries in the query copilot tab

---

less/resourceTree.less
src/Explorer/Controls/Accordion/AccordionComponent.tsx
src/Explorer/Tree/ResourceTree.tsx
src/Explorer/Tree/SampleDataTree.tsx

- Update height stylings for resource tree items
- Make font size 12px for sample container
- Set expanded by default for sample container 
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1530?feature.someFeatureFlagYouMightNeed=true)
[AB#2528009](https://msdata.visualstudio.com/ba574a88-a171-48e0-8fcb-5fef6d23739c/_workitems/edit/2528009)
[AB#2525466](https://msdata.visualstudio.com/ba574a88-a171-48e0-8fcb-5fef6d23739c/_workitems/edit/2525466)
[AB#2528022](https://msdata.visualstudio.com/ba574a88-a171-48e0-8fcb-5fef6d23739c/_workitems/edit/2528022)

[Query Copilot] Update sample data resource tree item stylings

---

src/Explorer/QueryCopilot/QueryCopilotTab.tsx

- Check if response is ok, otherwise handle 500 error 
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1533?feature.someFeatureFlagYouMightNeed=true)
[AB#2530345](https://msdata.visualstudio.com/ba574a88-a171-48e0-8fcb-5fef6d23739c/_workitems/edit/2530345)

[Query Copilot] Handle response if it returns a 500 status

---

package-lock.json
package.json
src/Explorer/QueryCopilot/Modal/WelcomeModal.test.tsx
src/Explorer/QueryCopilot/Modal/__snapshots__/WelcomeModal.test.tsx.snap
src/setupTests.ts

- Adding unit tests for Query Copilot Welcome Modal 
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1535?feature.someFeatureFlagYouMightNeed=true)

[Query Copilot] Add unit tests for Welcome Modal

---

src/Explorer/QueryCopilot/QueryCopilotTab.tsx
src/Explorer/QueryCopilot/__snapshots__/QueryCopilotTab.test.tsx.snap

This pull request contains improvements in QueryCopilotTab, namely including scrillable window, distinct and improved history, hidden Sample Prompts and updated Dropdown prompts.
Related tasks:
[AB#2531040](https://msdata.visualstudio.com/ba574a88-a171-48e0-8fcb-5fef6d23739c/_workitems/edit/2531040)
[AB#2531769](https://msdata.visualstudio.com/ba574a88-a171-48e0-8fcb-5fef6d23739c/_workitems/edit/2531769)
[AB#2532138](https://msdata.visualstudio.com/ba574a88-a171-48e0-8fcb-5fef6d23739c/_workitems/edit/2532138)
[AB#2532756](https://msdata.visualstudio.com/ba574a88-a171-48e0-8fcb-5fef6d23739c/_workitems/edit/2532756)
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1536?feature.someFeatureFlagYouMightNeed=true)

[Query Copilot] Scrollable Copilot tab, improved history and minor fixes

---

src/Explorer/QueryCopilot/Modal/QueryCopilotFeedbackModal.test.tsx
src/Explorer/QueryCopilot/Modal/QueryCopilotFeedbackModal.tsx
src/Explorer/QueryCopilot/Modal/WelcomeModal.test.tsx
src/Explorer/QueryCopilot/Modal/__snapshots__/QueryCopilotFeedbackModal.test.tsx.snap
src/Explorer/QueryCopilot/Modal/__snapshots__/WelcomeModal.test.tsx.snap
src/Main.tsx

- Adding tests for the welcome modal
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1538?feature.someFeatureFlagYouMightNeed=true)
[AB#2501500](https://msdata.visualstudio.com/ba574a88-a171-48e0-8fcb-5fef6d23739c/_workitems/edit/2501500)

[Query Copilot] Adding tests for the welcome modal

---

src/Explorer/Tree/SampleDataTree.tsx

This pull request contains implementation that adds "New SQL Query" button when clicked on "Item" section in SampleContainer.
Related tasks:
[AB#2567880](https://msdata.visualstudio.com/ba574a88-a171-48e0-8fcb-5fef6d23739c/_workitems/edit/2567880)
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1552?feature.someFeatureFlagYouMightNeed=true)

[Query Copilot] New Query button added on Items section

---

src/Explorer/QueryCopilot/Modal/QueryCopilotFeedbackModal.tsx
src/Explorer/QueryCopilot/Modal/WelcomeModal.tsx
src/Explorer/QueryCopilot/Modal/__snapshots__/QueryCopilotFeedbackModal.test.tsx.snap
src/Explorer/QueryCopilot/Modal/__snapshots__/WelcomeModal.test.tsx.snap
src/Explorer/QueryCopilot/QueryCopilotTab.tsx
src/Explorer/QueryCopilot/__snapshots__/QueryCopilotTab.test.tsx.snap

This pull request contains updated links for query copilot "Link" elements.
Related tasks:
[AB#2571219](https://msdata.visualstudio.com/ba574a88-a171-48e0-8fcb-5fef6d23739c/_workitems/edit/2571219)
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1556?feature.someFeatureFlagYouMightNeed=true)

[Query Copilot] Updated Copilot links

---

src/Explorer/QueryCopilot/QueryCopilotTab.tsx
src/Explorer/QueryCopilot/__snapshots__/QueryCopilotTab.test.tsx.snap

- Allow on enter to run generate query
[AB#2573353](https://msdata.visualstudio.com/ba574a88-a171-48e0-8fcb-5fef6d23739c/_workitems/edit/2573353)
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1558?feature.someFeatureFlagYouMightNeed=true)

[Query Copilot] Generate query on enter

---

src/Explorer/ContextMenuButtonFactory.tsx
src/Explorer/Menus/CommandBar/CommandBarComponentButtonFactory.tsx
src/Explorer/QueryCopilot/QueryCopilotTab.tsx
src/Explorer/QueryCopilot/QueryCopilotUtilities.test.tsx
src/Explorer/QueryCopilot/QueryCopilotUtilities.ts
src/Explorer/SplashScreen/SplashScreen.tsx
src/Shared/Telemetry/TelemetryConstants.ts
src/hooks/useQueryCopilot.ts

- Add correlation id in query generation
- Add traces for opening query copilot
- Add traces for executing query 
[AB#2571080](https://msdata.visualstudio.com/ba574a88-a171-48e0-8fcb-5fef6d23739c/_workitems/edit/2571080)
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1555?feature.someFeatureFlagYouMightNeed=true)

[Query Copilot] Add telemetry for query copilot

---

src/Explorer/QueryCopilot/QueryCopilotTab.tsx

This pull request contains implementation related with the flickering while the tab is processing request for generating query.
Related tasks:
[AB#2586606](https://msdata.visualstudio.com/ba574a88-a171-48e0-8fcb-5fef6d23739c/_workitems/edit/2586606)
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1564?feature.someFeatureFlagYouMightNeed=true)

[Query Copilot] Disable Query Copilot Tab flickering

---

src/Explorer/Explorer.tsx
src/Explorer/Panes/AddCollectionPanel.tsx
src/Platform/Hosted/extractFeatures.ts
src/UserContext.ts

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1565?feature.someFeatureFlagYouMightNeed=true)

Add logic in DE to show NPS Survey

---

src/Platform/Hosted/extractFeatures.ts

Fix issue with feature flag

---

src/Explorer/Explorer.tsx

Fix sendMessage in DE

---

src/Explorer/QueryCopilot/Modal/QueryCopilotFeedbackModal.tsx
src/Explorer/QueryCopilot/Modal/WelcomeModal.tsx
src/Explorer/QueryCopilot/Modal/__snapshots__/QueryCopilotFeedbackModal.test.tsx.snap
src/Explorer/QueryCopilot/Modal/__snapshots__/WelcomeModal.test.tsx.snap

This pull request contains changed text in different components based on the received feedback.
Related task:
[AB#2608328](https://msdata.visualstudio.com/ba574a88-a171-48e0-8fcb-5fef6d23739c/_workitems/edit/2608328)

[Query Copilot] Revise Copilot UI texts

---

src/Common/EntityValue.tsx
src/Common/TableEntity.tsx

…nce they have no significance in selection of elements and they are repetetive which is not a good practice

Fix 1586730 : WCAG 4.1.1: Ensures every id attribute value used in ARIA and in labels is unique (input[aria-labelledby="TextFieldLabel339"])

---

src/Explorer/Controls/CollapsiblePanel/CollapsibleSectionComponent.tsx
src/Explorer/Controls/CollapsiblePanel/__snapshots__/CollapsibleSectionComponent.test.tsx.snap

Improper arialabel named aria-name has been removed

---

src/Explorer/Tabs/QueryTab/QueryTabComponent.tsx

This pull request contains fix for having a reliable flag that will compare if v2 copilot feature should be show or not.
Related tasks:
[AB#2631496](https://msdata.visualstudio.com/ba574a88-a171-48e0-8fcb-5fef6d23739c/_workitems/edit/2631496)
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1581?feature.someFeatureFlagYouMightNeed=true)

[Query Copilot] Fix failing comparison for CopilosSampleDB

---

src/Localization/en/Common.json

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1585?feature.someFeatureFlagYouMightNeed=true)

Fix spelling of Refresh for self-serve blades.

---

src/Explorer/Explorer.tsx
src/Explorer/Menus/CommandBar/CommandBarComponentAdapter.tsx
src/Explorer/Menus/CommandBar/CommandBarUtil.tsx
src/Explorer/Menus/CommandBar/ConnectionStatusComponent.tsx
src/Explorer/Panes/CopyNotebookPane/CopyNotebookPane.tsx
src/Explorer/QueryCopilot/QueryCopilotTab.tsx
src/Explorer/QueryCopilot/QueryCopilotUtilities.ts
src/Explorer/Tabs/QuickstartTab.tsx
src/Explorer/Tree/Collection.ts
src/Utils/GalleryUtils.ts

Fix allocateContainer: add container pool parameter

---

src/Explorer/Explorer.tsx

Send undefined poolId instead of "default" pool

---

src/Explorer/QueryCopilot/Shared/QueryCopilotClient.ts

This pull request contains fixed implementations for generateSQLQuery request where, in previous PRs feature flags were removed. This implementation now only reintroduces them.
Related tasks:
[AB#2647336](https://msdata.visualstudio.com/ba574a88-a171-48e0-8fcb-5fef6d23739c/_workitems/edit/2647336)
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1590?feature.someFeatureFlagYouMightNeed=true)

[Query Copilot] Reintroduce feature flags

---

src/Explorer/Panes/AddCollectionPanel.tsx
src/Platform/Hosted/extractFeatures.ts

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1592?feature.someFeatureFlagYouMightNeed=true)

Remove NPS feature flag

---

src/Explorer/QueryCopilot/QueryCopilotTab.tsx

- Hide teaching bubble if users has selected sample prompt, history suggestions or has selected the text field for input 
[AB#2654557](https://msdata.visualstudio.com/ba574a88-a171-48e0-8fcb-5fef6d23739c/_workitems/edit/2654557)
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1593?feature.someFeatureFlagYouMightNeed=true)

[Query Copilot] Fix teaching bubble display 

---

src/Explorer/QueryCopilot/QueryCopilotTab.tsx
src/Explorer/QueryCopilot/Shared/QueryCopilotClient.test.ts
src/Explorer/QueryCopilot/Shared/QueryCopilotClient.ts
src/Platform/Hosted/extractFeatures.ts

This pull request contains implementation that sets flag for phoenix gateway for copilot related features on if not value is specified.
Related tasks:
[AB#2651797](https://msdata.visualstudio.com/ba574a88-a171-48e0-8fcb-5fef6d23739c/_workitems/edit/2651797)

[Query Copilot] Phoenix Gateway flag true by default

---

src/Contracts/ExplorerContracts.ts

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1597)

Adding a contract to open vcore mongo networking blade

---

src/Contracts/ExplorerContracts.ts

Adding contract to open vcore mongo connection string blade

---

src/hooks/useKnockoutExplorer.ts

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1598?feature.someFeatureFlagYouMightNeed=true)

Support NPS for PostGres

---

src/Explorer/QueryCopilot/Shared/QueryCopilotClient.ts
src/Explorer/QueryCopilot/Shared/QueryCopilotInterfaces.ts
src/Explorer/QueryCopilot/V2/Bubbles/Explanation/ExplanationBubble.test.tsx
src/Explorer/QueryCopilot/V2/Bubbles/Explanation/ExplanationBubble.tsx
src/Explorer/QueryCopilot/V2/Bubbles/Explanation/__snapshots__/ExplanationBubble.test.tsx.snap
src/Explorer/QueryCopilot/V2/Bubbles/Output/Buttons/Copy/CopyButton.test.tsx
src/Explorer/QueryCopilot/V2/Bubbles/Output/Buttons/Copy/CopyButton.tsx
src/Explorer/QueryCopilot/V2/Bubbles/Output/Buttons/Feedback/FeedbackButtons.test.tsx
src/Explorer/QueryCopilot/V2/Bubbles/Output/Buttons/Feedback/FeedbackButtons.tsx
src/Explorer/QueryCopilot/V2/Bubbles/Output/Buttons/Insert/InsertButton.test.tsx
src/Explorer/QueryCopilot/V2/Bubbles/Output/Buttons/Insert/InsertButton.tsx
src/Explorer/QueryCopilot/V2/Bubbles/Output/Buttons/OutputBubbleButtons.test.tsx
src/Explorer/QueryCopilot/V2/Bubbles/Output/Buttons/OutputBubbleButtons.tsx
src/Explorer/QueryCopilot/V2/Bubbles/Output/Buttons/__snapshots__/OutputBubbleButtons.test.tsx.snap
src/Explorer/QueryCopilot/V2/Bubbles/Output/OutputBubble.test.tsx
src/Explorer/QueryCopilot/V2/Bubbles/Output/OutputBubble.tsx
src/Explorer/QueryCopilot/V2/Bubbles/Output/__snapshots__/OutputBubble.test.tsx.snap
src/Explorer/QueryCopilot/V2/Sidebar/QueryCopilotSidebar.tsx
src/hooks/useQueryCopilot.ts

This pull request contains implementation related to adjusting necessary parts of the code that will work correctly based on the outcome received from the backend services of query copilot. Outcome is integrated with previously implemented code that will show this outcomes.
Related tasks:
[AB#2654818](https://msdata.visualstudio.com/ba574a88-a171-48e0-8fcb-5fef6d23739c/_workitems/edit/2654818)
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1599?feature.someFeatureFlagYouMightNeed=true)

[Query Copilot V2] Wire and adjust Output bubble with backend communication

---

src/Explorer/QueryCopilot/QueryCopilotTab.tsx
src/Explorer/QueryCopilot/Shared/QueryCopilotClient.ts
src/Explorer/QueryCopilot/Shared/QueryCopilotResults.tsx
src/Explorer/QueryCopilot/__snapshots__/QueryCopilotTab.test.tsx.snap
src/Explorer/Tabs/QueryTab/QueryTabComponent.tsx
src/hooks/useQueryCopilot.ts

This pull request contains implementation related to execution and showing of query results with inside the Query Tabs of the Cosmos DB's.
Related tasks:
[AB#2670244](https://msdata.visualstudio.com/ba574a88-a171-48e0-8fcb-5fef6d23739c/_workitems/edit/2670244)
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1605?feature.someFeatureFlagYouMightNeed=true)

[Query Copilot V2] Adjusted execute Query logic

---

src/Platform/Hosted/extractFeatures.ts

- Change the default feature flag value
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1604?feature.someFeatureFlagYouMightNeed=true)

Change deafault schema feature flag

---

src/Explorer/Explorer.tsx

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1610?feature.someFeatureFlagYouMightNeed=true)

Add additional checks for NPS survey

---

web.config

Update CSP header in web.config to allow Data Explorer to be iframed inside fabric

---

web.config

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1613?feature.someFeatureFlagYouMightNeed=true)

Allow iframe within Fabric Extension iframe

---

web.config

Add Fabric edog origin to allowed ancestors

---

src/Explorer/QueryCopilot/Modal/WelcomeModal.tsx
src/Explorer/QueryCopilot/Modal/__snapshots__/WelcomeModal.test.tsx.snap
src/Explorer/QueryCopilot/QueryCopilotTab.tsx
src/Explorer/QueryCopilot/V2/Modal/WelcomeSidebarModal.tsx
src/Explorer/QueryCopilot/__snapshots__/QueryCopilotTab.test.tsx.snap

Fix query copilot help links

---

.vscode/settings.json
package.json

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1619)

Minor QOL changes

---

src/ConfigContext.ts
src/Utils/EndpointValidation.ts

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1623?feature.someFeatureFlagYouMightNeed=true)

Update graph endpoint

---

web.config

Add wildcard to allow any fabric test origin

---

src/Explorer/Panes/CassandraAddCollectionPane/CassandraAddCollectionPane.tsx

arialabel has been changed according to react attributes

---

src/Explorer/Controls/Dialog.tsx

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1543?feature.someFeatureFlagYouMightNeed=true)
https://msdata.visualstudio.com/CosmosDB/_workitems/edit/1731991/

Dialog box of azure synapse closes on pressing escape button

---

src/Explorer/QueryCopilot/Modal/WelcomeModal.tsx
src/Explorer/QueryCopilot/Modal/__snapshots__/WelcomeModal.test.tsx.snap
src/Explorer/QueryCopilot/V2/Modal/WelcomeSidebarModal.tsx

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1629?feature.someFeatureFlagYouMightNeed=true)

fix preview links

---

src/hooks/useTabs.ts

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1636?feature.someFeatureFlagYouMightNeed=true)

Don't show the home screen for Fabric

---

package-lock.json

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1639?feature.someFeatureFlagYouMightNeed=true)
Included in this change are also some minor updates of some other packages version and metadata.

Update package-lock.json to fix dependencies resolution for fluent ui v9

---

src/Explorer/QueryCopilot/Modal/WelcomeModal.tsx
src/Explorer/QueryCopilot/Modal/__snapshots__/WelcomeModal.test.tsx.snap

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1632?feature.someFeatureFlagYouMightNeed=true)

Fit content to modal

---

src/Explorer/QueryCopilot/QueryCopilotTab.tsx

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1633?feature.someFeatureFlagYouMightNeed=true)

Disable query saving for copilot private preview

---

src/Explorer/QueryCopilot/QueryCopilotTab.tsx
src/Explorer/QueryCopilot/__snapshots__/QueryCopilotTab.test.tsx.snap

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1634?feature.someFeatureFlagYouMightNeed=true)

Add word wrap for the query explanation

---

src/hooks/useQueryCopilot.ts

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1635?feature.someFeatureFlagYouMightNeed=true)

Reset the state to initial query every time

---

web.config

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1649?feature.someFeatureFlagYouMightNeed=true)

Add redirect for /aad to /?feature.enableAadDataPlane=true

---

src/Explorer/QueryCopilot/Modal/QueryCopilotFeedbackModal.test.tsx
src/Explorer/QueryCopilot/Modal/QueryCopilotFeedbackModal.tsx
src/Explorer/QueryCopilot/Modal/__snapshots__/QueryCopilotFeedbackModal.test.tsx.snap
src/Explorer/QueryCopilot/QueryCopilotPromptbar.tsx
src/Explorer/QueryCopilot/QueryCopilotTab.tsx
src/Explorer/QueryCopilot/__snapshots__/QueryCopilotTab.test.tsx.snap
src/hooks/useQueryCopilot.ts

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1657?feature.someFeatureFlagYouMightNeed=true)

P1, P2 bug fixes for private preview

---

.eslintrc.js
package-lock.json
package.json
src/Common/CosmosClient.test.ts
src/Common/CosmosClient.ts
src/Explorer/Tabs/DocumentsTab.ts
src/Explorer/Tabs/MongoDocumentsTab.ts
src/Explorer/Tree/ConflictId.ts
src/Utils/PriorityBasedExecutionUtils.ts
src/Utils/QueryUtils.test.ts
src/Utils/QueryUtils.ts

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1664)

Upgrade Cosmos SDK to 4.0.0

---

src/Explorer/Quickstart/VCoreMongoQuickstartGuide.tsx

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1669)

Updating vcore mongo quickstart text based on feedback

---

src/Common/dataAccess/readCollections.ts
src/Common/dataAccess/readDatabases.ts

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1679)

Clear console and properly handle error message when querying database or containers (for Fabric)

---

src/Contracts/AzureResourceGraph.ts
src/Contracts/DataModels.ts
src/HostedExplorer.tsx
src/Platform/Hosted/extractFeatures.ts
src/hooks/useDatabaseAccounts.tsx
src/hooks/useSubscriptions.tsx

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1677)

Fetch subs and accounts via MS graph

---

src/Explorer/Quickstart/VCoreMongoQuickstartCommands.ts
src/Explorer/Quickstart/VCoreMongoQuickstartGuide.tsx

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1678)

Minor changes to vcore mongo quickstart based on feedback

---

src/Explorer/QueryCopilot/Modal/WelcomeModal.tsx
src/Explorer/QueryCopilot/Modal/__snapshots__/WelcomeModal.test.tsx.snap
src/Explorer/QueryCopilot/QueryCopilotPromptbar.tsx
src/Explorer/QueryCopilot/Shared/QueryCopilotClient.test.ts
src/Explorer/QueryCopilot/Shared/QueryCopilotClient.ts

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1691?feature.someFeatureFlagYouMightNeed=true)

fix the phoenix endpoint

---

src/Explorer/QueryCopilot/Shared/QueryCopilotClient.ts

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1693?feature.someFeatureFlagYouMightNeed=true)

do not throw error when initial checking of copilot enablement

---

src/Explorer/Panes/PanelComponent.less
src/Explorer/Panes/Tables/AddTableEntityPanel.tsx

… table dialog which has been added through this commit
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1665?feature.someFeatureFlagYouMightNeed=true)

Bug 2748872: "Back" button is not keyboard accessible which is present under "Email" screen.

---

src/Explorer/Tabs/QueryTablesTab.html

…since it is not accepted format
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1653?feature.someFeatureFlagYouMightNeed=true)

Bug 2723424:Role attribute has an inappropriate value for the given element.

---

src/Common/TableEntity.tsx

…elete buttons
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1652?feature.someFeatureFlagYouMightNeed=true)

Bug 2724013 Screen reader announces incorrect role when focus lands on the "Edit" and "Delete" buttons.

---

src/Explorer/Panes/DeleteCollectionConfirmationPane/DeleteCollectionConfirmationPane.tsx

…out the alert everytime a change occursin the input
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1544?feature.someFeatureFlagYouMightNeed=true)

Alert is being updated for every change, hence the screenreader readsout the alert everytime a change occursin the input

---

src/Explorer/Panes/Tables/TableQuerySelectPanel/TableQuerySelectPanel.test.tsx
src/Explorer/Panes/Tables/TableQuerySelectPanel/TableQuerySelectPanel.tsx
src/Explorer/Panes/Tables/TableQuerySelectPanel/__snapshots__/TableQuerySelectPanel.test.tsx.snap

…supported by the HTML elements used
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1547?feature.someFeatureFlagYouMightNeed=true)
https://msdata.visualstudio.com/CosmosDB/_workitems/edit/1586735/

aria posinset has been removed, since it is not an attribute that is supported by the HTML elements used

---

src/Explorer/Tabs/QueryTablesTab.html

WCAG 1.3.1,WCAG 4.1.2: Ensures every form element has a label (textarea)

---

src/Explorer/Controls/TreeComponent/treeComponent.less

…n navigation
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1551?feature.someFeatureFlagYouMightNeed=true)

outline offset has been added for the focus indicator to be visible on navigation

---

src/Explorer/Explorer.tsx
src/Explorer/Panes/__snapshots__/AddCollectionPanel.test.tsx.snap
src/Explorer/QueryCopilot/Modal/WelcomeModal.tsx
src/Explorer/QueryCopilot/Modal/__snapshots__/WelcomeModal.test.tsx.snap
src/Explorer/QueryCopilot/Shared/QueryCopilotClient.ts

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1708?feature.someFeatureFlagYouMightNeed=true)

Remove copilot feature registration check

---

src/ConfigContext.ts
src/Utils/EndpointValidation.ts

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1715?feature.someFeatureFlagYouMightNeed=true)

Add support for Dogfood

---

src/Explorer/QueryCopilot/Popup/CopyPopup.tsx
src/Explorer/QueryCopilot/Popup/__snapshots__/CopyPopup.test.tsx.snap

role=""status" has been added for the floating popup "query copied successfully" for the screen reader to announce the content

---

src/Explorer/QueryCopilot/QueryCopilotPromptbar.tsx

Link color has been modified to get color contrast ratio of more than 4.5:1

---

src/Explorer/QueryCopilot/QueryCopilotPromptbar.tsx
src/Explorer/QueryCopilot/V2/Footer/__snapshots__/Footer.test.tsx.snap
src/hooks/useQueryCopilot.ts

…tate
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1703?feature.someFeatureFlagYouMightNeed=true)

Bug 2819239:Screen reader does not announce the loading information which appears on invoking the 'Send' button.

---

less/Common/Constants.less
less/documentDBFabric.less
src/Contracts/FabricMessagesContract.ts
src/Explorer/Menus/CommandBar/CommandBarComponentAdapter.tsx
src/Explorer/Menus/CommandBar/CommandBarUtil.tsx
src/hooks/useKnockoutExplorer.ts

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1720?feature.someFeatureFlagYouMightNeed=true)

Fabric toolbar style and support to show/hide it

---

src/Explorer/Explorer.tsx

Update logic for NPS survey for existing accounts > 90 days

---

src/Explorer/QueryCopilot/QueryCopilotPromptbar.tsx

Bug 2819335: [Screen reader - Cosmos DB Query Copilot - Feedback]: Screen reader does not announce the 'State' by the 'Like/Dislike' buttons.

---

src/Explorer/Tabs/QueryTab/QueryResultSection.tsx
src/Explorer/Tabs/QueryTab/QueryTabComponent.less

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1718?feature.someFeatureFlagYouMightNeed=true)

Bug 2819486: [Programmatic access - Cosmos DB Query Copilot - Query stats]: Aria-labelledby attribute is defined on span with no valid role attribute.

---

src/Explorer/Explorer.tsx
src/Explorer/QueryCopilot/QueryCopilotPromptbar.tsx

Add more logs for NPS

---

src/Explorer/Panes/Tables/AddTableEntityPanel.tsx
src/Explorer/Panes/Tables/EditTableEntityPanel.tsx

For the TableAPI, I added a null or whitespace check for the Primary and Row Keys that will also trim the values to prevent whitespace.
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1731?feature.someFeatureFlagYouMightNeed=true)

Added TableAPI whitespace check and trim values

---

src/Contracts/MessageTypes.ts

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1737?feature.someFeatureFlagYouMightNeed=true)
Adding a MessageType for the CESCVA feedback blade to test with FE implementation.

Added CESCVA MessageType for FE

---

src/Explorer/Explorer.tsx

Remove localStorage for NPS

---

src/Explorer/Tabs/QueryTab/QueryTabComponent.tsx

Limit RU threshold only to NoSQL

---

src/Explorer/Menus/CommandBar/CommandBarComponentButtonFactory.tsx
src/Explorer/Tabs/DocumentsTab.ts
src/Explorer/Tabs/QueryTab/QueryTabComponent.tsx
src/Platform/Fabric/FabricUtil.ts

This reverts commit f403b086adf2131c37ed2c349e2582e17ea8c47c.
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1751)

Revert "Hide buttons for Fabric or when no write access (#1742)"

---

src/Explorer/Explorer.tsx
src/Explorer/Menus/CommandBar/CommandBarComponentButtonFactory.tsx

Reverts Azure/cosmos-explorer#1736

Revert "Adding CESCVA feedback button"

---

src/Common/MongoProxyClient.ts

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1758?feature.someFeatureFlagYouMightNeed=true)

fix create mongo collection and delete mongo document switching

---

src/Explorer/Controls/TreeComponent/TreeComponent.tsx
src/Explorer/Controls/TreeComponent/__snapshots__/TreeComponent.test.tsx.snap
test/cassandra/container.spec.ts
test/graph/container.spec.ts
test/mongo/container.spec.ts
test/mongo/container32.spec.ts
test/sql/container.spec.ts
test/tables/container.spec.ts

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1478?feature.someFeatureFlagYouMightNeed=true)

Bug 1240907: Aria-label is not descriptive enough for 'More(...)' button present under 'SQL API' section.

---

src/Common/Constants.ts

Fix API endpoint for CassandraProxy query API

---

src/Common/dataAccess/dataTransfers.ts
src/Explorer/Controls/Settings/SettingsSubComponents/PartitionKeyComponent.tsx
src/Explorer/Controls/Settings/SettingsUtils.tsx
src/Explorer/Controls/Settings/__snapshots__/SettingsComponent.test.tsx.snap
src/Explorer/Panes/ChangePartitionKeyPane/ChangePartitionKeyPane.tsx
src/Explorer/QueryCopilot/QueryCopilotPromptbar.tsx

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1777?feature.someFeatureFlagYouMightNeed=true)
This change addresses a few bugs in partition key change and query copilot:
- Fix progress bar issues in data transfer job
- Surface detailed error in the notifications pane
- Add a informational message bar when creating new container
- Bring back query explanation for generated query and removed prompt in the query editor.
Manual testing in standalone explorer

Fix bugs on data transfer and bring back query explanation and remove query prompt from editor

---

src/Explorer/Tabs/Tabs.tsx
src/Explorer/Tabs/TabsBase.ts
src/Explorer/Tree/Collection.ts

Adding container IDs to tabs in order to better navigate tabs (viewing, closing, etc)
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1772?feature.someFeatureFlagYouMightNeed=true)

Add container ids to tabs

---

src/Explorer/Menus/CommandBar/CommandBarComponentButtonFactory.tsx

This feature is not supported on any other platform incl. Hosted.
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1775?feature.someFeatureFlagYouMightNeed=true)

Show the Feedback button in Portal only

---

src/Common/MongoProxyClient.ts
src/ConfigContext.ts
src/Explorer/Tables/TableDataClient.ts
src/Explorer/Tabs/Tabs.tsx

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1794)

Activate Mongo Proxy and Cassandra Proxy in Prod

---

src/Utils/EndpointUtils.ts

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1791?feature.someFeatureFlagYouMightNeed=true)
This change enables use of the new backend for the Settings API in Prod.

Enable new backend for Settings API in Prod.

---

jest.config.js
package-lock.json
package.json
src/Explorer/Panes/__snapshots__/AddCollectionPanel.test.tsx.snap

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1812?feature.someFeatureFlagYouMightNeed=true)
This change updates the following dependencies:
- d3
- webpack-dev-server
- typedoc

Update d3, webpack-dev-server, typedoc dependencies.

---

src/Utils/EndpointUtils.ts

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1820?feature.someFeatureFlagYouMightNeed=true)

Activate Token Controller in new Portal Backend

---

src/Explorer/Tabs/MongoShellTab/MongoShellTabComponent.tsx
src/Explorer/Tabs/MongoShellTab/getMongoShellUrl.ts

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1823?feature.someFeatureFlagYouMightNeed=true)

Open Legacy Mongo Shell with correct base URL in sovereign clouds

---

src/Common/MongoProxyClient.ts
src/Explorer/Tabs/MongoShellTab/getMongoShellUrl.test.ts

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1828)

Enable Legacy Mongo Shell in Fairfax

---

src/Contracts/ActionContracts.ts
src/Explorer/Controls/Settings/__snapshots__/SettingsComponent.test.tsx.snap
src/Explorer/Explorer.tsx
src/Explorer/Notebook/NotebookManager.tsx
src/Explorer/OpenActions/OpenActions.tsx
src/Explorer/Panes/CopyNotebookPane/CopyNotebookPane.tsx
src/Explorer/Panes/CopyNotebookPane/CopyNotebookPaneComponent.tsx
src/Explorer/Panes/GitHubReposPanel/__snapshots__/GitHubReposPanel.test.tsx.snap
src/Explorer/Panes/StringInputPane/__snapshots__/StringInputPane.test.tsx.snap
src/Explorer/QueryCopilot/__snapshots__/QueryCopilotTab.test.tsx.snap
src/Explorer/SplashScreen/SplashScreen.tsx
src/Explorer/Tabs/NotebookV2Tab.ts
src/Explorer/Tree/ResourceTree.tsx
src/Explorer/Tree/ResourceTreeAdapter.tsx
src/Utils/GalleryUtils.ts

[Preview](https://cosmos-explorer-preview.azurewebsites.net/pull/1830?feature.someFeatureFlagYouMightNeed=true)
Reverts Azure/cosmos-explorer#1816

Revert "First set of changes for Notebooks removal."

---

src/ConfigContext.ts

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1838)

Point Mongo requests to old backend

---

src/Explorer/Panes/AddCollectionPanel.tsx

Description:
This PR addresses accessibility concerns within the Azure CosmosDB Data Explorer by ensuring every ARIA input field has an accessible name. Specifically, the addition of the ariaLabel attribute enhances programmatic access for users navigating the Data Explorer interface.
Changes Made:
Added ariaLabel attribute to ARIA input fields within the Azure CosmosDB Data Explorer.
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1835?feature.someFeatureFlagYouMightNeed=true)

[Programmatic Access - Azure CosmosDB – Data Explorer]: Ensures every ARIA input field has an accessible name.

---

src/Explorer/Controls/Settings/SettingsSubComponents/ContainerVectorPolicyComponent.tsx
src/Explorer/Panes/AddCollectionPanel.tsx

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1844?feature.someFeatureFlagYouMightNeed=true)

allow serverless accounts to have vector search embeddings

---

src/Explorer/Controls/TreeComponent/__snapshots__/TreeNodeComponent.test.tsx.snap

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1863?feature.someFeatureFlagYouMightNeed=true)
I merged a few PRs and unfortunately they had some test snapshot conflicts that didn't get merged properly. As a result, Unit Tests are currently failing in master. This PR fixes the issue by updating the snapshot.

fix a broken test snapshot

---

src/Explorer/Explorer.tsx
src/Explorer/Panes/SettingsPane/SettingsPane.tsx

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1870?feature.someFeatureFlagYouMightNeed=true)

handle sampledb error handling to load the data explorer

---

src/ConfigContext.ts

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1886)

Revert to old Mongo Proxy

---

src/Contracts/AzureResourceGraph.ts
src/Explorer/Tabs/MongoShellTab/MongoShellTabComponent.tsx
src/hooks/useSubscriptions.tsx

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1902)

[PRE RBAC #1878] Adding CRI fixes to pre RBAC commit

---

src/Explorer/ContextMenuButtonFactory.tsx
src/Explorer/Menus/CommandBar/CommandBarComponentButtonFactory.tsx

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1913)

Add Cassandra Shell tab

---

src/Platform/Emulator/emulatorAccount.tsx

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1917?feature.someFeatureFlagYouMightNeed=true)

Add vector search capability for emulator

---

src/Platform/Emulator/emulatorAccount.tsx

Fix vector search capability name

---

src/Common/dataAccess/createCollection.ts
src/Platform/Emulator/emulatorAccount.tsx

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1918?feature.someFeatureFlagYouMightNeed=true)

Fix vector search capability name (#1918)

---

src/Common/MongoProxyClient.ts
src/ConfigContext.ts

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1934)

Activate Mongo Proxy in MPAC

---

src/Utils/QueryUtils.ts

revert extract partition key

---

src/Common/MongoProxyClient.ts
src/ConfigContext.ts
src/Utils/QueryUtils.test.ts

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1936)

Activate Mongo Proxy in Prod

---

src/Utils/QueryUtils.test.ts
src/Utils/QueryUtils.ts

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1947)

Reinstating partition key fix with added check for nested partitions

---

src/Common/Constants.ts
src/Common/CosmosClient.ts
src/Common/MongoProxyClient.ts
src/Platform/Hosted/Components/ConnectExplorer.tsx
src/Utils/EndpointUtils.ts
src/hooks/usePortalAccessToken.tsx

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1950)

Runtime Proxy API

---

src/Common/Constants.ts
src/Explorer/Notebook/useNotebook.ts
src/Utils/EndpointUtils.ts
src/Utils/NetworkUtility.test.ts
src/Utils/NetworkUtility.ts

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1952)

Show portal networking banner for new backend

---

src/ConfigContext.ts

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1956)

Fixing regex on allowedParentFrameOrigins to address possibility of XSS

---

src/Common/MongoProxyClient.ts
src/ConfigContext.ts
src/Explorer/Tables/TableDataClient.ts
src/Explorer/Tabs/Tabs.tsx

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1959)

Use old backend for Mongo and Cassandra accounts depending on their IP rules

---

src/Platform/Hosted/Helpers/ResourceTokenUtils.test.ts
src/Platform/Hosted/Helpers/ResourceTokenUtils.ts

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1962)

Removing trailing ; from resource token which is incompatible with v2 tokens

---

src/Explorer/Tabs/DocumentsTabV2/DocumentsTableComponent.tsx
src/Platform/Hosted/extractFeatures.ts

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1973)
Remove `enableDocumentsTableColumnSelection` feature flag.

Move table column selection in Documents tab out of feature flag to MPAC

---

src/Explorer/Tabs/DocumentsTabV2/DocumentsTabV2.tsx

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1976)

Bug fix: when deleting documents, only show throttling warning when throttling happened

---

src/Common/MongoProxyClient.ts
src/ConfigContext.ts

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1977)

Bulk Delete API fix

---

src/Explorer/Tabs/DocumentsTabV2/DocumentsTableComponent.tsx

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1980)

Makes the Documents Tab table column selection and sorting available to all users.

---

less/documentDBFabric.less

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/2005)
The new Fabric extension code already takes care of these paddings.

Update styles for Fabric

---

less/documentDBFabric.less

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/2008)
Merge [this commit](https://github.com/Azure/cosmos-explorer/commit/070b7a4ca708db41e79e05d5b2b1a2c91804595f) so that it can be deployed before the corresponding Fabric change.

Remove unnecessary padding for Fabric

---

.github/workflows/ci.yml

Attempting to fix Nuget Publishing tasks in CI by moving to latest version of nuget setup.

Update to Nuget setup action v2.

---

src/Explorer/Tabs/Tabs.tsx

Description: This PR improves accessibility in the Azure Cosmos DB Data Explorer by removing unwanted applied role attributes and adding appropriate aria-labels to relevant elements. These changes enhance screen reader support and ensure compliance with accessibility standard
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/2001?feature.someFeatureFlagYouMightNeed=true)

[Programmatic Access- Azure Cosmos DB- Data Explorer]: Ensures role attribute has an appropriate value for the element.

---

src/Contracts/MessageTypes.ts
src/Explorer/Explorer.tsx
src/hooks/useKnockoutExplorer.ts

[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/2027?feature.someFeatureFlagYouMightNeed=true)

Removed NPS Survey from DE since it has been moved to the Overview Blade

---

src/Explorer/Panes/SettingsPane/SettingsPane.tsx

Added some emulator checks in Settings pane fields
https://msdata.visualstudio.com/CosmosDB/_workitems/edit/3607486/
[Preview this branch](https://dataexplorer-preview.azurewebsites.net/pull/2041)

Added emulator checks in settings pane fields

---

src/Common/CosmosClient.ts
src/Common/MongoProxyClient.test.ts
src/Common/MongoProxyClient.ts
src/ConfigContext.ts
src/Contracts/ViewModels.ts
src/Explorer/Notebook/useNotebook.ts
src/Explorer/QueryCopilot/Shared/QueryCopilotClient.ts
src/Explorer/Tables/TableDataClient.ts
src/Explorer/Tabs/DocumentsTabV2/DocumentsTabV2.tsx
src/Explorer/Tabs/MongoShellTab/MongoShellTabComponent.tsx
src/Explorer/Tabs/MongoShellTab/getMongoShellUrl.test.ts
src/Explorer/Tabs/MongoShellTab/getMongoShellUrl.ts
src/Explorer/Tabs/Tabs.tsx
src/Platform/Hosted/Components/ConnectExplorer.tsx
src/Utils/EndpointUtils.ts
src/hooks/useKnockoutExplorer.ts
src/hooks/usePortalAccessToken.tsx
test/testExplorer/TestExplorer.ts

Removing use of legacy backend from DE in all environments
[Preview this branch](https://dataexplorer-preview.azurewebsites.net/pull/2043?feature.someFeatureFlagYouMightNeed=true)

Backend Migration - Remove Use of Legacy Backend from DE

---

src/Explorer/Controls/Settings/SettingsSubComponents/MaterializedViewComponent.tsx
src/Explorer/Controls/Settings/SettingsSubComponents/MaterializedViewTargetComponent.tsx
src/Explorer/Tree/treeNodeUtil.tsx

PRD:  https://microsoft.sharepoint.com/:w:/r/teams/DocumentDB/_layouts/15/Doc.aspx?sourcedoc=%7B34A4E4A2-89FB-435D-89C2-646E113CBF9E%7D&file=[CreationAndDisplayOfMVInPortal.docx](https://microsoft.sharepoint.com/:w:/r/teams/DocumentDB/_layouts/15/Doc.aspx?sourcedoc=%7B34A4E4A2-89FB-435D-89C2-646E113CBF9E%7D&file=CreationAndDisplayOfMVInPortal.docx&nav=eyJoIjoiMTQzMTE1ODQ3OCJ9&action=default&mobileredirect=true)&nav=eyJoIjoiMTQzMTE1ODQ3OCJ9&action=default&mobileredirect=true

Materialized View Target Container

---

src/Explorer/Controls/Settings/SettingsComponent.tsx
src/Explorer/Controls/Settings/SettingsSubComponents/MaterializedViewComponent.tsx
src/Explorer/Controls/Settings/SettingsSubComponents/MaterializedViewSourceComponent.tsx
src/Explorer/Controls/Settings/SettingsSubComponents/MaterializedViewTargetComponent.tsx
src/Explorer/Controls/Settings/SettingsUtils.tsx
src/Explorer/Tree/treeNodeUtil.tsx

https://microsoft.sharepoint.com/:w:/r/teams/DocumentDB/_layouts/15/Doc.aspx?sourcedoc=%7B34A4E4A2-89FB-435D-89C2-646E113CBF9E%7D&file=[CreationAndDisplayOfMVInPortal.docx](https://microsoft.sharepoint.com/:w:/r/teams/DocumentDB/_layouts/15/Doc.aspx?sourcedoc=%7B34A4E4A2-89FB-435D-89C2-646E113CBF9E%7D&file=CreationAndDisplayOfMVInPortal.docx&nav=eyJoIjoiNjQzMTMwODgxIn0%3D&action=default&mobileredirect=true)&nav=eyJoIjoiNjQzMTMwODgxIn0%3D&action=default&mobileredirect=true

 all views associated with a container

---

src/Explorer/Controls/Settings/SettingsSubComponents/MaterializedViewComponent.test.tsx
src/Explorer/Controls/Settings/SettingsSubComponents/MaterializedViewSourceComponent.test.tsx
src/Explorer/Controls/Settings/SettingsSubComponents/MaterializedViewTargetComponent.test.tsx
src/Explorer/Controls/Settings/TestUtils.tsx

Test Files: Materialized View Tab

---

src/Explorer/Controls/Settings/SettingsSubComponents/MaterializedViewComponent.tsx

UI fixes - source container

---

src/Explorer/Tabs/TerminalTab.tsx

https://msdata.visualstudio.com/CosmosDB/_workitems/edit/3777887/?view=edit

Fixed Screenshot in Vcore Mongo Quickstart Terminal Blade

---

src/Utils/AuthorizationUtils.test.ts

[Preview this branch](https://dataexplorer-preview.azurewebsites.net/pull/2084)
This is for reference in case it gets flagged by security scanning. CodeQL doesn't seem to detect any issue either because it doesn't detect the JWT token or because it properly checks it validity.

Add comments for expired token used in test

---

src/Explorer/Tabs/DocumentsTabV2/DocumentsTabV2.tsx
src/Utils/QueryUtils.test.ts
src/Utils/QueryUtils.ts

Reverts Azure/cosmos-explorer#2085

Revert "fix partition key missing not being able to load the document"

---

src/Explorer/Tree/ResourceTreeAdapter.tsx
src/Explorer/Tree/__snapshots__/treeNodeUtil.test.ts.snap
src/Explorer/Tree/treeNodeUtil.tsx

Removed "Schema (Preview)" blade.
Without Change:
After this Change:

Mongo RU Schema Analyzer Deprecation

---

test/mongo/document.spec.ts
test/sql/document.spec.ts

Added document test skips

---

less/quickstart.less
src/quickstart.html

Emulator fixed outdated sample apps with new tutorials for
- dotnet
- java
- nodeJS

Emulator Quickstart Tutorials

---

src/Explorer/SplashScreen/SplashScreen.tsx

https://msdata.visualstudio.com/CosmosDB/_workitems/edit/4148408

Updated the Migrate data link

---

.github/workflows/ci.yml
playwright.config.ts
src/Explorer/Controls/InputDataList/InputDataList.tsx
src/Explorer/Tabs/DocumentsTabV2/DocumentsTabV2.tsx
src/Explorer/Tabs/DocumentsTabV2/__snapshots__/DocumentsTabV2.test.tsx.snap
test/CORSBypass.ts
test/fx.ts
test/mongo/document.spec.ts
test/sql/document.spec.ts
test/sql/testCases.ts
test/testData.ts

[Preview this branch](https://dataexplorer-preview.azurewebsites.net/pull/2126?feature.someFeatureFlagYouMightNeed=true)

Added more test cases and fix system partition key load issue

---

less/documentDBFabric.less

fix: Add overflow property and set minimum heights for flex and sidebar containers

---

src/Explorer/Tabs/CloudShellTab/CloudShellTerminalCore.tsx
src/Explorer/Tabs/CloudShellTab/ShellTypes/AbstractShellHandler.tsx
src/Explorer/Tabs/CloudShellTab/ShellTypes/MongoShellHandler.test.tsx
src/Explorer/Tabs/CloudShellTab/ShellTypes/MongoShellHandler.tsx
src/Explorer/Tabs/CloudShellTab/ShellTypes/VCoreMongoShellHandler.test.tsx
src/Explorer/Tabs/CloudShellTab/ShellTypes/VCoreMongoShellHandler.tsx
src/Explorer/Tabs/CloudShellTab/Utils/AttachAddOn.tsx

[Preview this branch](https://dataexplorer-preview.azurewebsites.net/pull/2128?feature.enableCloudShell=true)
This PR contains following changes:
1. Remove extra telemetry call after user consent.
2. Fix on session timeout logic.
3.  Add command to remove other files and packages once mongo package is downloaded. (_CELA requirement, not to keep any extra mongo file which might be under SSPL License_)

Cloudshell: Few Enhancement

---

src/Explorer/Panes/SettingsPane/SettingsPane.tsx
src/Explorer/Panes/SettingsPane/__snapshots__/SettingsPane.test.tsx.snap

[Preview this branch](https://dataexplorer-preview.azurewebsites.net/pull/2125?feature.someFeatureFlagYouMightNeed=true)
[ADO](https://msdata.visualstudio.com/CosmosDB/_workitems/edit/4120587)

fix: Add collapsible feature to Accordion in SettingsPane

---

src/Explorer/Controls/Settings/SettingsComponent.test.tsx
src/Explorer/Controls/Settings/SettingsComponent.tsx
src/Explorer/Controls/Settings/SettingsSubComponents/ThroughputInputComponents/ThroughputBucketsComponent.test.tsx
src/Explorer/Controls/Settings/SettingsSubComponents/ThroughputInputComponents/ThroughputBucketsComponent.tsx
src/Explorer/Explorer.tsx
src/UserContext.ts
src/Utils/FeatureRegistrationUtils.ts

[Preview this branch](https://dataexplorer-preview.azurewebsites.net/pull/2140?feature.someFeatureFlagYouMightNeed=true)
Added AFEC check for throughput bucketing in UserContext

Added AFEC check in userContext

---

src/Explorer/Controls/Settings/SettingsComponent.test.tsx
src/Explorer/Controls/Settings/SettingsComponent.tsx
src/Explorer/Controls/Settings/SettingsSubComponents/ThroughputInputComponents/ThroughputBucketsComponent.test.tsx
src/Explorer/Controls/Settings/SettingsSubComponents/ThroughputInputComponents/ThroughputBucketsComponent.tsx
src/Explorer/Explorer.tsx
src/UserContext.ts
src/Utils/FeatureRegistrationUtils.ts

Throughput bucketing build release

---

src/Explorer/Panes/AddGlobalSecondaryIndexPanel/AddGlobalSecondaryIndexPanel.tsx
src/Explorer/Panes/AddGlobalSecondaryIndexPanel/Components/ThroughputComponent.tsx

[Preview this branch](https://dataexplorer-preview.azurewebsites.net/pull/2138)
Cherry picking GSI bug fix from master

Default New Global Secondary Index Panel to be sharded (#2138)

---

less/documentDB.less
src/Common/dataAccess/deleteDocument.ts
src/Explorer/Tabs/DocumentsTabV2/DocumentsTabV2.tsx

[Preview this branch](https://dataexplorer-preview.azurewebsites.net/pull/2139)
[ADO](https://msdata.visualstudio.com/CosmosDB/_workitems/edit/4123670)

fix: Implement abort functionality for bulk document deletion

---

src/Explorer/Controls/Settings/SettingsComponent.tsx

[Preview this branch](https://dataexplorer-preview.azurewebsites.net/pull/2164?feature.someFeatureFlagYouMightNeed=true)

Added throughput buckets in the scale update

---

package-lock.json
package.json
preview/package-lock.json
src/Common/IteratorUtilities.ts
src/Common/QueryError.ts
src/Common/dataAccess/__snapshots__/queryDocuments.test.ts.snap
src/Common/dataAccess/queryDocuments.ts
src/Common/dataAccess/queryDocumentsPage.ts
src/Contracts/ViewModels.ts
src/Explorer/Graph/GraphExplorerComponent/GraphExplorer.tsx
src/Explorer/Menus/NotificationConsole/ConsoleData.tsx
src/Explorer/Menus/NotificationConsole/NotificationConsoleComponent.tsx
src/Explorer/Menus/NotificationConsole/__snapshots__/NotificationConsoleComponent.test.tsx.snap
src/Explorer/Panes/SettingsPane/SettingsPane.tsx
src/Explorer/Panes/SettingsPane/__snapshots__/SettingsPane.test.tsx.snap
src/Explorer/Tabs/QueryTab/QueryTabComponent.tsx
src/Explorer/Tabs/Tabs.tsx
src/Explorer/Tabs/TabsBase.ts
src/Shared/StorageUtility.ts
src/Utils/NotificationConsoleUtils.ts
src/Utils/QueryUtils.ts
webpack.config.js

[Preview this branch](https://dataexplorer-preview.azurewebsites.net/pull/2137)
Upgrade Cosmos SDK to v4.3
Changes include:
- Enhanced Query Control Feature (more [here](https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/performance-tips-query-sdk?tabs=v3&pivots=programming-language-nodejs#enhanced-query-control))
- Since RU threshold feature is dropped in the SDK update, Data Explorer now has its own logic that tracks the RU charge after each page of a query. If the cumulative charge exceeds the threshold, a warning is shown to the user.

Upgrade Cosmos SDK to v4.3

---

src/Explorer/Controls/ThroughputInput/ThroughputInput.tsx
src/Explorer/Panes/AddCollectionPanel/AddCollectionPanel.tsx

[Preview this branch](https://dataexplorer-preview.azurewebsites.net/pull/2166?feature.someFeatureFlagYouMightNeed=true)

feat: Integrate Fabric Native support for throughput management

---

src/hooks/useTabs.ts

[Preview this branch](https://dataexplorer-preview.azurewebsites.net/pull/2156?feature.someFeatureFlagYouMightNeed=true)
[ADO](https://msdata.visualstudio.com/CosmosDB/_workitems/edit/4226002)
Fixes #2104

fix: Activate the last opened React tab after closing active tab

---

src/Explorer/Panes/AddCollectionPanel/AddCollectionPanel.tsx
src/Explorer/Panes/AddCollectionPanel/__snapshots__/AddCollectionPanel.test.tsx.snap

- Show Partition Keys block for fabric
- Adjust layout and visibility of separators in AddCollectionPanel
[Preview this branch](https://dataexplorer-preview.azurewebsites.net/pull/2174?feature.someFeatureFlagYouMightNeed=true)

fix: Partition Keys block for fabric

---

package-lock.json
package.json
src/setupTests.ts

[Preview this branch](https://dataexplorer-preview.azurewebsites.net/pull/2187)

Upgrade Cosmos SDK to v4.4.0

---

src/ConfigContext.ts
src/Explorer/Controls/Settings/SettingsComponent.tsx
src/Explorer/Explorer.tsx
src/Explorer/Menus/CommandBar/CommandBarComponentButtonFactory.tsx
src/Explorer/Panes/AddCollectionPanel/AddCollectionPanel.tsx
src/Explorer/Panes/AddCollectionPanel/AddCollectionPanelUtility.tsx
src/Utils/PlatformFeatureUtils.ts
src/hooks/useKnockoutExplorer.ts
utils/local-proxy/index.js

Added platform feature utility

---

src/Explorer/SplashScreen/FabricHome.tsx

Fixes: [ADO](https://msdata.visualstudio.com/CosmosDB/_workitems/edit/4498135)
- Add tabIndex to button
- Add aria attributes to icons and headings
[Preview this branch](https://dataexplorer-preview.azurewebsites.net/pull/2208?feature.someFeatureFlagYouMightNeed=true)

chore: Enhance accessibility
