Azure/cosmos-explorer

src/Explorer/Controls/Header/GalleryHeaderComponent.tsx, src/Explorer/Controls/NotebookViewer/NotebookViewerComponent.tsx, src/GalleryViewer/galleryViewer.html, src/NotebookViewer/NotebookViewer.tsx, src/NotebookViewer/notebookViewer.html, src/Utils/GalleryUtils.test.ts, src/Utils/GalleryUtils.ts
- `hideInputs` hides input cells when rendering notebook
- Use fav icons for `galleryViewer` and `notebookViewer`
- Use notebook title as document title in `notebookViewer`
=> Add hideInputs query param in notebookViewer and other minor updates

less/documentDB.less, src/explorer.html
Currently if I open settings tab, it will only take up half of the screen. This is caused by the last commit of my previous PR: https://github.com/Azure/cosmos-explorer/pull/66.
I'm reverting part of the commit that's causing this bug to unblock the deployment to MPAC.
=> Fix styling issues with tabs manager

src/Explorer/Controls/NotebookGallery/GalleryViewerComponent.tsx
Repro steps for bug:
1. Open official samples in gallery (in DE)
2. Click "Download" button on one of the notebook cards
3. Complete the download and switch back to gallery tab
Expected behavior:
Gallery tab opens with the card list and updated download count on the notebook card
Current behavior:
Gallery tab opens with empty card list
This bug is happening because when download is complete we open a new tab which puts the Gallery tab in background and thus when trying to render the gallery tab to update download count we get `visibleRect` as zero in `getPageSpecification` callback. This leads to us calculating wrong page size. Since we're anyway caching `columnCount` and `rowCount` this change just uses the cached value if the new value results in zero (which should ideally never …
=> Fix gallery card list disappear bug

src/Explorer/Controls/DialogReactComponent/DialogComponent.tsx, src/Explorer/Controls/Header/GalleryHeaderComponent.tsx, src/Explorer/Controls/NotebookGallery/Cards/GalleryCardComponent.test.tsx, src/Explorer/Controls/NotebookGallery/Cards/GalleryCardComponent.tsx, src/Explorer/Controls/NotebookGallery/Cards/__snapshots__/GalleryCardComponent.test.tsx.snap, src/Explorer/Controls/NotebookGallery/GalleryAndNotebookViewerComponent.tsx, src/Explorer/Controls/NotebookGallery/GalleryAndNotebookViewerComponentAdapter.tsx, src/Explorer/Controls/NotebookGallery/GalleryViewerComponent.test.tsx, src/Explorer/Controls/NotebookGallery/GalleryViewerComponent.tsx, src/Explorer/Controls/NotebookGallery/__snapshots__/GalleryViewerComponent.test.tsx.snap, src/Explorer/Controls/NotebookViewer/NotebookMetadataComponent.tsx, src/Explorer/Controls/NotebookViewer/NotebookViewerComponent.tsx, src/Explorer/Controls/NotebookViewer/__snapshots__/NotebookMetadataComponent.test.tsx.snap, src/Explorer/Explorer.ts, src/Explorer/Tabs/GalleryTab.html, src/Explorer/Tabs/GalleryTab.tsx, src/GalleryViewer/GalleryViewer.tsx, src/GalleryViewer/galleryViewer.html, src/Utils/GalleryUtils.test.ts, src/Utils/GalleryUtils.ts, webpack.config.js
- Change gallery endpoint from `/galleryViewer.html` to `/gallery`
- Update card styling to remove buttons in standalone mode
- Refactor to show `GalleryViewComponent` and `NotebookViewerComponent` in a single page for standalone gallery by creating a new `GalleryAndNotebookViewerComponent ` (to match the behavior of gallery tab in DE)
- Accessibility fixes for gallery cards
- Add a text banner to standalone gallery
=> Updates to standalone gallery

.eslintignore, .eslintrc.js, src/Common/MongoProxyClient.ts
Explicit `any` types is currently a warning, but this turns it into an error. We should avoid using any. Here are some good primers:
https://itnext.io/avoiding-any-in-typescript-advanced-types-and-their-usage-691b02ac345a
https://43081j.com/2019/02/typescript-avoid-using-any
In many cases where `any` is required,  `unknown` is a better type. If `any` is truly needed, we can add an eslint line exception with a comment justifying the exception.
=> Make explicit any a linting error

webpack.config.js
In order to use `https://cosmos.azure.com/gallery` as endpoint for Notebooks Gallery we used `/gallery/index.html` as the path. However this breaks all relative http paths originating from that page (like images, config.json, and other resource files). Using `/gallery.html` instead fixes this issue. If needed we'll need to investigate how we can get `/gallery` path in the future without breaking other things.
=> Use /gallery.html instead of /gallery/index.html as Notebooks Gallery endpoint

src/Explorer/Panes/PublishNotebookPaneAdapter.tsx, src/Explorer/Panes/PublishNotebookPaneComponent.less, src/Explorer/Panes/PublishNotebookPaneComponent.test.tsx, src/Explorer/Panes/PublishNotebookPaneComponent.tsx, src/Explorer/Panes/__snapshots__/PublishNotebookPaneComponent.test.tsx.snap
- Dropdown gives an option for URL or image upload
- Preview shows how the card will be displayed in the gallery, updated in real time including preview of the cover image
- base64 converted image stored in metadata document
- Max limit is 1.5MiB for the image (As max document size for cosmos db is 2 MB)
- If an image with size > 1.5Mib is selected, failure message is shown and state is reset
Future work includes providing an option for 
- Adding the first visualization in the notebook
- Adding screenshot of the notebook in the desired aspect ratio
=> Added support for custom image upload during publish to Gallery

src/Common/Constants.ts, src/Contracts/DataModels.ts, src/Platform/Hosted/ArmResourceUtils.ts, src/Platform/Hosted/Main.ts
Cosmos DB readers cannot use the same API that is used by contributors to fetch Cosmos DB keys, so this change falls back to this other API to fetch read only keys for readers.
=> Support cosmos readers in Cosmos Explorer

src/Common/MessageHandler.ts, src/Explorer/Explorer.ts
- Fixes #122. Changes `sendMessage` to only work in portal context
- Disables notebooks API call for master key authenticated accounts
=> Fix refresh resources button and remove portal specific notebooks call

src/Explorer/Tabs/TabsManager.test.ts
Currently the "closes tab" test case is sometimes flaky. The test case closes one of the two opened tabs and checks if there's still one opened tab left. However, sometimes there's no opened tab left.
This is could be caused by the two tabs having the same tabId so that when it tries to close one tab by passing its tabId, both tabs are closed. This is possible since we assign tabId based on the time that the tab is created.
The fix is to hardcode the tabId of each tab to make sure they are different.
=> Fix tabs manager test

src/Utils/arm/generatedClients/2020-04-01/types.ts, utils/armClientGenerator/generator.ts
On master, many `resource` and `options` properties do not have the correct type and were output to `undefined`. This adds proper handling for more types. Now there are only 2 unhandled types and they fall back to `unknown`
=> Fix Generated ARM types

.eslintignore, src/Common/ErrorParserUtility.ts, src/Utils/PricingUtils.test.ts, src/Utils/PricingUtils.ts
1) Updated mongo collection create pane to display a better error when a shard key is ill formed.
2) Updated an error message to use double quotes since no string interpolation is used. I thought it was included in a previous PR but I guess the change didn't get staged.
=> Updating error message on mongo collection create

src/Common/Constants.ts, src/Common/DataAccessUtilityBase.ts, src/Platform/Hosted/Helpers/ConnectionStringParser.ts
This fixes the renew token/session pane in data explorer so it accommodates the new cassandra connection string format.
=> Fix connection string renew token pane

src/Common/Constants.ts, src/Explorer/Controls/FeaturePanel/FeaturePanelComponent.tsx, src/Explorer/Controls/FeaturePanel/__snapshots__/FeaturePanelComponent.test.tsx.snap, src/Explorer/Controls/NotebookGallery/Cards/GalleryCardComponent.test.tsx, src/Explorer/Controls/NotebookViewer/NotebookMetadataComponent.test.tsx, src/Explorer/Controls/NotebookViewer/NotebookViewerComponent.tsx, src/Explorer/Explorer.ts, src/Explorer/Notebook/NotebookManager.ts, src/Explorer/Panes/PublishNotebookPaneAdapter.tsx, src/Explorer/Panes/PublishNotebookPaneComponent.tsx, src/Explorer/Panes/__snapshots__/PublishNotebookPaneComponent.test.tsx.snap, src/Juno/JunoClient.test.ts, src/Juno/JunoClient.ts, src/NotebookViewer/NotebookViewer.tsx, src/Utils/GalleryUtils.test.ts
- This PR has the data explorer changes corresponding to https://msdata.visualstudio.com/CosmosDB/_git/CosmosDB-portal/pullrequest/405712
- newCellId is a new metadata element in galleryItem, containing the id of the link injected by JUNO
- that cell needs to be stripped out before being rendered by the the notebook viewer component 
- added isLinkInjectionEnabled feature flag to hide the feature
=> Added support for notebook viewer link injection

src/Explorer/Tabs/SettingsTab.ts
`content` is an optional property of `offer`, so `offer.content.offerAutopilotSettings` could throw an error if the offer doesn't have a `content` property.
The fix is to add null check when reading `offerAutopiloSettings`.
=> Add null check when reading offerAutopilotSettings

src/Common/dataAccess/deleteCollection.test.ts, src/Common/dataAccess/deleteCollection.ts, src/Common/dataAccess/deleteDatabase.test.ts, src/Common/dataAccess/deleteDatabase.ts, src/DefaultAccountExperienceType.ts, src/Explorer/Explorer.ts, src/Shared/DefaultExperienceUtility.ts, src/UserContext.ts
Currently deleteDatabase and deleteCollection always use the SQL URI for deleting database and collection. It should determine the correct URI to use based on the default experience.
=> Fix deleteDatabase and deleteCollection with ARM

src/Explorer/Panes/CopyNotebookPane.tsx, src/Explorer/Panes/CopyNotebookPaneComponent.tsx, src/Explorer/Panes/GenericRightPaneComponent.tsx, src/Explorer/Panes/PublishNotebookPaneAdapter.tsx, src/Explorer/Panes/UploadItemsPaneAdapter.tsx, src/Explorer/Panes/UploadItemsPaneComponent.tsx
GenericRightPaneComponent now accepts a ReactComponent as its content instead of a JSX.Element passed via props.content.
Also updated UploadItemsPaneAdapter, CopyNotebookPaneAdapter, and PublishNotebookPaneAdapter to reflect the changes in GenericRightPaneComponent.
=> Refactor GenericRightPaneComponent to accept a ReactComponent as its content

src/Explorer/Graph/GraphExplorerComponent/GraphExplorer.test.tsx, src/Explorer/Graph/GraphExplorerComponent/GraphExplorer.tsx
Rather than being sent as a gremlin query, the `g.V()` query is intercepted by GraphExplorer and processed as a sql query: this allows paging and the code path involves processing the response and issuing more (gremlin) queries to display the node's neighbors.
This change fixes a bug that incorrectly errors when processing the `g.V()` results and encountering numeric partition key value.
=> Fix handling numeric partition keys

src/Explorer/Panes/AddDatabasePane.ts, src/Shared/AddDatabaseUtility.ts, src/Utils/arm/generatedClients/2020-04-01/cassandraResources.ts, src/Utils/arm/generatedClients/2020-04-01/databaseAccounts.ts, src/Utils/arm/generatedClients/2020-04-01/gremlinResources.ts, src/Utils/arm/generatedClients/2020-04-01/mongoDBResources.ts, src/Utils/arm/generatedClients/2020-04-01/sqlResources.ts, src/Utils/arm/generatedClients/2020-04-01/tableResources.ts, src/Utils/arm/generatedClients/2020-04-01/types.ts, utils/armClientGenerator/generator.ts
Cassandra create is a pretty low risk first move to create. It was already done via ARM, but this moves it to the new auto generated ARM functions.
- Fixes a double stringify bug in the ARM request body code
- Adds handling of required and optional body parameters to generator clients.
=> Create Cassandra Keyspace via ARM

src/Explorer/Graph/GraphExplorerComponent/GraphExplorer.test.tsx, src/Explorer/Graph/GraphExplorerComponent/GraphExplorer.tsx
Boolean partition key values are actually valid.
This change prevents the visualization code to reject boolean partition key values.
=> Allow boolean partition key in graph visualization

src/Explorer/Panes/GenericRightPaneComponent.tsx, src/Explorer/Panes/PublishNotebookPaneAdapter.tsx, src/Explorer/Panes/PublishNotebookPaneComponent.tsx, src/Explorer/Panes/UploadItemsPaneAdapter.tsx, src/Explorer/Tabs/NotebookV2Tab.ts, src/Explorer/Tree/ResourceTreeAdapter.tsx
- Fix bug where "Submit" button is hidden by default for `GenericRightPaneComponent`
- Only show "Copy to ..." options when github is logged in
- Fix issue where updating notebook name wasn't updating the live preview in `PublishNotebookPaneComponent`
=> Show submit button by default in GenericRightPaneComponent & other fixes

src/Common/dataAccess/readCollections.ts, src/Common/dataAccess/readDatabases.ts
After we moved readDatabases and readCollections to RP, we found that for Mongo API, the resources that the calls return are missing the `ExtendedResourceProperties` such as `_rid`, `_self`, etc, which are used in several places in data explorer. This causes a bunch of issues for customers using Mongo API so we are switching back to using SDK to read databases and collections for Mongo.
=> Switch back to using SDK to read databases and collections for Mongo API

src/Common/dataAccess/deleteDatabase.ts, src/Common/dataAccess/readCollections.ts
`deleteDatabase`: RP does not support any operation on the database level for table API so we have to switch back to using SDK.
`readCollections`: I moved this call back to SDK but it actually works using RP as well. Therefore, moving the table call back to RP.
=> Switch back to SDK for deleteDatabase and use RP for readCollections for table API

src/Explorer/Explorer.ts
The auto-generated ARM clients use `configContext.ARM_ENDPOINT` but we were not properly setting it based on the iframe message
=> Update Config context ARM endpoint

src/Common/dataAccess/readCollections.ts
The settings tab is not showing the correct indexing policy and ttl setting because we recently moved to using RP to read tables and RP does not expose these properties for table API. We need to switch back to using SDK in `readCollections` again.
=> Fix settings tab for table API

src/Common/Constants.ts, src/Common/dataAccess/deleteCollection.ts, src/Common/dataAccess/deleteDatabase.ts, src/Common/dataAccess/readCollections.ts, src/Common/dataAccess/readDatabases.ts, src/Explorer/Explorer.ts, src/UserContext.ts
For cassandra keyspaces with shared throughput, the "Scale" tab doesn't appear in the resource tree because the keyspaces that we get from RP do not have the `_self` property which is used to find the corresponding database offer. Without the offer, the resource tree is unable to determine whether the throughput is shared or not.
We have to revert readCollections back to using SDK for Cassandra. In addition, I added a feature flag `enablesdkoperations` to allow us to easily switch back to using SDK calls when we find issues with RP in the future.
=> Fix settings tab issue for cassandra and add feature flag

src/Common/DataAccessUtilityBase.ts, src/Common/DocumentClientUtilityBase.ts, src/Common/dataAccess/createDatabase.ts, src/Contracts/DataModels.ts, src/Explorer/Panes/AddDatabasePane.ts, src/Utils/arm/request.ts
- Refactored and moved all code paths for creating database in different APIs into createDatabase.ts.
- Before creating a database with RP, we need to check whether there already exists a database with the same id by using the getDatabase call. This is because RP bundles the create call with the update call which means if we try to create a database that already exists, RP will update the existing database instead of creating a new one.
- If there's no existing database with the same id, then RP returns 404 for the get call, so we need to add a try catch block to intercept the error and check if the error code is `"NotFound"`
=> Move createDatabase to RP

src/ConfigContext.ts
ConfigContext defines all kinds of URLs and what not, I'm not sure about the security implications of allowing all this stuff to be modifiable by just anyone.
=> Allow 'platform' only to be overridden

src/Explorer/Notebook/NotebookComponent/NotebookComponentBootstrapper.tsx, src/Explorer/Notebook/NotebookComponent/epics.test.ts, src/Explorer/Notebook/NotebookComponent/epics.ts
Code completion is not working unless a kernel is running, so we automatically start the kernel by calling `restartKernel` (which doesn't require any kernel parameter).
=> Start kernel when opening notebook tab

cypress/package.json
The emulator e2e test is failing with the following error:
> Can't run because you've entered an invalid browser name.
> 
> Browser: 'chrome' was not found on your system or is not supported by Cypress.
> 
> Cypress supports the following browsers:
> - chrome
> - chromium
> - edge
> - electron
> - firefox (Cypress support in beta)
> 
> You can also use a custom browser: https://on.cypress.io/customize-browsers
> 
> Available browsers found on your system are:
> - firefox
> - edge
> - electron
This fix will change the browser from chrome to edge for the emulator e2e test temporarily while we investigate why chrome is missing from our system.
=> Use edge instead of chrome for emulator e2e test

src/Explorer/Tree/ResourceTreeAdapter.test.ts, src/Explorer/Tree/ResourceTreeAdapter.tsx
Opening the graph tab was highlighting the incorrect resource tree node (the Collection node instead of its "Graph" subnode).
I added some unit tests to protect this logic, but the selection mechanism should be redesigned, eventually.
=> Fix resource tree node selection bug

src/Shared/appInsights.ts
When fetch tracking is enabled in appInsights it adds `request-id` in Request headers which is not allowed by Nginx used by the NotebooksService app pod. This leads to failed API calls when launching a terminal.
=> Fix broken terminals

src/Explorer/Notebook/NotebookContentClient.ts
Today, if we have non notebook file (csv, xlsx) in the container and we try to download the file, it fails. That is because, the filetype is always defined as notebook in the call to content provider's get method. Fixing it to use the right type in this change. This change fixes the csv issue. With XLSX, there is more investigation needed since it complains about encoding. Will checkin this fix for csv to unblock the customer.
=> Notebooks: Ability to download file from notebooks container

src/Explorer/Panes/DeleteDatabaseConfirmationPane.ts, src/Utils/arm/request.ts
ARM will sometimes return errors wrapped in a top level "error" field. This PR adds handling for that case.
=> Improve ARM error parsing and display

src/Explorer/Explorer.ts, src/Explorer/Notebook/NotebookContentClient.ts, src/Utils/BlobUtils.ts
- Fix `NotebookContentClient.readFileContent` to return content string for `text`, `json`, and `base64` files
- Fix how we're constructing `Blob` from a `string`
Verified that the following scenarios now work:
- Downloading `.csv`, `.xlsx`, `.txt`, `.ipynb` files from container works
- `Copy To...` works for `.csv`, `.txt`, `.ipynb` files from container to github
TODO
- `Copy To...` doesn't work for `.xlsx` from container to github correctly. It copies the file but it is corrupted.
=> Fix file downloads from notebooks container

src/Explorer/Tabs/QueryTablesTab.html
Added alert role for screen readers. We may want to hold off on this change until we can display a friendly error message.
=> Added alert role to query tables tab error

src/Common/MessageHandler.test.ts, src/Common/MessageHandler.ts, src/Shared/Telemetry/TelemetryConstants.ts, src/Terminal/index.ts
- Add telemetry for `OpenTerminal`
- Add support for iframes within Data Explorer to also send telemetry messages to Portal window (for kusto logs)
This change broke fullscreen DE because the `getDataExplorerWindow` function got stuck in a busy while loop and had to be reverted. It happened because in Javascript if a window does not have a parent, its parent property is a reference to itself. Updated the method to work in that case as well. That behavior can't be tested locally so I added unit tests to test all possible theoretical scenarios.
=> Add telemetry for OpenTerminal

src/Explorer/Controls/ThroughputInput/ThroughputInputComponentAutoscaleV3.html
The ariaLabel parameter is used for another text field in this component and only one text field is shown at a time. Hard coding aria label to match the hard coded label for this text field.
=> Fixed aria label for autopilot throughput

src/Explorer/Tabs/QueryTab.html, src/Explorer/Tabs/QueryTab.less
* Add `<caption>` tag.
* Remove unnecessary column (used for layout)
* Add `scope="col"` in header for screen reader to mention header when reading cell value
=> Fix a11y bugs in query stats table

src/Explorer/Controls/DynamicList/DynamicListComponent.ts
A11Y Bug 835065
After pressing enter key on the remove item control, then the visual focus indicator should move to the edit field. 
Also did the same when adding a key as it is annoying to tab until I get to the newly added input to enter my path.
=> Fix focus when adding and removing a unique key

src/Explorer/Panes/Tables/AddTableEntityPane.ts, src/Explorer/Panes/Tables/TableAddEntityPane.html
This PR focuses the first interactive element in the add row pane. The current focus attempts to focus the first entity value, however it doesn't seem to ever actually focus the element. In the accessibility report, I found it a bit confusing that it expected to select the first interactive element in the header, but went with what was written rather than my intuition, and can adjust if that's wrong.
https://msdata.visualstudio.com/CosmosDB/_queries/query/b7017577-e55f-4ce9-a968-0f12c1b1ccaf (requires access)
=> [Accessibility] Focuses header control element on Add Row click in Cassandra

src/ConfigContext.ts, src/Utils/MessageValidation.test.ts, src/Utils/MessageValidation.ts
Allow injection of valid origins via config.json file. Will enable us to deploy to new targets.
=> Allow remote config to set valid origins

src/Explorer/Panes/AddCollectionPane.html, src/Explorer/Panes/AddCollectionPane.ts
The "New Container" pane contains info bubbles next to some inputs: there's an (i) display that can be hovered over or focused to show/hide the bubble text.
The info bubble text is made visible/not visible by CSS using `:hover` and `:focus` pseudo-classes.
One info bubble text contains a hyper-link. Using the mouse and hovering over the (i) will show the text which will stay visible when moving the mouse to the link, because the link is a child of a `:hover`'ed text.
This is not the case with keyboard navigation (tab key to move focus). First the text will appear, because (i) is focused. When hitting Tab again, the text will disappear and focus will move to the next element in the form, instead of the hyperlink (which is now hidden), because of the css rule that only shows the text when …
=> Fix inaccessible link by keyboard nav in info bubble

less/documentDB.less
Currently if we apply text spacing, the tooltip of the info icon goes outside of the boundary of the add collection panel and becomes partially invisible:
In order to show the complete tooltip, we can either add a horizontal scroll bar or remove the `width` and `min-width` setting of the tooltip. However, the latter fix will also make the width of the tooltip box too narrow when text spacing is off so I think the best fix is to simply add a horizontal scroll bar by changing the horizontal overflow from `hidden` to `auto`.
=> [Accessibility] Add horizontal scroll bar if tooltip box goes outside of panel boundary

less/documentDB.less
After zooming to 200%, some content on the right side of data explorer becomes hidden and there's no horizontal scroll bar to make it visible. This PR adds a scroll bar to allow users to access the hidden content.
=> Fix some content becomes hidden after zooming to 200%

src/Common/Constants.ts, src/Common/MessageHandler.test.ts, src/Common/MessageHandler.ts, src/Explorer/Controls/Notebook/NotebookTerminalComponent.tsx, src/Explorer/Panes/DeleteCollectionConfirmationPane.test.ts, src/Explorer/Panes/DeleteCollectionConfirmationPane.ts, src/Explorer/Panes/DeleteDatabaseConfirmationPane.test.ts, src/Explorer/Panes/DeleteDatabaseConfirmationPane.ts, src/Explorer/Tabs/MongoShellTab.ts, src/Shared/Telemetry/TelemetryProcessor.ts, src/Terminal/index.ts, src/Utils/WindowUtils.test.ts, src/Utils/WindowUtils.ts
In TelemetryProcessor's traceSuccess there are 2 optional parameters with the first one being unknown type. This lead to some incorrect usage of TelemetryProcessor functions.
- Remove unknown parameter type from TelemetryProcessor functions to catch incorrect usage at compile time
- Update TelemetryProcessor.getData to work for iframes
This fixes the issue where OpenTerminal log doesn't contain "success" actionModifier
=> Fix incorrect usage of TelemetryProcessor

src/Explorer/Tree/Database.ts, src/Explorer/Tree/ResourceTreeAdapter.tsx, test/container.spec.ts
Currently the resource tree would re-render a total of 5 times when a database node is expanded. 
The first two re-renders are triggered when:
1. A node is selected (expanding a database node also selects it).
2. The collections of a database have finished loading.
The second re-render is expected. The resource tree must re-render after the collections have been loaded. The first one is also necessary because when a node is selected, we not only need to highlight the selected node, but we also need to remove the hightlighting from the previous selected node.
The third re-render is also triggered by loading the collections. This is because we have a duplicate subscription to `database.collections`. The `cleanupDatabasesKoSubs` function is supposed to remove any duplicate subscriptions but …
=> Fix resource tree refresh issue

src/Common/dataAccess/readDatabaseOffer.ts
Since RP doesn't have an API for reading database throughput for Tables API, we should switch to using SDK. Note that it should still work fine going through the RP code path, just cleaner and safer to use SDK for Tables.
=> Use SDK for reading database offer for Tables API

src/Common/dataAccess/readDatabaseOffer.ts, src/Common/dataAccess/readOffers.ts, src/Contracts/DataModels.ts, src/Explorer/Panes/AddCollectionPane.ts, src/Explorer/Panes/AddDatabasePane.ts, src/Explorer/Tree/Database.ts
By default, the `AddCollectionPane` and `AddDatabasePane` set shared throughput to true. This causes the create database call to fail for serverless accounts because shared throughput is not supported.
The fix is to set shared throughput to false by default if the database account is serverless.
Similarly, the read database offer call would fail if the account is serverless so we shouldn't make the call if it's serverless.
=> Fix create database for serverless accounts

src/Common/Constants.ts, src/Common/EnvironmentUtility.ts, src/Common/MongoProxyClient.test.ts, src/Common/MongoProxyClient.ts, src/Explorer/Tables/TableDataClient.ts, src/Explorer/Tabs/MongoShellTab.ts
The portal passes down the extension endpoint in the iframe message but in some cases, we were relying on older code to pick the endpoint from constants. This code was not aware of webpack variable injection and did not work on localhost. This PR unifies all extension endpoint references to pull from the value passed down via the portal.
=> Cleanup extension endpoint loading

src/Common/MessageHandler.ts, src/Utils/WindowUtils.ts
Heatmap is hosted in an iframe directly by portal window. This causes `getDataExplorerWindow` to jump to portal window directly and throwing exception because of different origin. The fix here is to catch the exception and fallback to current window if no data explorer window is found.
Verified that heatmap no longer throws above exception locally.
=> Do not fail when trying to find DE window with cross origin

src/Explorer/Tables/TableDataClient.ts
Cassandra endpoints are broken since the in their original backend object they had trailing slashes while all other types did not. This keeps all endpoints consistent in not having a trailing slash and instead adds it when the `apiEndpoint` const is declared as the other endpoints do (like mongo)
See: #224
=> Fix Cassandra Endpoint URLs by adding trailing slash in construction

src/Common/dataAccess/createDatabase.ts, src/Common/dataAccess/deleteDatabase.ts, src/Explorer/ContextMenuButtonFactory.ts, src/Explorer/Tree/ResourceTreeAdapter.tsx
Removes delete database option from resource tree menu for Tables accounts. Also throws for create/delete in underlying API calls
=> Remove option to delete/create root table database

src/ConfigContext.ts, src/Utils/MessageValidation.test.ts, src/Utils/MessageValidation.ts
My original change to the new set of Regex's did not account for the bare production domains. So `ms.portal.azure.com` worked but not `portal.azure.com`
=> Fix Parent Origin Regex

src/ConfigContext.ts, src/Utils/arm/request.ts
Allows overriding the ARM API version via query param: https://cosmos.azure.com/explorer.html?armAPIVersion=2020-03-01
=> Allow setting of ARM API version via query param

src/Explorer/Tabs/SettingsTab.ts
The Settings tab is broken for serverless account because we do not have null checks for `collection.quotaInfo()`. Due to my recent change that lazy loads the collection offer, we no longer read quota info if the account is serverless, thus `collection.quotaInfo()` returns undefined. There are several places in SettingsTab where we call `this.collection.quotaInfo().numPartitions` which would throw an error.
The fix is to either add a null check or add a special case for serverless account.
=> Add checks for serverless account

.github/workflows/automerge.yml
A limitation of Github actions is that [a workflow cannot trigger another workflow if using the built in github token](https://github.com/pascalgn/automerge-action#limitations). I have set up a PAT on my account that should allow us to workaround this.
=> Use Github PAT for automerge

src/Explorer/Menus/NotificationConsole/NotificationConsoleComponent.tsx, src/Explorer/Menus/NotificationConsole/__snapshots__/NotificationConsoleComponent.test.tsx.snap
story description:
Repro-Steps:
Open URL: https://ms.portal.azure.com/
Login via valid credentials
Navigate to "Azure Cosmos DB" from left pane and select it.
Navigate to any of the Azure Cosmos DB which is already created and select it.
Navigate to "Data Explorer" from the left and select it.
Navigate through all the controls under Data Explorer blade.
Navigate with the Narrator and reach console image at the button of the page.
Expected Result:
On the data explorer page, alt should be properly defined for the console image i.e alt=console. So, that the Screen Reader user does able gets the proper information of the image.
=> [Azure][Screen Reader-CosmosDB – Data Explorer] Alt is not correctly defined for the console image on the data explorer page

src/Terminal/index.ts
Recent upgrade to jupyterlab broke opening Mongo Shell and Cassandra Shell because now we need to explicitly pass the correct content-type header.
=> Add correct content-type header to terminals calls

src/Explorer/Explorer.ts
Using `await` inside a `forEach` loop does not work as expected. It actually just throws away all the promises instead of waiting for the promise to finish before moving onto the next one.
The correct way to do this is to use `map` instead of `forEach` and use `Promise.all` to wait for all promises to finish. This allows the database offers to be loaded in parallel.
=> Fix database offers not loaded when add collection pane is opened

src/Explorer/Notebook/NotebookClientV2.ts, src/Explorer/Notebook/NotebookComponent/NotebookComponentBootstrapper.tsx, src/Explorer/Notebook/NotebookComponent/epics.test.ts, src/Explorer/Notebook/NotebookComponent/epics.ts, src/Explorer/Notebook/NotebookComponent/store.test.ts, src/Explorer/Notebook/NotebookComponent/store.ts, src/Explorer/Notebook/notebookClientV2.test.ts
This fixes two regressions:
* Kernel selection broken: the command bar button does not allow to select kernels
The customMiddleware that updates the kernelspecs list in the command was not plugged in with the latest store refactor.
* Python kernel is always auto-started, even for c# notebooks for example
This is now using the proper nteract core epic (`launchKernelWhenNotebookSetEpic`) to autostart the kernel for non-readonly notebooks.
For read-only notebooks we explicitly do not include this `launchKernelWhenNotebookSetEpic` epic in order to disable auto-start (ie leave as kernel lazy-start) rather than relying on an `undefined` kernelref as currently done. This makes it more robust.
=> Fix notebook kernel selection and auto-kernel-start

src/Explorer/Notebook/NotebookRenderer/base.css
The [switch to monaco editor](https://github.com/Azure/cosmos-explorer/pull/239) has introduced this issue.
When running Data Explorer outside of portal, I often see an extra horizontal scrollbar in the cell input. This seems to be caused by the monaco editor widget not properly recalculating its width wrt to the container (nteract cell input): it must be off by a pixel or so, as shown by the scrollbar draggable element covering the entire width of the bar itself. No content is occluded.
This change removes the scrollbar in both directions as they don't seem useful: 
- in the y axis, the cell height expands with the content
- in the x axis, the words wraps. Images a scaled to fit.
The change is also in line with the default settings in nteract (which we override).
=> Fix horizontal scrollbar in notebook cell input issue

less/documentDB.less
Allow horizontal scrollbar when zooming in, but not vertical.
=> Fix double-scrollbar bug

src/Explorer/Controls/Settings/SettingsComponent.tsx, src/Explorer/Tabs/SettingsTab.ts, src/Explorer/Tabs/SettingsTabV2.tsx, src/Explorer/Tabs/TabsBase.ts, src/Shared/Telemetry/TelemetryConstants.ts
- Modified tab activate and close logging to contain tabId
- Overrode this tabId in SettingsV2 to make the tabId contain "SettingsV2"
- Changed type of telemetry action for updatecollection and update offer success and failure to "UpdateSettingsV2" in SettingsComponent
- Added new Action types "DiscardSettings" and "DiscardSettingsV2" for telemetry actions fired when discard button is clicked on setttings v2 and settings v2 respectively
=> Added telelmetry for settings v2 and v1

src/Common/dataAccess/readDatabaseOffer.ts, src/Common/dataAccess/updateOffer.ts, src/Explorer/Tree/Database.ts
RP does not supporting reading or updating database level throughput for Tables API so we have to switch back to using SDK calls for these operations.
=> Use SDK calls to read and update shared throughput for Tables API

src/Common/dataAccess/readDatabases.ts
Since I've cleaned up all the places that use `_rid` and `_self` of a database in my previous commit (https://github.com/Azure/cosmos-explorer/commit/d525afa14272ea3c7c90df2c20949aba2f145daa), we are safe to use RP to read databases for all APIs except Tables.
For Tables API, since RP doesn't support any database level operations, I have to hardcode the read database response. The only property we need in the Tables database is the id which is the string that we display in the resource tree.
=> Use RP to read databases for all API

src/Common/dataAccess/createStoredProcedure.ts, src/Common/dataAccess/createTrigger.ts, src/Common/dataAccess/createUserDefinedFunction.ts, src/Common/dataAccess/deleteStoredProcedure.ts, src/Common/dataAccess/deleteTrigger.ts, src/Common/dataAccess/deleteUserDefinedFunction.ts, src/Common/dataAccess/readStoredProcedures.ts, src/Common/dataAccess/readTriggers.ts, src/Common/dataAccess/readUserDefinedFunctions.ts, src/Common/dataAccess/updateStoredProcedure.ts, src/Common/dataAccess/updateTrigger.ts, src/Common/dataAccess/updateUserDefinedFunction.ts
RP doesn't support stored procedure, trigger, and UDF operations for Gremlin API so we have to use SDK for now.
=> Use SDK calls for stored procedure, trigger, and UDF operations for Gemlin API

src/Juno/JunoClient.test.ts, src/Juno/JunoClient.ts
We need to record `subscriptionId` when publishing a notebook, also we want to restrict notebooks to only from a particular `subscriptionId` when accessing `My published work` tab. This change passes the `subscriptionId` as part of the URL when publishing or accessing published notebooks.
=> Pass subscriptionId when publishing/accessing published notebooks

src/Explorer/Notebook/NotebookRenderer/NotebookRenderer.less
In Notebook code complete dropdown, moving and up/down active item does not update background color.
This is because the item background color has a `.main` class which is accidentally one of the `.main` rules in Data Explorer less file which should be more specific.
Rather than modifying our `.main {}` rule, which could break something, the easiest is to clear the background with a specific rule.
=> Fix notebook code complete selected dropdown item background color

src/Explorer/Controls/Settings/SettingsSubComponents/ScaleComponent.tsx, src/Explorer/Controls/Settings/SettingsSubComponents/ThroughputInputComponents/ThroughputInputAutoPilotV3Component.tsx, src/Explorer/Controls/Settings/SettingsUtils.test.tsx, src/Explorer/Controls/Settings/SettingsUtils.tsx, src/Explorer/Controls/ThroughputInput/ThroughputInputComponentAutoscaleV3.html, src/Explorer/Tabs/SettingsTab.ts
- removed the `isFixed` check in both new and old settings tab so that the options to switch between manual and autoscale shows up for fixed collections
- updated the message below the text box to inform the users that the max RU for fixed collections is 10000
- updated validation rule so that the max RU cannot exceed 10000 for fixed collections for both autoscale and manual
=> Allow users to switch between manual and autoscale for fixed collections

src/Explorer/Tabs/TabsBase.ts
Can't tell from current telemetry the name of the tab that was opened/closed
=> Add Tab Name to Telemetry

src/Explorer/Panes/AddDatabasePane.ts, src/Utils/arm/request.ts
1. Create database issue:
- Databases created via create database panel always have auto pilot selected, even if manual throughput is selected.
- This is because the panel sets the auto pilot throughput value even if manual throughput is selected. When we send the create database request, we check for autoscale throughput setting first, so we always end up creating a database with auto pilot enabled.
- The fix is to only set the `autoPilotMaxThroughput` of the `CreateDatabaseParams` if autos pilot is selected in the panel.
2. Delete database issue:
- The `Location` header of the delete request returns `204` instead of `200` when the operation completes.
- The fix is to add an additional check for `204` status code when polling for operation status.
=> Fix create and delete database

src/Explorer/SplashScreen/SplashScreenComponent.less
Repro Steps:
1. Open URL: https://ms.portal.azure.com/
2. Login via valid credentials
3. Navigate to "Azure Cosmos DB" from left pane and select it.
4. Navigate to any of the Azure Cosmos DB which is already created and select it.
5. Navigate to "Data Explorer" from the left and select it.
6. Navigate through all the controls under Data Explorer blade.
7. Open CCA tool and check luminosity contrast ratio of borderline control i.e Start with sample button.
8. Verify, if the luminosity ratio of the borderline control is greater than 3:1 or less than 3:1.
Actual Result:
Luminosity contrast ratio of the borderline control is less than 3:1 i.e 1.3:1.
Expected result:
Luminosity contrast ratio of the borderline control should be 3:1 or greater than 3:1.
Current solution make color #949494 to …
=> [526416][Visual Requirement-Data Explorer (iframe)]On the Data Explorer page, luminosity contrast ratio of the borderline button is less than 3.:1.

src/Common/dataAccess/getCollectionDataUsageSize.ts
`getCollectionDataUsageSize` uses the Azure Monitor RP call which doesn't work for non-AAD users. Currently the collection data usage size is only used for the MinRU survey that we display in the settings tab. Discussed with @southpolesteve: we will hide the survey for non-AAD users for now.
=> Only call getCollectionDataUsageSize for AAD users

src/Contracts/ViewModels.ts, src/Explorer/Tabs/TabsManager.html, src/Explorer/Tree/Collection.ts
Clicking the settings button allows users to create duplicate settings tabs. This PR fixes that and changes the SettingsV2 enum since another enum has the same value.
=> Fix duplicate settings tabs

canvas/README.md, canvas/index.js, canvas/package.json, package-lock.json, package.json
This adds a mock module for `canvas`. Nteract has a ignored require and undeclared dependency on this module. `cavnas` is a server side node module and is not used in browser side code for nteract.
Installing it locally (`npm install canvas`) will resolve the problem, but it is a native module so it is flaky depending on the system, node version, processor arch, etc. This module provides a simpler, more robust solution.
Remove this workaround if [this bug](https://github.com/nteract/any-vega/issues/2) gets resolved
=> Remove dependency on canvas

src/Explorer/Controls/Settings/SettingsComponent.tsx, src/Explorer/Controls/Settings/SettingsSubComponents/ThroughputInputComponents/ThroughputInputAutoPilotV3Component.tsx, src/Explorer/Controls/Settings/SettingsUtils.tsx
Issue 1: The storage capacity of a cassandra table shows as "fixed" in the settings tab.
- This is because the `partitionKey` property of a cassandra table is stored inside `resource.schema` property instead of the top-level `resource` object. When we try to determine if a collection is fixed in settings component, we first check if the `partitionKey` property exists. If not, we treat it as a fixed collection. As a result, this check would return true for any cassandra table.
- The fix is to check if the account is Mongo first before checking for partition keys since a fixed collection is only possible when using Mongo API.
Issue 2: When user types a number that exceeds the maximum throughput allowed in the manual throughput field, the number is automatically changed to the max.
- This …
=> Fix two settings tab issues

less/tree.less
Constrain left pane container to height: 100% so that scrollbar show up when content wants to overflow.
The `main` classname seems too generic, but I left it alone (so I don't break anything), since this part will eventually be ported to React.
=> Fix missing scrollbar in left pane when too many collections/notebooks

src/Explorer/Controls/Settings/SettingsComponent.test.tsx, src/Explorer/Controls/Settings/SettingsComponent.tsx
Right now "foo" becomes "foo" and "/foo" becomes "//foo". The slash check condition needs to be reversed.
=> Fix Conflict Resolution path setting

less/hostedexplorer.less, src/Explorer/Panes/AddCollectionPane.html, src/hostedExplorer.html
A11y fixes - Add a skip link and remove duplicate ids 
- Add a skip link to allow people who navigate sequentially through content more direct access to the primary content of the Data Explorer
- Rename id of partition key field in Add Collection Pane to ensure no elements contain duplicate attributes.
=> A11y fixes - Add a skip link and remove duplicate ids 

src/Explorer/Tabs/QueryTab.html, src/Explorer/Tabs/QueryTab.ts
Cosmos does not support non-correlated subqueries https://docs.microsoft.com/en-us/azure/cosmos-db/sql-query-subquery But unfortunately there is no way for a user to know this as the query still executes and returns results. Query team is working on supporting this, but as a stop gap we can use a simple regex to try and direct users to the sub query docs.
=> Warn on SubQuery

src/Explorer/Panes/AddCollectionPane.ts
This PR fixes an issue where the Mongo default indexing checkbox is incorrectly ignored and only depends on a user's flight.
=> fix issue where Mongo indexing checkbox stops adding wildcard index

src/Explorer/Tables/TableDataClient.ts
The query for deleting a Cassandra table row is not constructed properly. Need to add a pair of brackets to fix the order of concatenating the query string.
=> Properly construct the query to delete Cassandra row

src/Explorer/Panes/AddCollectionPane.ts
This is a fix to check that a customer is using Mongo 3.6 before adding an index everything policy.
=> check that customer is using Mongo 3.6 before adding default index

src/Explorer/Controls/NotebookGallery/Cards/GalleryCardComponent.tsx, src/Explorer/Controls/NotebookGallery/CodeOfConductComponent.tsx, src/Explorer/Controls/NotebookGallery/GalleryViewerComponent.tsx, src/Explorer/Controls/NotebookGallery/__snapshots__/CodeOfConductComponent.test.tsx.snap, src/Explorer/Controls/NotebookViewer/NotebookViewerComponent.tsx, src/Explorer/Explorer.ts, src/Explorer/Panes/PublishNotebookPaneAdapter.tsx, src/Explorer/Panes/PublishNotebookPaneComponent.tsx, src/Explorer/Panes/__snapshots__/PublishNotebookPaneComponent.test.tsx.snap, src/Explorer/Tree/ResourceTreeAdapter.tsx, src/Shared/Telemetry/TelemetryConstants.ts, src/Utils/GalleryUtils.ts
New telemetry actions -
- NotebooksGalleryPublish
- NotebooksGalleryReportAbuse
- NotebooksGalleryClickReportAbuse
- NotebooksGalleryViewCodeOfConduct
- NotebooksGalleryAcceptCodeOfConduct
- NotebooksGalleryFavorite
- NotebooksGalleryUnfavorite
- NotebooksGalleryClickDelete
- NotebooksGalleryDelete
- NotebooksGalleryClickDownload
- NotebooksGalleryDownload
- NotebooksGalleryViewNotebook
- NotebooksGalleryViewGallery
- NotebooksGalleryViewOfficialSamples
- NotebooksGalleryViewPublicGallery
- NotebooksGalleryViewFavorites
- NotebooksGalleryViewPublishedNotebooks
1. fix card layout if tags are not provided
2. Remove favorite, download, delete buttons from publish preview card
3. String updates
4. add "Publish to Gallery" in context menu
TODO
- Add icon for "Publish to gallery" in context …
=> Add telemetry for Notebooks Gallery and other updates

src/Explorer/Panes/DeleteCollectionConfirmationPane.ts, src/Explorer/Panes/DeleteDatabaseConfirmationPane.ts, src/Explorer/Tables/TableDataClient.ts
Missed this during our mass ARM migration. Cassandra deletes were still going through proxy instead of ARM.
=> Delete Cassandra tables/keyspaces via ARM

sampleData/gremlinSampleData.json
The `gremlinSampleData.json` is missing the `createNewDatabase` flag which allows the `SamplesDB` database to be created before creating the sample container.
=> Fix start with samples in Gremlin API

src/Explorer/Panes/AddCollectionPane.ts, src/Explorer/Panes/CassandraAddCollectionPane.ts
The `isAutoPilotSelected` flag needs to be true when creating a collection on a serverless account.
=> Fix serverless create issue

src/Explorer/Controls/NotebookGallery/GalleryViewerComponent.tsx, src/Explorer/Controls/NotebookGallery/__snapshots__/GalleryViewerComponent.test.tsx.snap
This PR removes published and favourites tabs when users sees the gallery through the cosmos.azure.com/gallery.html landing page and is not logged in. In such a case, the container passed to GalleryViewerComponent is undefind, and it used as a check.
Portal experience:
Stand alone Gallery experience:
=> Removed published, favourites tabs for hosted gallery

src/NotebookViewer/NotebookViewer.tsx
When the notebook viewer gets a tab name in the url, it does not propagate it to the Gallery link which is opened when the back arrow is clicked. This PR fixes that error. This is needed now since public gallery is going to be available as well.
=> Notebook viewer bug fix

src/Explorer/SplashScreen/SplashScreen.tsx
> [2:52 AM] @languy
>     
> @notlaforge I'm looking at SplashScreen as a template to migrate ResourceTree. I noticed that it subscribes to some ko's in the constructor: https://github.com/Azure/cosmos-explorer/blob/7188e8d8c26b9fde55e8e138875db8205f81a536/src/Explorer/SplashScreen/SplashScreen.tsx#L48 I suggest we do the subscribing in componentDidMount() and unsubscribe in componentWillUnmount()in order to properly cleanup and only subscribe when the component is being used. Thoughts? 
>
=> Fix subscription leak

src/Explorer/Controls/NotebookGallery/GalleryViewerComponent.tsx, src/Explorer/Controls/NotebookGallery/__snapshots__/GalleryViewerComponent.test.tsx.snap, src/Explorer/Explorer.tsx, src/GalleryViewer/GalleryViewer.tsx, src/Utils/GalleryUtils.ts
This PR makes the "Public Gallery" tab of the notebooks tab the landing / default tab in the Notebooks Gallery.
=> Swapped "Official samples" and "Public Gallery" tabs

.github/workflows/ci.yml
Removes the emulator test as check during PRs. Why?
- Its a slow and flaky test
- The emulator is released **very** rarely and never from a branch
- Emulator is always manually tested before release
- Almost all of the emulator specific init logic has been removed
- If it runs on master and fails, it is a good signal but will not block peoples work or deploys
Give these reasons I think its a fair trade off to only run this test on a master or release branch
=> Run Emulator test only on master

src/Common/ErrorHandlingUtils.ts
The code is calling ErrorHandlerUtility which has a dependency on `window` which is not available in a web worker
=> Fix upload worker error display

jest.config.js
In addition this changes the thresholds to meet the existing level of test coverage. This was motivated by work that imported a lot of existing yet untested (and unexercised) code, which brought down the total % without adding any more code.
=> Test coverage: include all source files

src/hooks/useKnockoutExplorer.ts
The refactor of #541 introduced a bug where userContext does not contain the AAD token before calling `listKeys` in the same method. As a result, the CosmosClient did not have access to the master key and was failing for certain operations against the Mongo Proxy. This PR fixes it, but brings up some long term concerns:
1. Should all our AAD function depend on userContext being populated? Should we make it accept the token as an optional parameter for cases like this?
2. Not having a fully populated userContext object is a recipe for bugs. We should ensure all userContext updates happen as soon as possible in the application*or* maybe look into moving userContext to a proper react context provider.
=> Fix Mongo AAD bug where collections are not loading

src/Explorer/Controls/Settings/SettingsComponent.tsx
Currently, Mongo Index editor tab shows a login error when a Mongo 3.2 account opens it.
The correct logic should be :
---> If Auth type is AAD 
----> If Mongo 3.6 +
----> show editor
-----> else
----> dont show the editor
----> If not AAD auth, show the AAD login error
This PR fixes this logic flow.
=> Mongo index editor bug fix 

src/Common/MessageHandler.ts, src/Controls/Heatmap/Heatmap.ts, src/Explorer/Tabs/MongoShellTab.ts, src/hooks/useKnockoutExplorer.ts
This change makes the ready message compatible with Ibiza SDK IFrame v1 control, currently used by the portal. The previous change made the ready message compatible with IFrame v2, but breaks current portal users.
=> Make ready message backwards compatible

src/Explorer/Notebook/NotebookComponent/epics.ts
Currently if there's an error when executing a code cell the UI keeps on showing circular progress bar. This is because the transient cell status is never reset after an execution has been canceled. Nteract simply stops updating the transient cell status as soon as an error is encountered and issues EXECUTE_CANCELED action for all cells.
This change adds an epic to always reset cell status after EXECUTE_CANCELED action.
=> Reset cell status after execution is canceled

src/Platform/Hosted/extractFeatures.ts
Since we are now calling `extractFeatures` in `UserContext` which is in the outer iframe layer instead of `explorer` which is in the inner iframe, we should use `window.location.search` instead of `window.parent.location.search`.
=> Use window instead of window.parent in extractFeatures function

src/Explorer/Tables/QueryBuilder/QueryBuilderViewModel.ts, src/Explorer/Tables/TableEntityProcessor.ts
When building queries with projections, the resulting query does not include the "id" property as part of the projection. The "id" property is used by the results grid to display as the RowKey so the result is queries wih projections do not show the RowKey.
This change fixes this by including "id" as part of the projections.
=> Fix table api query projections

src/Explorer/Tabs/TabsManager.html
I misunderstood the purpose of a `ko.foreach()` loop in my changes back in #534. This re-introduces the loop.
=> When switching between tabs, editors remain open

src/Platform/Hosted/extractFeatures.ts
This doesn't really fix the fact that portal feature flags are not being set, but it does re-enable feature flags in hosted mode.
=> Defensively set feature flags from window.parent

src/Explorer/Panes/UploadItemsPane/index.tsx
https://portal.microsofticm.com/imp/v3/incidents/details/234330983/home
The current file size check is preventing upload of files that would otherwise succeed. On the wire, without whitespace, the file can become smaller than the browser reported size. I don't see much point in keeping this check. The service will return an error for the file if it is too big.
=> Remove File upload size check

src/Localization/en/SqlX.json, src/SelfServe/SelfServe.tsx, src/SelfServe/SelfServeTelemetryProcessor.ts, src/SelfServe/SelfServeTypes.ts, src/SelfServe/SqlX/SqlX.tsx, src/Shared/Telemetry/TelemetryProcessor.ts
this PR
- Makes SelfServeTelemetryProcessor dependent on TelemetryProcessor
- renamed the methods in selfServeTelemetryProcessor
- extends trace, traceStart etc to take a message type as well ("TelemetryInfo" string enum is used for SelfServe as opposed to TelemetryInfo = 0 numeric enum for DE telemetry)
- Adds webpack chunk name for localization files dynamically loaded
- Added/Modified SqlX specific translation keys
=> SelfServe - Telemetry and Localization improvements

src/SelfServe/SelfServe.tsx, src/SelfServe/SelfServeTypes.ts, src/SelfServe/SelfServeUtils.test.tsx, src/SelfServe/SelfServeUtils.tsx, src/SelfServe/SqlX/SqlX.tsx
This PR
- There was mismatch in prod when the classname was set before the object instantiation earlier. now we use constructor.name throughout
- Removed setting className for selfServeDescriptor in SelfServeUtil
- Modified tests
=> Added className to SelfServeBaseClass

src/SelfServe/SqlX/SqlX.tsx, webpack.config.js
This PR adds a webpack change to ensure class and function names are not mangled. This is needed for selfserve, since we use the class name to build the intermediate data structure and to pick up translations.
=> Webpack changes for selfserve

src/Common/MessageHandler.ts, src/hooks/useKnockoutExplorer.ts
With the new iFrame component in Ibiza SDK the portal window only accepts messages coming from the windows that it created. This broke our Kusto telemetry logging from the Terminal windows because terminal windows are created by Data Explorer.
To fix this we now send messages from Terminal window to Portal window via Data Explorer.
Verified that this fix works by inspecting /extensiontelemetry payload.
=> Fix telemetry from child windows of Data Explorer

src/Explorer/Notebook/NotebookClientV2.ts, src/Explorer/Notebook/NotebookRenderer/NotebookReadOnlyRenderer.tsx, src/Explorer/Notebook/NotebookRenderer/NotebookRenderer.tsx, src/Explorer/Notebook/NotebookRenderer/outputs/IFrameOutputs.tsx, src/Explorer/Notebook/NotebookRenderer/outputs/SandboxFrame.tsx, src/Explorer/Notebook/NotebookRenderer/outputs/javascript.tsx, src/Platform/Hosted/extractFeatures.ts, src/Utils/StyleUtils.ts
To provide some context - currently we don't sandbox notebook outputs. This can be dangerous because malicious scripts can do unexpected things when just viewing a notebook. We're trying to solve that by sandboxing all outputs in `<iframe>`.
Verified that the following type of outputs work:
Preview URL for standalone gallery: https://cosmos-explorer-preview.azurewebsites.net/commit/0f4c261edbc746686ba26f1c1f593557c538c1c6/gallery.html?feature.sandboxNotebookOutputs=true
Unfortunately we can't preview in Data Explorer due to feature flags no being honored in Portal. And AAD doesn't work for Hosted mode for preview endpoints.
=> Sandbox outputs for every code cell using <iframe>

src/Common/dataAccess/readCollections.ts, src/Common/dataAccess/updateCollection.ts, src/Explorer/Controls/Settings/SettingsComponent.test.tsx, src/Explorer/Controls/Settings/SettingsComponent.tsx, src/Explorer/Explorer.tsx, src/hooks/useKnockoutExplorer.ts
ICM: https://portal.microsofticm.com/imp/v3/incidents/details/235371314/home
`readCollections` for Mongo accounts is still using the SQL SDK.  Calling via the SQL SDK was preventing private endpoint Mongo accounts for loading properly in the portal and those users are unable to see their collections. This original reason we special cased Mongo was due to some ARM gaps, but it appears those have been addressed.
This also fixes a bug in the development mode iframe logic for the portal. It was not updating userContext correctly when loading the message from the cache.
=> Call readCollections for Mongo using ARM

src/Contracts/DataModels.ts, src/Explorer/Tabs/MongoDocumentsTab.ts, src/Explorer/Tree/Collection.ts, src/Explorer/Tree/Database.ts
ICM: https://portal.microsofticm.com/imp/v3/incidents/details/236412873/home
This fixes a bug introduced by https://github.com/Azure/cosmos-explorer/pull/636
Mongo collections were previously loaded via the SQL SDK which returned a `parititonKey` property. ARM returns a `shardKey` property in a different format. This PR still loads the collections via ARM but it adds a `partitionKey` property to the response calculated from `shardKey`. This is a bit of a hack, but lots of downstream code expects `Collection.partitionKey` to exist.
I have manually tests CRUD for the following cases:
- No shard key
- Simple shard key: `foo`
- Complex shard key: `foo.bar.baz`
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/657?feature.someFeatureFlagYouMightNeed=true)
=> Fix for Mongo shard key loaded via ARM

src/Explorer/Explorer.tsx, src/Explorer/Menus/CommandBar/CommandBarComponentButtonFactory.tsx
Feature request from a user: https://portal.microsofticm.com/imp/v3/incidents/details/235635477/home
Best I can tell there is no reason to hide this in hosted mode
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/660?feature.someFeatureFlagYouMightNeed=true)
=> Expose Settings in Hosted Mode

package-lock.json, src/Explorer/Notebook/NotebookRenderer/markdown-cell.tsx
By manually importing `markdown-cell.tsx` from `@nteract/stateful-components` (in #658), we introduced a new dependency to `@nteract/presentational-components@3.4.9`. The rest of the code relies on `@nteract/presentational-components@3.4.8`.
The difference between the two versions is [a now missing `width: 100%`](https://github.com/nteract/nteract/commit/7fa580011578350e56deac81359f6294fdfcad20#diff-07829a1908e4bf98d4420f868a1c6f890b95d77297b9805c9590d2dba11e80ce) for the markdown editor.
This fix reinstates the style to properly show the editor.
=> Fix Markdown Editor not displaying when double-clicking on Markdown cell

src/Explorer/Notebook/NotebookRenderer/outputs/SandboxFrame.tsx
Use height of frameBody's firstElementChild instead of frameBody's. For some reason frameBody's height is not correct in some scenarios but using frameBody.firstElementChild's height gives the correct height.
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/676)
=> Fix height for SandboxFrame

src/Explorer/Controls/Settings/SettingsSubComponents/SubSettingsComponent.tsx
Hide ttl options for Mongo in settings tab and display a message to ask the customers to create a `_ts` index instead.
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/677)
=> Hide TTL in settings tab for Mongo API

src/Explorer/Panes/ExecuteSprocParamsPanel/__snapshots__/index.test.tsx.snap, src/Explorer/Panes/ExecuteSprocParamsPanel/index.tsx
Changing the default here from `undefined` to  `""` ended up breaking non-partitioned stored procedure execution 
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/685?feature.someFeatureFlagYouMightNeed=true)
=> Fix Stored Procedures for Non-Partitioned Collections

src/Common/dataAccess/bulkCreateDocument.ts, src/Explorer/Tree/Collection.ts
Unfortunately the new SDK bulk methods are TOO FAST! In production, uploading a JSON file of just 50 items will cause throttling. This PR adds some basic retry logic for throttled document creations when uploading a JSON file
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/684?feature.someFeatureFlagYouMightNeed=true)
=> Adds retry logic to Upload JSON

src/Explorer/Panes/ExecuteSprocParamsPanel/index.tsx
This was missed in the React migration. Custom parameters and partition keys need to be run through `JSON.parse`
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/693)
=> Parse Custom sproc parameters

src/Explorer/Tree/Database.ts
ICM: https://portal.microsofticm.com/imp/v3/incidents/details/236927554/home
https://github.com/Azure/cosmos-explorer/pull/657 introduced a bug where connection string users were getting their partition key overridden. Long term we need a better solution here. `readCollections` is too abstract.
=> Fix Mongo Parition Keys for Connection String mode

src/Explorer/Panes/AddCollectionPane.ts
After a collection is created the first name, `resetData` is called which sets the `isAutoPilotSelected` boolean to true. This causes issue for serverless account since we cannot set throughput value.
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/708)
=> Fix create collection for serverless account

src/Explorer/Panes/Tables/EditTableEntityPanel.tsx, src/Explorer/Tables/TableEntityProcessor.ts
Currently boolean and number (double and integer) type property values are stored as string. We need to parse the string value based on the property type.
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/737)
=> Fix table entity boolean and number type property values

src/Explorer/Explorer.tsx
Earlier, the "Enable Notebooks" button in the command bar was enabled only if the databaseAccount location was not a disallowed location. With these changes, the same check is made on both 
- database account location
- first write region of the database account
=> Enable the "Enable notebooks" button

src/Explorer/Notebook/NotebookRenderer/NotebookReadOnlyRenderer.tsx
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/746)
We have a custom implementation of `Markdown` cell that we use in `NotebookRenderer`. This custom implementation disables HTML rendering in markdown cells. This change uses the same for `NotebookReadOnlyRenderer` which we use for Gallery.
=> Disable HTML in markdown cell for NotebookReadOnlyRenderer

src/CellOutputViewer/CellOutputViewer.less, src/CellOutputViewer/CellOutputViewer.tsx, src/Explorer/Notebook/NotebookRenderer/outputs/SandboxOutputs.tsx, src/Explorer/Notebook/SchemaAnalyzerComponent/SchemaAnalyzerComponent.less, src/Explorer/Notebook/SchemaAnalyzerComponent/SchemaAnalyzerComponent.tsx
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/747?feature.enableSchemaAnalyzer=true)
Use CellOutputViewer for rendering Schema Analyzer outputs too. This way we are using all the supported output transforms in a secure way. Also add support for custom class names to style individual outputs.
This also fixes an issue where `text/html` data isn't rendered in Schema Analyzer tab. That was a regression because of sandboxing outputs work. We now no longer load any Nteract output transforms in Data Explorer. CellOutputViewer is the one which loads all transforms lazily,
=> Use CellOutputViewer for SchemaAnalyzer

src/Explorer/Panes/AddCollectionPanel.tsx, src/Explorer/Tables/TableEntityProcessor.ts
Table edit entity bug:
- The boolean entity value could be either string or boolean so we can call `.toString` to convert boolean value into string.
Table int64 bug:
- We need to pass the entity value of a int64 type as a string instead of number.
Add collection panel bug:
- Add null check for `databaseAccount.properties` and `databaseAccount.properties.capabilities`.
=> Fix table edit entity bug and add collection panel bug for connection string users

src/SelfServe/SelfServeComponent.tsx, src/SelfServe/SelfServeUtils.tsx
This PR
- Adds a Metrics Blade type for selfServe components to generate a link to the metrics blade
- Fixes a bug with Save/Discard buttons not being disabled correctly when an element's default value is set to undefined. 
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/764)
=> Added metrics blade link and fixed SelfServe bugs

src/Explorer/Panes/AddCollectionPanel.tsx
The new collection pane behavior changed for connection string users and ended up passing `analyticalTTL` as `0` which throw a backend error if synapse is not enabled on the account.
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/778?feature.someFeatureFlagYouMightNeed=true)
=> Pass undefined analyticalTTL if Synapse is disabled

src/Explorer/Controls/ThroughputInput/ThroughputInput.test.tsx, src/Explorer/Controls/ThroughputInput/ThroughputInput.tsx, src/Explorer/Panes/AddCollectionPanel.tsx, src/Explorer/Panes/AddDatabasePanel/AddDatabasePanel.tsx, src/Explorer/Panes/AddDatabasePanel/__snapshots__/AddDatabasePanel.test.tsx.snap, src/Utils/CapabilityUtils.ts, src/hooks/useSidePanel.ts
This PR fixes the following issues:
- `Throughputinput` component should maintain the throughput value, `isAutoscaleSelected` flag, and `isCostAcknowledged` flag as states and re-render itself when these values change. It shouldn't rely on the parent components to keep track of these states and re-render. The parent component should only be responsible for reading these values.
- A lot of small fixes in `AddDatabasePane` which are mostly styling fixes and removing redundant code.
- Fixes a console error in `useSidePanel` where `onCloseCallback.callback` can be undefined and throws an exception when called.
=> Fix throughput input component and add database panel

src/Explorer/Controls/ThroughputInput/ThroughputInput.test.tsx, src/Explorer/Controls/ThroughputInput/ThroughputInput.tsx, src/Explorer/Controls/ThroughputInput/__snapshots__/ThroughputInput.test.tsx.snap, src/Explorer/Explorer.tsx, src/Explorer/Panes/AddDatabasePanel/AddDatabasePanel.tsx, src/Explorer/Panes/PanelInfoErrorComponent.tsx, src/Explorer/Panes/RightPaneForm/RightPaneForm.test.tsx, src/Explorer/Panes/RightPaneForm/RightPaneForm.tsx, src/Explorer/Panes/RightPaneForm/__snapshots__/RightPaneForm.test.tsx.snap, src/Explorer/Panes/SettingsPane/SettingsPane.tsx, src/Explorer/Panes/SettingsPane/__snapshots__/SettingsPane.test.tsx.snap, src/Explorer/Panes/UploadFilePane/UploadFilePane.tsx, src/Explorer/Panes/UploadItemsPane/UploadItemsPane.tsx, src/Explorer/Panes/UploadItemsPane/__snapshots__/UploadItemsPane.test.tsx.snap
- fixed a styling issue in `RightPaneForm` component where the `PanelInfoErrorComponent` makes the panel exceed 100% height
- refactored logic for showing `PanelInfoErrorComponent` and removed some unnecessary hooks
- fixed a issue in AddDatabasePane where clicking on the "show details" button does not expand the notification console
- added a new test case for throughputinput component which tests switching between manual and autoscale mode
- fixed a issue in UploadItemsPane where we still send a request even when input validation fails
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/780)
=> Batch of small fixes for RightPaneForm and AddDatabasePane components

src/Explorer/Tree/Collection.ts, src/Explorer/Tree/Database.ts
Currently we use `this.offer()` to determine whether we have read the offer of a database/collection. However, `this.offer()` could be `undefined` in both of the following cases:
1. The offer of a database/collection has not been read
2. The offer of a database/collection has been read and is `undefined`
In the second case, we clearly don't need to read the offer again but our current logic does it anyways.
To fix this issue, I added a new flag to indicate whether the offer has been read and used to in combination with `this.offer()` to determine whether we need to read the offer via ARM.
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/768)
=> Improve lazy load database/collection offer logic

src/Explorer/Controls/InputTypeahead/InputTypeaheadComponent.tsx
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/793?feature.someFeatureFlagYouMightNeed=true)
The old input-typeahead component was removed [here](https://github.com/Azure/cosmos-explorer/commit/f9e8b5eaaae0af2b39b93ab999bcca5f0904a3a8#diff-cdea1174da6c9b0ec78d5aeb7242f54a06e3b87ce846d61731e0ce37955006db), but the React-based input-typeahead component now must import the package, in order to work.
=> Add 'import 'jquery-typeahead' to fix InputTypeahead in GraphExplorer

src/Explorer/Panes/AddCollectionPanel.tsx
Fixed the logic for setting throughput based on user inputs. There are 4 cases:
1. Shared database + new database: we should use the throughput of the new database
2. Shared database + existing database: no need to set throughput in this case
3. Non-shared database + new database: use throughput of the new container
4. Non-shared database + existing database: use throughput of the new container
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/808)
=> Fix container manual throughput for non-shared database

src/SelfServe/SelfServeComponent.tsx, src/SelfServe/SqlX/SqlX.rp.ts
This PR ensures errors from RP calls are thrown so that they are correctly surfaced by the Self Serve Framework.
Also fixed a bug with DISCARD.
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/816?feature.someFeatureFlagYouMightNeed=true)
=> Sqlx bug fixes

src/HostedExplorer.tsx, src/hooks/useAADAuth.ts
We were using the catchall cosmos.azure.com which doesn't work well in other non-mpac or prod environments
=> Use customer endpoint for RBAC AAD auth

src/HostedExplorer.tsx, src/hooks/useAADAuth.ts
There seems to be a race condition with loading the account switching tenants
=> Rollback DB endpoint use by AAD

.github/workflows/ci.yml
The current preview upload script has a bug. It only works on commits coming from PRs. When the commit is built from master it fails as `github.event.pull_request.head.sha` does not exist. This PR adds a fall back to `github.sha`
=> Upload master commits for preview

web.config
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/829)
We bundle js/css along with `cellOutputViewer.html`. So if we don't disable cache the browser wouldn't pickup new changes in the file. This is causing issues with rendering cell outputs (in both notebooks and schema analyzer) in prod.
=> Disable caching for cellOutputViewer.html

preview/config.json, preview/index.js, src/ConfigContext.ts, src/HostedExplorer.tsx, src/hooks/useAADAuth.ts
Adds `msalRedirectURI` and a few tweaks to the preview app that will allow us to use the preview URLs as stand alone hosted explorer. Essentially previews of cosmos.azure.com instead of just working in the portal
=> Enable Preview for Hosted Mode

src/Common/CosmosClient.ts, src/hooks/useKnockoutExplorer.ts
Users getting started with DataPlane RBAC are restricting access to listKeys, and using AAD as the fallback. We can give the master key to the SDK in that case, since they won't be able to fetch it anyway
=> Removes feature flag from passing masterKey to SDK

package-lock.json, package.json, src/Explorer/Controls/Editor/EditorComponent.ts, src/Explorer/Controls/Editor/EditorReact.tsx, src/Explorer/Controls/JsonEditor/JsonEditorComponent.ts
ICM https://portal.microsofticm.com/imp/v3/incidents/details/243084374/home
I am hoping upgrading Monaco fixes this issue https://github.com/microsoft/monaco-editor/issues/643
Monaco breaks when loaded inside a cross origin iframe? The same exact code and script tab works fine on cosmos.azure.com. Wild
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/847?feature.someFeatureFlagYouMightNeed=true)
=> Upgrade Monaco Editor

src/Explorer/Controls/ThroughputInput/ThroughputInput.test.tsx, src/Explorer/Controls/ThroughputInput/ThroughputInput.tsx, src/Explorer/Controls/ThroughputInput/__snapshots__/ThroughputInput.test.tsx.snap, src/Explorer/Panes/UploadItemsPane/__snapshots__/UploadItemsPane.test.tsx.snap
This is for fixing: https://msdata.visualstudio.com/CosmosDB/_workitems/edit/1200815. We should use 400 - 10000 RU instead of 400 - unlimited for unsharded collection.
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/845)
=> Show 10k RU instead of unlimited as max RU for unsharded collection

src/Contracts/ViewModels.ts, src/Explorer/Explorer.tsx, src/Explorer/Tabs/MongoShellTab.ts, src/Explorer/Tabs/TabsBase.ts, src/Explorer/Tabs/TerminalTab.tsx, src/Explorer/Tree/Collection.ts
This PR 
- FIxes the terminal tabs and mongo shell tabs numbering. 
Earlier, 
**new tab index = number of tabs of the same type open + 1** 
So if 
- tab 1 was opened
- tab 2 was opened
- tab 1 was closed
- new tab is opened ----> New tab would be "Mongo Terminal 2", when it should be actually be "Mongo Terminal 3". 
So I introduce an 'index' property. now 
**new tab index = index of the latest tab (of the same type) open + 1** 
- Adds a spinner to the terminal tab when terminal is loading
- Fixed error due to which terminal tabs did not load if they were opened quickly after DE loads, and the notebookServerEndpoint is not populated yet. Now, the terminal tabs are populated only after the notebookServerEndpoint is populated to a non null value.
[Preview this …
=> Mongo tabs UX fixes

src/Common/MongoProxyClient.ts, src/Explorer/Explorer.tsx
Fixed the following issues:
1. `Cannot read property 'continuationToken' of undefined` error: The `MongoProxyClient.queryDocuments` calls `MongoProxyClient.errorHandling` when the response contains an error. However, since `errorHandling` is an async function, we have to add `await` in the caller. Otherwise, `queryDocuments` would return an undefined result before the error is thrown, which then causes more script errors.
2. Save and browse query panes do not correctly check if the `___Cosmos` database has already been created: This is because we are lazy loading the containers. If we don't expand the `___Cosmos` database, then we do not load its containers. Therefore, we can't find the `___Query` container and the check returns false. The fix is to always load the containers if the …
=>  Fix query tab/pane related issues

src/Explorer/Controls/Settings/__snapshots__/SettingsComponent.test.tsx.snap, src/Explorer/Panes/GitHubReposPanel/__snapshots__/GitHubReposPanel.test.tsx.snap, src/Explorer/Panes/StringInputPane/__snapshots__/StringInputPane.test.tsx.snap, src/Explorer/Tree/Collection.ts, src/Explorer/Tree/Database.ts, src/Explorer/Tree/ResourceTreeAdapter.tsx
We can get rid of all the knockout subscriptions in resource tree by updating the `useDatabases` store whenever a collection changes.
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/904)
=> Replace subscriptions in resource tree with useDatabases hook

src/Explorer/Controls/Settings/SettingsComponent.tsx, src/Explorer/Tree/Collection.ts
After loading the collection offer, we never update `this.offer`. Also, we need to wait to the offer to finish loading before setting the throughput values.
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/926?feature.someFeatureFlagYouMightNeed=true)
=> Fix scale component not showing in settings tab

src/Contracts/DataModels.ts, src/hooks/useDatabaseAccounts.tsx, src/hooks/useKnockoutExplorer.ts
Data explorer is currently completely broken for users with disableLocalAuth = true as we try to call listKeys which succeeds, but the key itself doesn't work in the data plane. this ensures we only use AAD auth from the beginning
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/EDIT_THIS_NUMBER_IN_THE_PR_DESCRIPTION?feature.enableAadDataPlane=true)
=> Adds disableLocalAuth check for listKeys call

src/Explorer/Explorer.tsx
Need to import the `ComponentRegisterer` module in Explorer to register the json editor.
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/935?feature.someFeatureFlagYouMightNeed=true)
=> Fix json editor in documents tab

src/Common/dataAccess/createCollection.test.ts, src/Common/dataAccess/createCollection.ts, src/Common/dataAccess/createDatabase.ts, src/Explorer/useDatabases.ts, test/cassandra/container.spec.ts, test/graph/container.spec.ts, test/mongo/container.spec.ts, test/mongo/container32.spec.ts, test/notebooks/upload.spec.ts, test/sql/container.spec.ts, test/tables/container.spec.ts, test/utils/waitForExplorer.ts
- Removed the additional `GET` call before creating a database/container to check if the name is unique. Instead, do the check using the `useDatabses` zustand store.
- Increased the default timeout from 30s to 50s for tests that involve database/container creation.
- Added `waitForExplorer` function in tests that involve database/container creation. The function adds a timeout of 5 seconds after data explorer loads to make sure all the databases/containers are done loading and is available in the `useDatabses` store.
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/949?feature.someFeatureFlagYouMightNeed=true)
=> Improve e2e stability

src/Explorer/Notebook/useNotebook.ts
When initializing the notebooks tree, the `gitHubNotebooksContentRoot` needs to be set at the same time as `myNotebooksContentRoot` and `galleryContentRoot`. Otherwise, it would trigger two re-renders of the resource tree, and the first re-render would throw an error since `gitHubNotebooksContentRoot` hasn't been set and is still undefined.
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/951?feature.someFeatureFlagYouMightNeed=true)
=> Fix connect to github

src/Explorer/useDatabases.ts
For a new tables account, the database is undefined when creating the first table.
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/958?feature.someFeatureFlagYouMightNeed=true)
=> Fix validateCollectionId for new tables account

src/Common/ResourceTreeContainer.tsx, src/Explorer/Explorer.tsx, src/Explorer/Notebook/NotebookContentClient.ts, src/Explorer/Notebook/useNotebook.ts, src/Explorer/Panes/CopyNotebookPane/CopyNotebookPane.tsx, src/Explorer/Tree/ResourceTree.tsx, src/Juno/JunoClient.ts, src/Platform/Hosted/extractFeatures.ts
Currently the new resource tree re-renders every 5 seconds if notebooks is enabled for the account because it listens to the entire `useNotebooks` store instead of just the states that it needs. The memory tracker component updates the `memoryUsageInfo` state in the store every 5 seconds which triggers the resource tree to re-render. This behavior also masked some other issues since the resource tree is able to pick up the latest state every 5 seconds, making it look like the resource tree re-renders correctly for certain actions when it's actually not.
Here's a list of issues exposed after fixing the re-rendering issue:
- The resource tree does not re-render after creating a new notebook
- The resource tree does not re-render after renaming a notebook
- The resource tree does not …
=> Fix new resource tree

src/Explorer/Controls/Dialog.tsx
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/969?feature.someFeatureFlagYouMightNeed=true)
The `true` in the `closeDialog` method is causing the entire state to be overwritten including the methods that control the dialog. This fixes that bug. But long term it should probably not be `true`
=> Fix bug in Dialog State store

src/Explorer/Notebook/NotebookComponent/NotebookComponentBootstrapper.tsx, src/Explorer/Notebook/NotebookComponent/VirtualCommandBarComponent.tsx, src/Explorer/Notebook/NotebookRenderer/NotebookRenderer.tsx, src/Explorer/Notebook/NotebookRenderer/Prompt.less, src/Explorer/Notebook/NotebookRenderer/Prompt.tsx, src/Explorer/Notebook/NotebookRenderer/PromptContent.test.tsx, src/Explorer/Notebook/NotebookRenderer/PromptContent.tsx, src/Explorer/Notebook/NotebookRenderer/Toolbar.tsx, src/Explorer/Notebook/NotebookRenderer/__snapshots__/PromptContent.test.tsx.snap, src/Explorer/Notebook/NotebookRenderer/decorators/kbd-shortcuts/index.tsx, src/Explorer/Notebook/NotebookUtil.ts, src/Explorer/Notebook/SecurityWarningBar/SecurityWarningBar.test.tsx, src/Explorer/Notebook/SecurityWarningBar/SecurityWarningBar.tsx, src/Explorer/Notebook/SecurityWarningBar/__snapshots__/SecurityWarningBar.test.tsx.snap, src/Explorer/Tabs/NotebookV2Tab.ts, src/Utils/GalleryUtils.ts
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/970)
1. Mark all notebooks downloaded from the Public Gallery as untrusted (by setting "untrusted" flag in notebook metadata)
2. Block executing Untrusted notebook from Keyboard shortcut, Hover button, Context Menu, and Command bar menu
3. Allow a user to Trust Notebook
Addresses this bug - https://msdata.visualstudio.com/CosmosDB/_workitems/edit/1224092/
=> Add Security Warning Bar for untrusted notebooks

less/Common/Constants.less, less/resourceTree.less, src/Explorer/Explorer.tsx, src/Explorer/Menus/CommandBar/CommandBarComponentButtonFactory.test.ts, src/Explorer/Menus/CommandBar/CommandBarComponentButtonFactory.tsx, src/Explorer/Menus/CommandBar/CommandBarUtil.tsx, src/Explorer/Tree/ResourceTree.tsx
this pr
- Makes the command bar icons gray when the command bar buttons are disabled
- Hides the "Enable Notebooks" button behind featureflag
- Makes the "Notebooks is currently unavailable ..." resource tree item unclickable
- Hides notebook initialization calls under feature flag
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/979)
=> Changes for Disabling notebook related features

src/Explorer/Panes/PublishNotebookPane/PublishNotebookPane.tsx, src/Juno/JunoClient.test.ts, src/Juno/JunoClient.ts
DE change to address this pentest bug: https://msdata.visualstudio.com/CosmosDB/_queries/edit/1223992/?triage=true
The author name can currently be spoofed since it is part of the payload for notebook publish request.
This PR removes the author name from the payload.
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/966)
=> Removing author from publish notebook payload

src/hooks/useAADAuth.ts, src/hooks/useKnockoutExplorer.ts
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1004?feature.enableAadDataPlane=true)
We were fetching the aadToken always against the default authority (I believe that's login.microsoftonline/common) but we have access to and can set the cachedTenantId when they change directories or accounts or login/out, so we can fetch with that tenantId.
=> Fetch aad token against tenant's authority

src/Common/MongoProxyClient.test.ts, src/Common/MongoProxyClient.ts, src/Explorer/Controls/Settings/SettingsRenderUtils.tsx, src/Explorer/Controls/ThroughputInput/CostEstimateText/CostEstimateText.tsx, src/Platform/Hosted/extractFeatures.test.ts, src/Shared/Constants.ts, src/Shared/PriceEstimateCalculator.ts, src/Utils/PricingUtils.test.ts, src/Utils/PricingUtils.ts
Fixed incorrect cost estimate formula used in add collection panel:
- For multi-master, we should multiply the price by the number of regions instead of number of regions + 1
- Removed the multi-master multiplier from the formula. The base price for autoscale throughput already takes into account the multiplier. I added the multiplier into the base price for manual throughput.
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1070?feature.someFeatureFlagYouMightNeed=true)
=> Fix throughput cost estimate in add collection panel

src/Explorer/Notebook/useNotebook.ts
Data pane expansion issue fixed.
**Issue Context:**
Data Node expansion was linked to GitHub tree connection i.e., when user connects to GitHub we collapse Data and expand GitHub. During phoenix changes I have created a GitHub tree in left menu with the context menu to connect to GitHub and as part it this got broke. We reverted the GitHub left menu changes but this missed. This PR fix this.
=> Data pane expand issue

src/Common/Tooltip/InfoTooltip.tsx, src/Explorer/Controls/ThroughputInput/__snapshots__/ThroughputInput.test.tsx.snap, src/Explorer/Panes/AddCollectionPanel.tsx
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1022?feature.someFeatureFlagYouMightNeed=true)
Fixed 'Info' icons containing tooltip information under 'New collection' blade accessible using keyboard issue.
https://user-images.githubusercontent.com/79906609/132536564-3414fd8a-8163-4673-a004-0eee9c680f1c.mp4
=> Fixed add collection tooltip accessibility issue

src/Explorer/Controls/ThroughputInput/ThroughputInput.tsx, src/Explorer/Controls/ThroughputInput/__snapshots__/ThroughputInput.test.tsx.snap
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1020?feature.someFeatureFlagYouMightNeed=true)
Added aria-required property  for 'Autoscale' and 'Manual' radio controls under 'New collection' , 'New Graph', 'New Database',  and 'New Table'  blade.
=> fixed aria-required property missing issue

src/hooks/useTabs.ts
Ensure that when promoting a new tab to being the 'active' tab (as a consequence of, say, closing the active tab) that the newly promoted tab has a chance to install its buttons and what not.
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1107)
https://user-images.githubusercontent.com/3104/134435353-68bcb0e2-8a4c-4981-823e-7aa6c50725ea.mov
=> Close tab fixes

jest.config.js, src/Utils/GalleryUtils.test.ts
Download from gallery pop-up expects explorer.tsx class instance but a concrete object was passed. 
Fixed this.
=> Fix Unit Test: Mock the class to its instance 

src/Contracts/DataModels.ts, src/Explorer/Controls/Settings/SettingsComponent.tsx, src/Explorer/Controls/Settings/SettingsSubComponents/ScaleComponent.tsx, src/Explorer/Controls/Settings/SettingsSubComponents/ThroughputInputComponents/ThroughputInputAutoPilotV3Component.tsx, src/Explorer/Controls/ThroughputInput/ThroughputInput.test.tsx, src/Explorer/Controls/ThroughputInput/ThroughputInput.tsx, src/Explorer/Controls/ThroughputInput/__snapshots__/ThroughputInput.test.tsx.snap, src/Explorer/Panes/AddCollectionPanel.tsx, src/Explorer/Panes/AddDatabasePanel/AddDatabasePanel.tsx, src/Explorer/Panes/AddDatabasePanel/__snapshots__/AddDatabasePanel.test.tsx.snap, src/Explorer/Panes/CassandraAddCollectionPane/CassandraAddCollectionPane.tsx, src/Explorer/Panes/DeleteCollectionConfirmationPane/__snapshots__/DeleteCollectionConfirmationPane.test.tsx.snap, src/Explorer/Panes/ExecuteSprocParamsPane/__snapshots__/ExecuteSprocParamsPane.test.tsx.snap, src/Explorer/Panes/PanelFooterComponent.tsx, src/Explorer/Panes/RightPaneForm/RightPaneForm.tsx, src/Explorer/Panes/RightPaneForm/__snapshots__/RightPaneForm.test.tsx.snap, src/Explorer/Panes/StringInputPane/__snapshots__/StringInputPane.test.tsx.snap, src/Explorer/Panes/Tables/TableQuerySelectPanel/__snapshots__/TableQuerySelectPanel.test.tsx.snap, src/Explorer/Panes/Tables/__snapshots__/AddTableEntityPanel.test.tsx.snap, src/Explorer/Panes/Tables/__snapshots__/EditTableEntityPanel.test.tsx.snap, src/Explorer/Panes/__snapshots__/DeleteDatabaseConfirmationPanel.test.tsx.snap, src/Platform/Hosted/extractFeatures.ts, src/Utils/arm/generatedClients/cosmos/sqlResources.ts, src/hooks/useDatabaseAccounts.tsx
- add check for throughput cap when creating a new database/collection
- add throughput cap error message under the throughput value text field in add collection panel and add database panel
- block the user from sending the create request if throughput cap is exceeded
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1151?feature.someFeatureFlagYouMightNeed=true)
=> Add throughput cap error message

src/Utils/arm/generatedClients/cosmos/sqlResources.ts, src/hooks/useDatabaseAccounts.tsx
2021-10-15 version is not available in all environments. For fetching sql resources, we do not need the latest version so I'm reverting the version back to 2021-04-15. For fetching database account, we should be using 2021-10-15-preview.
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1154?feature.someFeatureFlagYouMightNeed=true)
=> Fix ARM api version

src/Explorer/Controls/Settings/SettingsComponent.tsx, src/Explorer/Controls/ThroughputInput/ThroughputInput.tsx, src/Explorer/Explorer.tsx, src/Explorer/Menus/CommandBar/CommandBarComponentButtonFactory.tsx, src/Explorer/SplashScreen/SplashScreen.tsx, src/Explorer/Tree/Collection.ts, src/Explorer/Tree/Database.tsx
With the latest change in portal, when throughput cap is turned off for an account, the value is set to -1 instead of null. Therefore, when we check the throughput cap value in data explorer, we need to account for the -1 value.
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1159?feature.someFeatureFlagYouMightNeed=true)
=> Check for -1 throughput cap value

src/Explorer/Panes/Tables/Validators/EntityTableHelper.tsx, src/Explorer/Tables/Constants.ts, src/Explorer/Tables/TableDataClient.ts
- added Timestamp type to CassandraTypes
- treat Timestamp values as string and wrap the values inside single quotes when creating queries
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1163?feature.someFeatureFlagYouMightNeed=true)
=> Add Timestamp type to cassandra column types and wrap Timestamp value inside single quotes when creating queries

src/Common/Constants.ts, src/ConfigContext.ts, src/GitHub/GitHubOAuthService.ts, src/Juno/JunoClient.ts, src/Utils/GitHubUtils.ts
This PR
- Adds a new config context for github test env client id
- Adds logic to pick this client id to send for github OAuth call and to junoin case juno endpoint used is test/test2/test3
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1168)
=> Added integration for new github client for test env

src/Explorer/Tables/DataTable/TableEntityListViewModel.ts
Currently if the table columns change after sending a query, instead of setting the tables header to the new set of columns, we incorrectly set it to the difference between the old columns and the new columns. The fix is to simply pass the entire array of the new columns to the `updateHeaders` function instead of just the difference.
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1166?feature.someFeatureFlagYouMightNeed=true)
=> Properly update table columns

src/Common/Constants.ts, src/Explorer/Explorer.tsx, src/Explorer/Menus/CommandBar/CommandBarComponentAdapter.tsx, src/Explorer/Menus/CommandBar/CommandBarComponentButtonFactory.tsx, src/Explorer/Notebook/NotebookContainerClient.ts, src/Explorer/Notebook/useNotebook.ts, src/Explorer/Panes/CopyNotebookPane/CopyNotebookPane.tsx, src/Explorer/SplashScreen/SplashScreen.tsx, src/Explorer/Tree/Collection.ts, src/Explorer/Tree/ResourceTree.tsx, src/Platform/Hosted/extractFeatures.ts, src/Utils/GalleryUtils.ts, src/hooks/useKnockoutExplorer.ts
This PR
- Renames phoenix feature flag to "phoenixnotebooks". This is used for all notebook related checks
- Adds a seaprate phoenixfeatures flag for schema analyzer, mongo terminal and cassandra terminal
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1184?feature.phoeixfeatures=true&feature.phoeixnotebooks=true)
=> Added separate flag for shells and schema analyzer

src/Contracts/ExplorerContracts.ts, src/Explorer/Controls/Notebook/NotebookTerminalComponent.test.tsx, src/Explorer/Controls/Notebook/NotebookTerminalComponent.tsx, src/Explorer/Explorer.tsx, src/Explorer/Tabs/TerminalTab.tsx, src/Terminal/JupyterLabAppFactory.ts, src/Terminal/TerminalProps.ts, src/Terminal/index.ts, src/hooks/useKnockoutExplorer.ts
This PR
- Adds logic to check the terminal output messages to see if the mongo or cassandra shells are closed
- If closed, a "closetab" message is sent from terminal iframe to cosmos-explorer (the parent)
- This is read and handled by the cosmos explorer which closes the tab with the correspondign tabId
- Also fixes a bug with tab numbering
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1183)
=> Close mongo and casssandra terminal tabs once the shells are exited

src/Explorer/Menus/CommandBar/CommandBarComponentButtonFactory.test.ts, src/Explorer/Menus/CommandBar/CommandBarComponentButtonFactory.tsx, src/Explorer/Panes/AddCollectionPanel.tsx
Removing account serverless check to show synapse link options on command bar and new container pane.
=> Removing serverless check to show synapse link options

src/Explorer/Tree/Collection.ts
It's hard to know which tab has the data of which container today since they are all named "Items". This makes it easier to differentiate them.
Added the container id to the tab name so instead of all reading "Items" they read as "Planet - Items", "Books - Items", etc. 
Ran the cosmos explorer locally, used the feature flag on portal to point it to my local cosmos explorer and validated that the tab name now had the id. 
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1233)
=> Update Tab title from 'Items' to id + ' - Items' to make it easier to differentiate them

src/Explorer/Controls/Settings/SettingsComponent.tsx
In the constructor of the settings component, the states are initialized with `undefined` so when the settings tab is rendered the first time, it will have no selected value. The actual values of the states are only populated when the component is mounted. Normally when we call `setState` in settings component, it should also trigger a re-render for the inner tabs/pivots (e.g. scale, settings, indexing policy), updating the selected values. However, it looks like there's some special logic for the fluent UI pivot/pivot items which causes the inner tabs to not update while it's the active tab.
This fix sets the proper initial value for the states in the constructor which fixes the issue. However, a better fix would be to move the actual content of the tabs outside of the pivot. This way we …
=> Fix settings tab shows no selected value

src/Phoenix/PhoenixClient.ts, src/Shared/Telemetry/TelemetryConstants.ts, src/hooks/useKnockoutExplorer.ts
This PR:
> Making phoenix enabled irrespective ofDE launched from portal or hosted explorer.
> Add telemetry for IsDBAccountWhitelisted Call
=> Make Phoenix enabled based of config context

src/Common/CosmosClient.ts
We discovered recently that v2 SDks which are not merge proof are sending the header "x-ms-cosmos-sdk-supported-capabilities" so changing it to "x-ms-cosmos-sdk-supportedcapabilities" to ensure non supported sdks are blocked when customer opts into merge
This is a follow up for https://github.com/Azure/cosmos-explorer/pull/1190
=> Change Headers meant to unblock merge private preview customers

src/Common/MongoProxyClient.test.ts, src/Common/MongoProxyClient.ts, src/Common/QueriesClient.ts, src/Common/dataAccess/readDocument.ts, src/Common/dataAccess/updateDocument.ts, src/Contracts/ViewModels.ts, src/Explorer/Controls/Settings/SettingsSubComponents/SubSettingsComponent.tsx, src/Explorer/Controls/Settings/TestUtils.tsx, src/Explorer/Controls/Settings/__snapshots__/SettingsComponent.test.tsx.snap, src/Explorer/OpenActions/OpenActions.tsx, src/Explorer/Tables/TableEntityProcessor.ts, src/Explorer/Tabs/ConflictsTab.ts, src/Explorer/Tabs/DocumentsTab.html, src/Explorer/Tabs/DocumentsTab.ts, src/Explorer/Tabs/MongoDocumentsTab.ts, src/Explorer/Tree/Collection.test.ts, src/Explorer/Tree/Collection.ts, src/Explorer/Tree/ConflictId.ts, src/Explorer/Tree/DocumentId.ts, src/Explorer/Tree/ResourceTokenCollection.ts, src/Utils/QueryUtils.ts
- store partition keys and values as array in `DocumentId`
- add support in documents tab to display multiple partition keys in the grid
- add `x-ms-documentdb-partitionkey` header in the request options when doing a read or update operation on documents with multiple partition key
- **this requires the SDK to upgrade the current version to "2020-07-15"**
- for Mongo, assume the length of partition key array is 1 if it's defined
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1252?feature.someFeatureFlagYouMightNeed=true)
=> Add support for multi-partition key

src/Common/dataAccess/readDocument.ts
If a document has no partition key value defined, use `undefined` instead of `[]`.
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1256?feature.someFeatureFlagYouMightNeed=true)
=> Fix error when reading document with no partition key

src/Explorer/Tree/ResourceTree.tsx
Load sproc, UDF, and triggers when they are expanded
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1267?feature.someFeatureFlagYouMightNeed=true)
=> Fix stored procedures, UDF, and triggers sometimes don't show up in the resource tree after expanding

src/Explorer/Tree/Collection.ts
We removed the "/" prefix for Mongo shard keys in this change: https://github.com/Azure/cosmos-explorer/pull/1252. This has caused some issues because other functions still assume the "/" exists. I am adding the "/" back in this PR and will work on removing it completely in a later PR.
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1269?feature.someFeatureFlagYouMightNeed=true)
=> Fix issue with reading and saving mongo documents with shard key

src/Common/dataAccess/deleteDocument.ts, src/Common/dataAccess/updateDocument.ts
Use undefined as the partition key value when deleting and updating documents
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1274?feature.someFeatureFlagYouMightNeed=true)
=> Use undefined as the partition key value when deleting and updating documents

src/Contracts/DataModels.ts, src/Explorer/Explorer.tsx, src/Phoenix/PhoenixClient.ts
This PR
- Renames Validation error -> phoenix error
- Refactors the allocate container flow in phoenix client to better handle errors which are now all json type
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1272)
=> ValidationErrors renamed to PhoenixErrors

src/Explorer/Notebook/SchemaAnalyzer/SchemaAnalyzer.tsx
This is needed so that we can trigger IcM whenever Schema Analyze fails
=> Log errors by Schema Analyzer

src/Common/Constants.ts, src/Contracts/DataModels.ts, src/Explorer/Explorer.tsx, src/Explorer/Notebook/NotebookContainerClient.ts
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1290)
This PR:
-Updates the phoenix allocate call with poolId as default
=> Update allocate call

package-lock.json, package.json
Upgrade js sdk version to 3.16.2 to include a hotfix
=> Upgrade js sdk version

src/Common/dataAccess/createCollection.ts, src/Common/dataAccess/createDatabase.ts, src/Common/dataAccess/createStoredProcedure.ts, src/Common/dataAccess/createTrigger.ts, src/Common/dataAccess/createUserDefinedFunction.ts, src/Common/dataAccess/deleteCollection.ts, src/Common/dataAccess/deleteDatabase.ts, src/Common/dataAccess/deleteStoredProcedure.ts, src/Common/dataAccess/deleteTrigger.ts, src/Common/dataAccess/deleteUserDefinedFunction.ts, src/Common/dataAccess/readCollectionOffer.ts, src/Common/dataAccess/readCollections.ts, src/Common/dataAccess/readDatabaseOffer.ts, src/Common/dataAccess/readDatabases.ts, src/Common/dataAccess/readStoredProcedures.ts, src/Common/dataAccess/readTriggers.ts, src/Common/dataAccess/readUserDefinedFunctions.ts, src/Common/dataAccess/updateCollection.ts, src/Common/dataAccess/updateOffer.ts, src/Common/dataAccess/updateStoredProcedure.ts, src/Common/dataAccess/updateTrigger.ts, src/Common/dataAccess/updateUserDefinedFunction.ts, src/Explorer/ContextMenuButtonFactory.tsx, src/UserContext.ts
- When enableSDKOperations feature flag is set, show "Delete Database" button for TablesDB
- Delete TablesDB via data plane (JS SDK)
- Replaced `userContext.useSDKOperations` with `userContext.features.enableSDKOperations` flag
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1300?feature.someFeatureFlagYouMightNeed=true)
=> Allow users to delete TablesDB database when enableSDKOperations feature flag is set

src/Explorer/Tabs/QueryTab/QueryTabComponent.tsx
Remove unnecessary null checks when aggregating the query metrics. These checks will cause the final result to be 0 if one of the metric value is 0. The `_normalize` function already handles the case where the value of a metric is null or undefined.
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1302?feature.someFeatureFlagYouMightNeed=true)
=> Fix aggregated query metrics show incorrect number

package-lock.json, package.json
Updating Cosmos DB SDK to 3.16.3 to accommodate hotfix for allowing trailing white space in keys
=> Updating SDK to 3.16.3

package-lock.json, package.json
Reverting cosmos sdk to 3.16.2
=> Reverting cosmos sdk to 3.16.2

src/Explorer/Controls/ThroughputInput/ThroughputInput.tsx, src/Explorer/DataSamples/ContainerSampleGenerator.ts, src/Explorer/Panes/AddCollectionPanel.tsx, src/Explorer/SplashScreen/SplashScreen.tsx, src/Explorer/Tabs/DocumentsTab.ts, src/Explorer/Tabs/Tabs.tsx, src/Explorer/Tree/ResourceTree.tsx, src/Explorer/Tutorials/MongoQuickstartTutorial.tsx, src/Main.tsx, src/hooks/useTabs.ts
- changed the "Launch quickstart" button to open add collection panel with pre-filled values
- made the SampleGenerator work with Mongo API
- changed the autoscale throughput value for SampleDB from 4000 to 1000
- added set of teaching bubbles after the SampleDB is created
- fixed a bug where closing the Connect tab does not automatically activates the Home tab
Figma: https://www.figma.com/file/m6MTakDdn9hhZWmAN9H4mG/COSP-5x5?node-id=1533%3A195809
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1313?feature.someFeatureFlagYouMightNeed=true)
=> Add teaching bubbles for mongo quickstart

src/Utils/EndpointValidation.ts
Add AGC endpoint "https://main.cosmos.ext.azure" to the allowed endpoints list
=> Whitelist AGC endpoint in data explorer

src/Explorer/Menus/CommandBar/CommandBarComponentAdapter.tsx
Hide connect btn and only show when phoenix notebooks or features are used
=> Hide connect btn and only show when phoenix notebooks or features are used

src/Contracts/DataModels.ts, src/Explorer/Explorer.tsx, src/Explorer/Notebook/NotebookContainerClient.ts, src/Phoenix/PhoenixClient.ts
For graphql, we changed the create and reset workspace APIs to return an array of allocated servers instead of just one.
This PR migrates Notebooks also to this new API response.
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1320)
=> Moved notebooks to latest API version

src/Explorer/Explorer.tsx
This PR fixes the issue with Gallery tab loading official samples
=> Gallery loading issue

src/Contracts/ViewModels.ts, src/Explorer/Explorer.tsx, src/Explorer/Menus/CommandBar/CommandBarComponentAdapter.tsx, src/Platform/Hosted/extractFeatures.ts, src/UserContext.ts, src/hooks/useKnockoutExplorer.ts
- set the API type to "Postgres" if `inputs.isPostgresAccount` is true
- remove `enablePGQuickstart` feature flag and replace it by checking if the APIType === "Postgres"
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1323?feature.someFeatureFlagYouMightNeed=true)
=> Properly load a postgres account in data explorer

src/Explorer/Panes/AddCollectionPanel.tsx
This change disables the wildcard index option for collection create, when the account has 16MB document capability enabled.
=> Disable wild card index for Mongo 16MB documents

src/Contracts/ViewModels.ts, src/Explorer/Tabs/PostgresConnectTab.tsx, src/Explorer/Tabs/Tabs.tsx, src/UserContext.ts, src/hooks/useKnockoutExplorer.ts
The connection string tab in data explorer is exactly the same as the connection string blade in the OSS portal:
=> Implement connection string tab for postgres

src/Explorer/Notebook/useNotebook.ts, src/Explorer/Quickstart/QuickstartGuide.tsx, src/Explorer/Tabs/QuickstartTab.tsx, src/Phoenix/PhoenixClient.ts, src/Terminal/JupyterLabAppFactory.ts
When a free tier account is just created, it's possible that the permissions have not been propogated, causing the `getDbAccountAllowedStatus` call to fail. This fix adds a retry logic to the request with a maximum retry count of 10 and a 5 seconds retry interval.
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1342?feature.someFeatureFlagYouMightNeed=true)
=> Add retries when checking if account is allowed to access phoenix

src/Contracts/ViewModels.ts, src/Explorer/SplashScreen/SplashScreen.less, src/Explorer/SplashScreen/SplashScreen.tsx, src/UserContext.ts, src/hooks/useKnockoutExplorer.ts
Hide launch quick start button and postgres teaching bubbles if account is a replica
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1344)
=> Hide launch quick start button and postgres teaching bubbles if account is a replica

src/Contracts/DataModels.ts, src/Contracts/ExplorerContracts.ts, src/Contracts/ViewModels.ts, src/Explorer/Tabs/Tabs.tsx, src/Explorer/Tree/Collection.ts, src/Explorer/Tree/ResourceTree.tsx, src/Explorer/Tree/ResourceTreeAdapter.tsx, src/Utils/APITypeUtils.ts, src/Utils/NetworkUtility.ts, src/hooks/useKnockoutExplorer.ts, src/hooks/useTabs.ts
- implemented an API to check if the user's network settings allow data explorer access
- display a warning banner at the top of the tabs section if the check fails
- added a button in the banner to open the networking blade
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1348?feature.someFeatureFlagYouMightNeed=true)
=> Add check and guidance for networking settings

src/Explorer/Controls/Settings/SettingsSubComponents/SubSettingsComponent.tsx
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1371?feature.someFeatureFlagYouMightNeed=true)
This change addresses a bug where the "Large shard key is enabled" message is being displayed for Mongo API accounts.
=> Display large partition key message for SQL API accounts only.

sampleData/sqlSampleData.json, src/Explorer/Panes/AddCollectionPanel.tsx
This changes replaces the address sample data with adventure works data for SQL and Mongo API. [Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/EDIT_THIS_NUMBER_IN_THE_PR_DESCRIPTION?feature.someFeatureFlagYouMightNeed=true)
=> Update address sample data for SQL and Mongo

less/resourceTree.less, src/Common/Constants.ts, src/Common/dataAccess/readCollections.ts, src/Contracts/DataModels.ts, src/Contracts/ViewModels.ts, src/Explorer/Explorer.tsx, src/Explorer/Panes/SettingsPane/SettingsPane.tsx, src/Explorer/Panes/SettingsPane/__snapshots__/SettingsPane.test.tsx.snap, src/Explorer/Tree/Database.tsx, src/Explorer/Tree/ResourceTree.tsx, src/Shared/StorageUtility.ts
[Preview this branch](https://ms.portal.azure.com/?dataExplorerSource=https%3A%2F%2Fcosmos-explorer-preview.azurewebsites.net%2Fcommit%2F8688fa71ac5947c5b8c5aeb55c0a8b122cb186d2%2Fexplorer.html%3Ffeature.pr%3Dhttps%253A%252F%252Fgithub.com%252FAzure%252Fcosmos-explorer%252Fpull%252F1411%2523users%252Faisayas%252Flazyloading#@microsoft.onmicrosoft.com/resource/subscriptions/b9c77f10-b438-4c32-9819-eef8a654e478/resourceGroups/aisayas/providers/Microsoft.DocumentDb/databaseAccounts/aisayas-gremlin/dataExplorer)
Load containers with a _load more_ button if a database has more than 50 containers. Toggle was also added to allow the user to opt in (or out). 
**Note - Containers are not fetched in alphanumeric order during pagination
=> Lazy loading containers

jest.config.js, src/Explorer/Tabs/MongoShellTab/getMongoShellOrigin.test.ts, src/Explorer/Tabs/MongoShellTab/getMongoShellOrigin.ts, src/Explorer/Tabs/MongoShellTab/getMongoShellUrl.test.ts, src/Explorer/Tabs/MongoShellTab/getMongoShellUrl.ts, src/Platform/Hosted/extractFeatures.ts
- Load Legacy Mongo Shell V2 by default
- Add/Keep feature flags to load from portal BE and V1
- Skip code coverage if skipCodeCoverage environment variable is set to "true"
=> Load Legacy Mongo Shell V2 by default

src/Explorer/QueryCopilot/Popup/DeletePopup.test.tsx, src/Explorer/QueryCopilot/Popup/DeletePopup.tsx, src/Explorer/QueryCopilot/QueryCopilotTab.tsx
- Add toggle ability on query feedback buttons
- Delete or generate new query will also clear the feedback buttons state
[AB#2501546](https://msdata.visualstudio.com/ba574a88-a171-48e0-8fcb-5fef6d23739c/_workitems/edit/2501546)
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1512?feature.someFeatureFlagYouMightNeed=true)
=> [Query Copilot] Add toggle on feedback buttons

src/Explorer/Menus/CommandBar/CommandBarComponentButtonFactory.tsx, src/Explorer/useSelectedNode.ts
- Disable command buttons when query copilot sample container is used
- Open query copilot tab when clicking new query in the sample container only
[AB#2501541](https://msdata.visualstudio.com/ba574a88-a171-48e0-8fcb-5fef6d23739c/_workitems/edit/2501541)
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1514?feature.someFeatureFlagYouMightNeed=true)
=> [Query Copilot] Disable command bar buttons when sample container is used

src/Explorer/ContextMenuButtonFactory.tsx, src/Explorer/Panes/SettingsPane/SettingsPane.tsx, src/Explorer/Panes/SettingsPane/__snapshots__/SettingsPane.test.tsx.snap, src/Explorer/QueryCopilot/Modal/WelcomeModal.tsx, src/Explorer/QueryCopilot/QueryCopilotTab.tsx, src/Explorer/Tree/SampleDataTree.tsx
This PR contains reversing logic for cross partition queries, removing parameter which were previously used in Query Copilot part of the code that opens Query Copilot tab, and also small changes/improvements/bugs in Query Copilot in general.
Related work items:
https://msdata.visualstudio.com/CosmosDB/_workitems/edit/2183598
https://msdata.visualstudio.com/CosmosDB/_workitems/edit/2523302
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1521?feature.someFeatureFlagYouMightNeed=true)
=> Reverse cross partition query behavior in DE Query settings pane

src/Explorer/QueryCopilot/QueryCopilotTab.tsx, src/Explorer/QueryCopilot/QueryCopilotUtilities.ts, src/Explorer/Tabs/DocumentsTab.ts, src/Explorer/Tree/ResourceTokenCollection.ts, src/Explorer/Tree/SampleDataTree.tsx
- add proper onClick function to the items node
- use sample data client to read documents for sample data container
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1528?feature.enablecopilot=true)
=> Fix "items" button in sample data resource tree does not open documents tab

src/Explorer/Panes/CassandraAddCollectionPane/CassandraAddCollectionPane.tsx, test/cassandra/container.spec.ts
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1532?feature.someFeatureFlagYouMightNeed=true)
The text related to the label is not readout by screenreader, when focus moves to the "Enter Tabe Id" input currently. Since, few screenreaders are able to readout limited content, we are not able to associate the label text by 'aria-labelledby' we are adding the corresponding text to aria-label attribute itself which satisfies the requirement to readout the label.
=> Aria label updated with label name of the input element

src/Explorer/Tabs/Tabs.tsx
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1527?feature.someFeatureFlagYouMightNeed=true)
Aria-controls is an attribute that identifies the controlled element from the controlling element. Eg..,. A button is present which opens a tab. Here the button is the controller and the tab is the controlled element. Establishing this relation helps in navigation of the page logically with supported browsers.But in our case, we don't have an id "connect " to use aria-controls. Hence removing the connect that appears in the case of default "Home" tab
https://msdata.visualstudio.com/CosmosDB/_workitems/edit/2236143
=> removing the connect value for ariacontrols variable

src/Explorer/Menus/CommandBar/CommandBarComponentButtonFactory.tsx
This pull request contains fix where it will allow user to create Container or Database even if Sample Database is selected.
Related work items:
[AB#2528027](https://msdata.visualstudio.com/ba574a88-a171-48e0-8fcb-5fef6d23739c/_workitems/edit/2528027)
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1531?feature.someFeatureFlagYouMightNeed=true)
=> [Query Copilot] Not disabling create database/container buttons for Sample Database

src/Explorer/Menus/CommandBar/CommandBarComponentButtonFactory.tsx, src/Explorer/QueryCopilot/QueryCopilotTab.tsx, src/Explorer/Tabs/DocumentsTab.ts
This pull request contains disabling buttons for Query Copilot tab in different occasions or disabling them at all. Also, it includes hiding of Dropdown if the user prompt does not match any record from ether History or Suggested prompts.
Related tasks:
[AB#2530366](https://msdata.visualstudio.com/ba574a88-a171-48e0-8fcb-5fef6d23739c/_workitems/edit/2530366)
[AB#2530294](https://msdata.visualstudio.com/ba574a88-a171-48e0-8fcb-5fef6d23739c/_workitems/edit/2530294)
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1534?feature.someFeatureFlagYouMightNeed=true)
=> [Query Copilot] Dropdown hide and buttons disabled in specific occasions

src/Explorer/Controls/Editor/EditorReact.tsx
This pull request contains fix for a bug that doesn't allow user clicking the Query Results in the SQL/Query Copilot Tab. User would be able to select and copy content of the query results with this fix.
Related task:
[AB#2501400](https://msdata.visualstudio.com/ba574a88-a171-48e0-8fcb-5fef6d23739c/_workitems/edit/2501400)
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1537?feature.someFeatureFlagYouMightNeed=true)
=> Query Results no longer blocked for clicking/copying content

src/Explorer/QueryCopilot/QueryCopilotTab.tsx, src/Explorer/QueryCopilot/SamplePrompts/SamplePrompts.test.tsx
This pull request contains fix when error message bar is hidden or shown based on the outcome of sent requests.
Related tasks:
[AB#2549397](https://msdata.visualstudio.com/ba574a88-a171-48e0-8fcb-5fef6d23739c/_workitems/edit/2549397)
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1542?feature.someFeatureFlagYouMightNeed=true)
=> [Query Copilot] Hide error message bar when request is successful

src/Explorer/SplashScreen/SplashScreen.tsx, src/hooks/useKnockoutExplorer.ts
- After the sample data info fetch is finished, update the feature flag to true or false, thus even if the feature flag is enabled it will not show query more faster with copilot, unless sample data can be reached
[AB#2573352](https://msdata.visualstudio.com/ba574a88-a171-48e0-8fcb-5fef6d23739c/_workitems/edit/2573352)
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1560?feature.someFeatureFlagYouMightNeed=true)
=> [Query Copilot] Update feature flag after sample data connection info fetch

src/Explorer/Tabs/Tabs.tsx
…m unselected tabs while using contrast themes
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1509?feature.someFeatureFlagYouMightNeed=true)
The selected tabs present in " data explorer " are not differentiated from unselected tabs when high contrast themes are applied. A border at the bottom has been added for the tabs to differentiate from the unselected ones.
=> Border at the bottom has been added  for the tabs to differntiate from unselected tabs

less/documentDBFabric.less
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1614?feature.someFeatureFlagYouMightNeed=true)
With my last fix in https://github.com/Azure/cosmos-explorer/pull/1607/commits/c8b533f0aab657b6da47305f70cd8e5ad9939948 for Portal, I broke the active Tab design for Fabric, sorry about that!
Bug:
Fixed:
=> Fix active tabs border on Fabric

src/Explorer/Panes/UploadItemsPane/UploadItemsPane.tsx
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1621?feature.someFeatureFlagYouMightNeed=true)
When uploading json files to a database, longer file names and messages were cut off with no tooltip to show the full file name or message.  This tooltip was added.
=> File Upload Tooltip

package.json
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1624?feature.someFeatureFlagYouMightNeed=true)
This change fixes the issue when running `npm run format` on windows, git then shows 700+ files changed making it impossible to find which file had code that was actually reformatted.
Explanation:
* End of line character(s): traditionally CRLF (carriage return + line feed or '\r\n') in windows, LF ('\n') in linux.
* On windows, the recommended config by git bash is to set: `"autocrlf" = true`. Meaning, git saves files with CRLF, but uploads with LF so that the repository in linux always contains files with LF.
The config is saved during installation here: `C:\Program Files\Git\etc\gitconfig`.
You can override this by doing `git config <your parameter change here>` …
=> Prevent prettier from converting CRLF to LF

src/Explorer/DataSamples/ContainerSampleGenerator.test.ts
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1655?feature.someFeatureFlagYouMightNeed=true)
[This commit](https://github.com/Azure/cosmos-explorer/pull/1313/files) enables sample collection for mongo api.
The test being removed was not working (`await` missing [here](https://github.com/Azure/cosmos-explorer/blob/f36fccd3efe80834a7ac169a498a8bd000875786/src/Explorer/DataSamples/ContainerSampleGenerator.test.ts#L136)) and is incorrect, since we now support sample generation for Mongo API.
=> Remove obsolete unit test

src/Platform/Hosted/Components/ConnectExplorer.tsx, test/sql/resourceToken.spec.ts
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1673?feature.someFeatureFlagYouMightNeed=true)
This change adds a call to the portal backend to determine if an account has been restricted from connection string based login.
If account has been restricted, user is informed via an error tooltip.
=> Check for accounts that are restricted from connection string login.

src/Explorer/Panes/Tables/EditTableEntityPanel.tsx, src/Explorer/Panes/Tables/__snapshots__/EditTableEntityPanel.test.tsx.snap, src/Explorer/Tables/TableDataClient.ts
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1658?feature.someFeatureFlagYouMightNeed=true)
Data Explorer was not handling NULL values properly.
Issue 1: If a row had fields which where NULL, when opening the row to edit, the fields that were NULL did not show so the user could insert values in those fields. 
Issue 2: When attempting to insert a new row, when trying to leave non-string data types as empty, errors are thrown from backend but not caught and displayed properly in DE.
RESOLUTION: The backend requires a valid value for all types so it was advised to display a Warning on the edit panel that null values cannot be edited.
=> Explorer null handling

src/Terminal/JupyterLabAppFactory.ts, src/Terminal/index.ts
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1675)
On vCore Mongo, if the user enters an incorrect password, the whole terminal window closes. This adds a check for a specific message in the stdout which indicates the shell didn't accept the password and in that case recreates the terminal.
One of two things could happen in the future:
1. Once Phoenix adds the feature to fully login without the need for user input, this change could be undone.
2. If this is useful for other scenarios, other checks could be created.
=> Adds restarting vcore mongo shell if user enters wrong password

src/Platform/Hosted/Components/ConnectExplorer.tsx, src/Platform/Hosted/ConnectScreen.less
This change comes on request from Walmart to direct users to the aad redirect URL if they are blocked.
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1683?feature.someFeatureFlagYouMightNeed=true)
=> Add directions to use AAD login if account blocked from connection string login.

src/Explorer/Explorer.tsx, src/Explorer/Panes/AddCollectionPanel.tsx, src/hooks/useKnockoutExplorer.ts
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1692?feature.someFeatureFlagYouMightNeed=true)
Remove the constraint that only will show the survey after the create a collection process (see note for b).  Show the NPS survey when user opens Data Explorer.   Same as PG does.
2.	Change the % of user's we display to.
a.	Account older than 90 days: from 25% to 33%
b.	Account between 3- 90 days: from 10% to 100%   
c.	Try Cosmos DB Account Day 1: from 25% to 100%
3.	User may only see survey 1 time every 90 days.
=> Increase NPS sample size and remove constraints

src/Common/CosmosClient.ts
During previous region outages, DE was unable to view account data.  
According to [this doc](https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/troubleshoot-sdk-availability), setting enableEndpointDiscovery to false can compromise the SDK's ability to fail over if a region becomes unavailable.
Letting this bake in MPAC to see if there are any issues not encountered during validation.
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1694)
=> Enabling enableEndpointDiscovery to test DE Region Outage Resiliency

src/Explorer/Tabs/Tabs.tsx
…ing continuosly
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1682?feature.someFeatureFlagYouMightNeed=true)
=> Bug 2748412: Focus order is not logical after expanding/collapse of "Collapse" control under "Data Explorer" screen.

src/Explorer/Panes/CassandraAddCollectionPane/CassandraAddCollectionPane.tsx
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1661?feature.someFeatureFlagYouMightNeed=true)
Provisioned thoughput checkbox present in the "New keySpace" dialog is not aligned and the contents of the checkbox is scattered improperly.
=> Bug 2748824:"Provision dedicated throughput for this table "check box is misaligned in normal mode (100%)

src/Explorer/Tabs/QueryTab/QueryResultSection.tsx
=> Bug 2724821: Heading hierarchy is not defined sequentially on the "Data explorer" page.

src/Common/CosmosClient.ts
Reverting enabling endpoint discovery until next CCOA since it didn't have a chance to bake in MPAC during the current CCOA.
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1698?feature.someFeatureFlagYouMightNeed=true)
=> Revert Enabling Endpoint Discovery 

src/Common/CosmosClient.ts
Enabling endpoint discovery in MPAC to test region outage in a non-development environment.
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1711?feature.someFeatureFlagYouMightNeed=true)
=> Enabling endpoint discovery to test region failure

.github/workflows/ci.yml
This change fixes the break in Nuget Publish MPAC task during CI.
=> Fix the Nuget Publish MPAC action in CI.

src/Explorer/Controls/ThroughputInput/ThroughputInput.tsx
=> Bug 2748803: Spin edit field present within the "New key space" screen is not associated with its label.

src/Contracts/ViewModels.ts, src/Explorer/Panes/AddDatabasePanel/AddDatabasePanel.tsx, src/Explorer/Panes/CassandraAddCollectionPane/CassandraAddCollectionPane.tsx, src/Shared/Constants.ts, src/UserContext.ts, src/hooks/useKnockoutExplorer.ts, test/testExplorer/TestExplorer.ts
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1741?feature.someFeatureFlagYouMightNeed=true)
This change removes the addCollectionDefaultFlight parameter and associated references, as it is no longer being used.
=> Remove references to addCollectionDefaultFlight parameter.

src/Explorer/Menus/CommandBar/CommandBarComponentButtonFactory.tsx, src/Explorer/Tabs/DocumentsTab.ts, src/Explorer/Tabs/QueryTab/QueryTabComponent.tsx, src/Platform/Fabric/FabricUtil.ts
* The `userContext.hasWriteAccess` flag is currently only used to show Write vs Read-Only cosmos db account keys in the Connect tab. We extend the meaning of this flag to mean Data Explorer is in write vs read-only mode and hide buttons not relevant to read-only.
* Hide "New Items", "Update" in document tab when in read-only
* Fabric: 
* Hide Open/Save Query, because queries are saved in another (not mounted) database
* Set Data Explorer as read-only for now.
=> Hide buttons from command bar for Fabric or when no write access

src/Contracts/ExplorerContracts.ts
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1743?feature.someFeatureFlagYouMightNeed=true)
Having "Contracts/MessageTypes" brakes the Frontend code that pulls this. The folder name changes to DataExplorerContracts in the FrontEnd code resulting in the build not find the import.
P.S. - I don't like where prettier moved the import :(
=> Correcting import for MessageTypes

src/Explorer/Controls/Settings/SettingsSubComponents/ThroughputInputComponents/ThroughputInputAutoPilotV3Component.tsx, src/Explorer/Controls/Settings/SettingsSubComponents/ThroughputInputComponents/__snapshots__/ThroughputInputAutoPilotV3Component.test.tsx.snap
When viewing Scale & Settings tab on db/container, when set to Autoscale, the min & max values are correct. But when switching to Manual the cost estimate is using the same base RU value as autoscale ($0.00012) when it should be using its own base value ($0.00008).
=> Fixing manual throughput cost estimate

src/Explorer/Tabs/TerminalTab.tsx
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1747)
Currently the network warning that displays on Postgres' and vCore Mongo's quickstarts only say PostgreSQL:
Fixing this so it now shows the correct API type for the account:
=> Fixing terminal tab to display correct API type for network warning

less/documentDBFabric.less
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1756?feature.someFeatureFlagYouMightNeed=true)
Small updates from Design:
* no grey backgrounds
* no margin between toolbar, content and status
=> Update layout and colors for Fabric per req from Design

src/Explorer/Menus/CommandBar/CommandBarComponentButtonFactory.tsx, src/Explorer/Tabs/DocumentsTab.ts
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1757?feature.someFeatureFlagYouMightNeed=true)
Also improve the logic for hiding edit buttons in Documents tab.
=> Don't show Settings buttons for Fabric readonly

src/Explorer/Explorer.tsx, src/Explorer/Menus/CommandBar/CommandBarComponentButtonFactory.tsx
Reverts Azure/cosmos-explorer#1736 - This commit will add the CESCVA feedback button back.
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1759?feature.someFeatureFlagYouMightNeed=true)
=> "CESCVA feedback button"

less/Common/Constants.less, src/Explorer/Menus/CommandBar/CommandBarUtil.tsx, src/Explorer/Tabs/Tabs.tsx
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1761?feature.someFeatureFlagYouMightNeed=true)
* [Hide the RU Threshold Message in Fabric](https://github.com/Azure/cosmos-explorer/commit/b8923624a26bb1625f3879919b21f46ed13893f1) 
* Fabric is RO and the Settings button is hidden, hence the message doesn't make sense. If customers hit the limits they can go to Portal and change the settings there.
* [Change the toolbar font size and icon color in Fabric](https://github.com/Azure/cosmos-explorer/commit/5de3bc643939b0566e320d35b0bc5c79c00c2e4d)
* Blue Toolbar icons and 12>14 font size to align with Fabric ribbon
=> Small fixes for Fabric PuPr

configs/mpac.json, src/Contracts/ViewModels.ts, src/Explorer/Panes/__snapshots__/AddCollectionPanel.test.tsx.snap, src/Explorer/QueryCopilot/QueryCopilotPromptbar.tsx, src/UserContext.ts, src/hooks/useKnockoutExplorer.ts
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1745?feature.someFeatureFlagYouMightNeed=true)
Adds feedback policies settings into the user context. Will only work with portal.
Removes teaching bubbles and modals
updated staging endpoint for Phoenix to Prod
Manually tested locally by changing the policy settings in tenant admin settings.
=> add feedback policies integration with copilot

src/Common/Constants.ts, src/ConfigContext.ts, src/Explorer/Tables/TableDataClient.ts, src/Utils/EndpointUtils.ts
This change adds support for the new backend service - CassandraProxy in DE to call the Proxy APIs from the client.
=> Add CassandraProxy support in DE

src/Common/CosmosClient.ts
Note: another option is to comment the entire switch and simply return the resource token, but I felt that keeping the segregation logic alive as much as possible would make it easier if we had to re-enable the code that is commented out.
=> Turn off fetching authorization token for Fabric

src/Explorer/Menus/CommandBar/CommandBarComponentButtonFactory.tsx
as the whole Home tab feature is not supported there.
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1774?feature.someFeatureFlagYouMightNeed=true)
=> Don't show the new Home button in Fabric

src/Contracts/FabricMessagesContract.ts, src/UserContext.ts, src/hooks/useKnockoutExplorer.ts
There is a rendering issue where the documents table doesn't resize properly if explorer is loaded in the beackground (invisible). To workaround this, track DE visibility from Fabric RPC and open the first container only once DE becomes visible. If DE has been already shown, open the container right away.
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1771?feature.someFeatureFlagYouMightNeed=true)
=> Fix initial container loading in Fabric

src/Explorer/OpenActions/OpenActions.tsx
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1780?feature.someFeatureFlagYouMightNeed=true)
**Description**
The open database or collections action will not work if the action is fired too early, before databases are loaded.
OR no collections are loaded.  This is only apparent when the actions are triggered from portal such as ExplorerContracts.ActionContracts.OpenCollectionTab
e.g clicking on the collection row on the overview blade
So adding a subscription listener to the list of databases that calls subscription listener to collections.
**How Has This Been Tested?**
By clicking on the row of the collection item from overview blade, should open data explorer then the items tab
=> fix opening collections

src/Contracts/MessageTypes.ts, src/Explorer/Tabs/QueryTab/QueryTab.tsx
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1783?feature.someFeatureFlagYouMightNeed=true)
Description
Overview and DataExplorer blade will keep the current query tab open state in portal to communicate it to the Azure Copilot.
How Has This Been Tested?
By updating the DE contracts manually locally and testing it in portal
=> Add activate/close tab contracts and add to queryTab

less/documentDB.less
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1784?feature.someFeatureFlagYouMightNeed=true)
The Monaco Editor we're using for editing queries has a built-in "Quick Actions" panel, opened with the F1 key, that provides access to keyboard shortcuts and editor actions like commenting/uncommenting lines, etc. Unfortunately, some of our top-level CSS styles are clobbering styles the editor provides which makes that quick action panel look bad:
This PR reasserts the styles that Monaco uses with a more specific selector so that they override our global `label` and `.highlight` styles. The result is that the quick input panel now looks the same as in the [Monaco Editor Playground](https://microsoft.github.io/monaco-editor/playground.html?source=v0.47.0):
This fixes …
=> [Bug #3061738] Unclobber some Monaco styles we clobber

src/Main.tsx, src/ReactDevTools.ts
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1788?feature.someFeatureFlagYouMightNeed=true)
I was going to use the [React Dev Tools extension](https://react.dev/learn/react-developer-tools) to get some information about the Components hierarchy in the explorer. Unfortunately, since we host the explorer inside an iframe, it doesn't Just Work ™️ . To make it work, [we need to inject a little code to copy the `__REACT_DEVTOOLS_GLOBAL_HOOK__ ` value from the parent frame to the child frame](https://github.com/facebook/react-devtools/issues/76#issuecomment-128091900). This has to be done _before_ React is loaded, so it takes a little bit of trickery.
I noticed that this code already exists in `ReactDevTools.ts`, but it isn't imported anywhere. So, I've added it …
=> add support for react dev tools to the editor

src/Explorer/Controls/Editor/EditorReact.tsx, src/Explorer/Tabs/QueryTab/QueryTabComponent.tsx
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1785?feature.someFeatureFlagYouMightNeed=true)
Undo/redo is another feature that's built in to the Monaco editor so we _should_ be getting it for free. However, we aren't, so something must be going wrong. After a bunch of digging, the root cause of the problem is the way we're tracking the content of the editor itself. We hook a 'content changed' event on the editor, then use that to update the internal state tracking the content of the editor. When we re-render, we use that internal state to set the content of the editor. That causes a few problems:
1. Setting the content using `setValue` will destroy the undo/redo stack.
2. Unnecessarily setting the content of the editor to it's existing content will create …
=> [Task #3061771] Correct render order issues on undo

src/Explorer/Controls/Editor/EditorReact.tsx
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1799?feature.someFeatureFlagYouMightNeed=true)
This is regarding the ICM(s) where query results are not updating after the initial query result showing and they run different subsequent query.
The executeEdits on the editor is being executed but for some reason, editor's internal state is not showing up correctly in the readonly monaco editor that we use in the query results panel below, until we manually re-render like going to the Query Stats tab and coming back.
So this is one way of fixing I think just to set the editor value directly and forcing rerender if it's readonly.
=> set the value in the editor for results

src/Explorer/Tables/TableDataClient.ts
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1790?feature.someFeatureFlagYouMightNeed=true)
Currently errors for Cassandra DBs are being displayed as `undefined`. This is because the errors aren't being stored in `error.message` but `error.responseJSON.message`
Current add row error:
Current create table error:
=> Cassandra API create table error messages swallowed by the Portal and shown as "undefined".

src/Explorer/Panes/CassandraAddCollectionPane/CassandraAddCollectionPane.tsx
Added hyphen '-' as a prohibited character in the tooltip for a new Cassandra Keyspace name id. This is to prevent users from accidentally trying to add it to a name as it is not accepted within CQL.
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1800?feature.someFeatureFlagYouMightNeed=true)
=> Added hyphen to prohibited characters in Cassandra keyspace name title

src/Explorer/Panes/Tables/AddTableEntityPanel.tsx
Moving the CreateDocument call inside the Try statement allows the code to exit on error and eventually set setIsExecuting(false). With it being outside, the Try statement is never seen.
The only other way to prevent this would be to remove setIsExecuting(true) on line 125, which would defeat the purpose of the executing visuals while an operation is in progress. 
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1801?feature.someFeatureFlagYouMightNeed=true)
=> Cassandra "Add Row" error hangs on isExecuting

package-lock.json, package.json, src/Explorer/Controls/CommandButton/CommandButtonComponent.tsx, src/Explorer/Menus/CommandBar/CommandBarComponentAdapter.tsx, src/Explorer/Menus/CommandBar/CommandBarComponentButtonFactory.tsx, src/Explorer/Menus/CommandBar/CommandBarUtil.tsx, src/Explorer/Tabs/DocumentsTab.ts, src/Explorer/Tabs/QueryTab/QueryTabComponent.tsx, src/Explorer/Tabs/StoredProcedureTab/StoredProcedureTabComponent.tsx, src/Explorer/Tabs/TriggerTabContent.tsx, src/Explorer/Tabs/UserDefinedFunctionTabContent.tsx, src/KeyboardShortcuts.tsx, src/Main.tsx
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1789?feature.someFeatureFlagYouMightNeed=true)
**This PR introduces a new dependency on `tinykeys`** I'm not 100% clear on what process, if any, is needed for that but I'm happy to follow whatever is needed.
This PR adds Keyboard Shortcuts by allowing Command Bar Buttons to specify a keyboard shortcut that should be used to activate the command. Upon pressing the keyboard shortcut, the existing `onCommandClick` handler will be executed. The following shortcuts are bound:
| Shortcut | Context | Action |
| - | - | - |
| `Ctrl+J`/`Cmd+J` [^1] | A collection is selected | Open a new Query Tab for the selected collection |
| `Shift+Enter` | A query tab is active | Execute the query (or the selection, if there is one) …
=> [Task 3061766] Global Keyboard Shortcuts, implemented through the Command Bar

src/Explorer/Tabs/Tabs.tsx, src/Explorer/Tabs/TriggerTabContent.tsx
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1804?feature.someFeatureFlagYouMightNeed=true)
I noticed two bugs related to the command bar while working on some keyboard shortcuts:
1. If you have a Trigger Tab open, it takes over the command bar entries, even if it's not currently the active tab. See this video for an example:
https://github.com/Azure/cosmos-explorer/assets/7574/cb2cbf2c-16e7-4c28-8248-d323edd31fd4
2. React tabs have no context buttons. However, nothing clears the button state when you activate a React tab, so the command bar is still showing the buttons for the previously-selected tab:
https://github.com/Azure/cosmos-explorer/assets/7574/9296d35a-04f8-4554-bfba-ab9397a255a1
This PR fixes both issues, so that the command bar stays …
=> Fix issues with the command bar when switching through React and Trigger tabs

src/Explorer/Menus/CommandBar/CommandBarComponentAdapter.tsx, src/Explorer/Menus/CommandBar/CommandBarComponentButtonFactory.tsx, src/Explorer/Tabs/DocumentsTab.ts, src/Explorer/Tabs/QueryTab/QueryTabComponent.tsx, src/Explorer/Tabs/StoredProcedureTab/StoredProcedureTabComponent.tsx, src/Explorer/Tabs/TriggerTabContent.tsx, src/Explorer/Tabs/UserDefinedFunctionTabContent.tsx, src/KeyboardShortcuts.tsx
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1805?feature.someFeatureFlagYouMightNeed=true)
Additional shortcuts, as part of [Task 3061766](https://dev.azure.com/msdata/CosmosDB/_workitems/edit/3061766/). This are all still implemented through the Command Bar and represent the bulk of the remaining keyboard shortcuts. I'll have a separate follow-up PR to add some tab-management shortcuts that should finish up our keyboard shortcuts.
New Shortcuts in this PR:
| Shortcut | Context | Action |
| - | - | - |
| `Alt+N Q` | A container is selected | Open a new Query tab. This is the same as `Ctrl+J` from the previous PR, but for consistency with other "New X" shortcuts below, I added it as another option |
| `Alt+N P` | A container is selected | Opens a New Stored …
=> [Task 3061766] Additional Keyboard Shortcuts

src/Explorer/Menus/CommandBar/CommandBarComponentAdapter.tsx, src/Explorer/Tabs/Tabs.tsx, src/KeyboardShortcuts.tsx, src/hooks/useTabs.ts
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1808?feature.someFeatureFlagYouMightNeed=true)
*Draft PR for now, since this will likely conflict with https://github.com/Azure/cosmos-explorer/pull/1805 and I want to resolve those conflicts by merging the other PR first and rebasing this one*
This adds a few new Keyboard Shortcuts for Tab Managment and Navigation:
| Shortcut | Action |
| - | - |
| `Ctrl+Alt+[`/`Command+Alt+[` [^1] | Switch to the tab on the left |
| `Ctrl+Alt+]`/`Command+Alt+]` [^1] | Switch to the tab on the right |
| `Ctrl+Alt+W`/`Command+Alt+W` [^2] | Close the current tab |
**This does not include "Reopen Last Closed Tab"**. Implementing that is a significant increase in complexity, so I think we should track it as separate from the main …
=> [Task 3071878] Tab Navigation Keyboard Shortcuts

src/KeyboardShortcuts.tsx
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1814?feature.someFeatureFlagYouMightNeed=true)
@sevoku pointed out a few of our keybinds that aren't as convenient on non-US keyboards. This PR updates the tab navigation shortcuts to add bindings, based off of Visual Studio's bindings, that are more convenient on non-US keyboards.
=> add more intl-friendly tab nav shortcuts

src/Explorer/Tabs/DocumentsTab.ts
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1815?feature.someFeatureFlagYouMightNeed=true)
This fixes some user feedback that it's difficult to create a new document that includes a value for the partition key. I noticed this myself, it's easy to miss when hand-creating documents and you may need to look up what the partition key is. This PR changes the template we use when creating a new document to include all partition keys associated with the container.
If there's a simple partition key, it gets added to the document:
If there are multiple (hierarchical) partition keys, they each get added:
Finally, if the partition key is a nested property, we create nested objects as needed to get to the path for the partition key:
If the user wants to omit one or …
=> initialize new documents with their partition key

src/Explorer/Tabs/DocumentsTabV2/DocumentsTabV2.tsx
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1831?feature.someFeatureFlagYouMightNeed=true)
**Note:** This PR isn't targeting `master`, it's targeting the branch for #1770 . Merging it will just squash these commits into a new commit on that branch.
I'm opening this primarily just so @languy can review the adjustments I'm proposing to his existing branch, rather than me just adding commits to it :). All are welcome to take a look and provide feedback though.
This updates #1770 with a few changes to fix up the keyboard shortcuts on the Items tab. A few elements:
1. I wired up the `onKeyDown` for the filter input to the `onFilterKeyDown` callback that was ported over so it now works.
2. I had to implement the keyboard focus adjustments from the existing tab …
=> Port item editor shortcuts to improved Items tab branch

src/Explorer/SplashScreen/SplashScreen.tsx
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1836?feature.someFeatureFlagYouMightNeed=true)
This just adds a link to the new keyboard shortcuts doc to the Home tab. The link appears no matter what API you're connected to:
=> add link to keyboard shortcuts doc to home tab

src/Explorer/Controls/Settings/SettingsUtils.tsx, src/Explorer/Controls/Settings/__snapshots__/SettingsComponent.test.tsx.snap
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1842?feature.someFeatureFlagYouMightNeed=true)
This change removes the (preview) label from the Computed Properties tab in Container settings.
=> Remove preview label from Computed Properties.

src/Common/Constants.ts, src/Contracts/DataModels.ts, src/Utils/CapabilityUtils.ts
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1826?feature.someFeatureFlagYouMightNeed=true)
Description
with a breaking change in RP for api version 2024-05-15-preview, contracts need to be updated in the portal.
Adding capacityMode property in database account resource where the account capacitymode is defined rather than in the capabilities.
Currently standalone DE is using fixed 2024-02-15-preview version,
the problem is when in-portal DE loads the databaseaccount from the portal with the latest API and passed into the DE, which breaks the contract for serverless accounts. 
How Has This Been Tested?
Tested locally with sideloaded portal where the databaseaccount is fetched from 2024-05-15-preview API
=> add capacityMode

src/Explorer/Tabs/DocumentsTabV2/DocumentsTabV2.tsx
Both the Refresh button and Load More button use `loadNextPage`. The only difference is the continuation token which must be reset for Refresh.
=> Fix Refresh button behaving like Load More bug

src/Explorer/Tabs/DocumentsTabV2/DocumentsTabV2.tsx
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1852)
* Open Mongo RU account, open database, open collection, click on "Items"
* create new document "aaa". Save.
* refresh collection (e.g. reload the page and re-open collection Items)
* create more documents "bbb" and "ccc".
* Select and delete just "bbb"
Only "aaa" will show up. All the newly created documents don't appear on the list. Refreshing the collection will show them.
Unlike NoSql, the remote call to create a new mongo document does not return an object with an `rid` field. The `rid` field is present when listing documents from a collection.
The delete documents logic that removed the deleted documents from the current list was based on this `rid` field and therefore did not show any of the newly …
=> Fix delete newly created mongo documents bug

src/Explorer/Tabs/DocumentsTabV2/DocumentsTabV2.tsx, src/Explorer/Tabs/DocumentsTabV2/DocumentsTableComponent.test.tsx, src/Explorer/Tabs/DocumentsTabV2/DocumentsTableComponent.tsx, src/Explorer/Tabs/DocumentsTabV2/__snapshots__/DocumentsTabV2.test.tsx.snap, src/Explorer/Tabs/DocumentsTabV2/__snapshots__/DocumentsTableComponent.test.tsx.snap
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1855)
Currently, Data Explorer is read-only for Fabric. Selection of documents in the table to delete them doesn't make sense, so hide the checkbox column.
=> Disable table selection for Fabric/read-only

src/Explorer/Controls/ThroughputInput/ThroughputInput.tsx, src/Explorer/Controls/ThroughputInput/__snapshots__/ThroughputInput.test.tsx.snap, src/Explorer/Panes/CassandraAddCollectionPane/CassandraAddCollectionPane.tsx
Description: The luminosity ratio of links juxtaposed with surrounding text within the 'Add Table' pane fell below the recommended 3:1 ratio. To remedy this, we've implemented a subtle yet effective visual enhancement by underlining the links. This adjustment ensures improved accessibility and readability, aligning with best practices for user interface design.
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1840?feature.someFeatureFlagYouMightNeed=true)
=> [Visual Requirement - Azure Cosmos DB - Add Table]: Luminosity ratio of links with surrounding text is less than required 3:1 under 'Add Table' pane.

src/Explorer/Tabs/Tabs.tsx
This PR addresses an accessibility issue where low vision users and individuals sensitive to colors may encounter difficulty in recognizing controls and differentiating between surrounding text and links if the luminosity ratio is less than 3:1. To enhance accessibility and improve usability for these users, we have implemented underlining for links, providing a visual cue that enhances link visibility and ensures better differentiation from surrounding text.
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1847?feature.someFeatureFlagYouMightNeed=true)
=> Luminosity ratio of 'Learn More' link with surrounding text is less than required 3:1 under 'Data Explorer' pane.  

src/Explorer/Controls/CommandButton/CommandButtonComponent.tsx, src/Explorer/Menus/CommandBar/CommandBarUtil.tsx, src/Explorer/Panes/SettingsPane/SettingsPane.tsx, src/Explorer/Panes/SettingsPane/__snapshots__/SettingsPane.test.tsx.snap, src/Explorer/Tabs/QueryTab/QueryTabComponent.tsx, src/Shared/StorageUtility.ts
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1833?feature.someFeatureFlagYouMightNeed=true)
This PR adds a new dropdown to the Query Editor Command Bar:
The options in this menu allow you to toggle between Vertical (editor and results view are stacked vertically; matches the current view) or Horizontal (editor and results view are stacked horizontally, a new layout made available in this PR):
https://github.com/Azure/cosmos-explorer/assets/7574/90848113-bb92-4b83-a877-49ed8ace3fa5
The default layout is Vertical, matching the current view. However, this too can be changed using a setting in the Settings pane:
Changing this option will affect the starting view for _all future Query Editor panels_ opened on that Browser (the setting is stored in …
=> Allow query result view to be toggled from command bar

src/Explorer/Controls/TreeComponent/TreeNodeComponent.test.tsx, src/Explorer/Controls/TreeComponent/TreeNodeComponent.tsx, src/Explorer/Controls/TreeComponent/__snapshots__/TreeNodeComponent.test.tsx.snap
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1862?feature.someFeatureFlagYouMightNeed=true)
This fixes a small rendering bug in the new resource tree, that I noticed while investigating #1861 . When merging the Fabric resource tree, I made a seemingly benign refactoring. I changed the definition of the `itemType` prop on `TreeItem` from this:
https://github.com/Azure/cosmos-explorer/blob/cebf044803e58a56710adbecaf1bcf05587b8627/src/Explorer/Controls/TreeComponent2/TreeNode2Component.tsx#L100-L102
To this:
```
const isBranch = node.children?.length > 0;
<TreeItem
value={treeNodeId}
itemType={isBranch ? "branch" : "leaf"}
```
There's a subtle difference there! The old logic considered an empty, but non-`undefined`, `children` array as indicating a branch …
=> show an expand icon for nodes with non-null children array

src/Explorer/Controls/TreeComponent/TreeNodeComponent.tsx, src/Explorer/Controls/TreeComponent/__snapshots__/TreeNodeComponent.test.tsx.snap, src/Explorer/Tree/ResourceTree.tsx
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1861?feature.someFeatureFlagYouMightNeed=true)
This fixes an issue discovered after deploying the new resource tree (#1841) to MPAC. The tree nodes were set to `height: 100%`, and the containing Fluent Provider was set to `overflow: hidden`. A FluentUI Tree is a nested set of `Tree`s containing `TreeItem`s which contain `Tree`s containing `TreeItem`s, etc. Setting a `TreeItem` to `height: 100%` forced them to expand to fit all their children. Removing this avoids the overlap. However, because the containing Fluent Provider is `overflow: hidden`, doing that means overflow off the bottom is truncated, so we just need to switch the container to `overflow: auto` to get scrollbars back.
Here's the _broken_ behavior in …
=> stop tree nodes from expanding to full height, causing overlap

src/Explorer/Tabs/DocumentsTabV2/DocumentsTabV2.tsx, src/Explorer/Tabs/DocumentsTabV2/DocumentsTableComponent.tsx
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1864)
This change addresses 2 issues, but also cleans up some other related problems with the current implementation:
* When filter is applied, the list updates and its first document is selected, but on the right pane, it still shows the old document instead of the newly selected document.
* When filter is applied and there are multiple documents, one can click on a document to load it on the right pane. But when the result is only one document, clicking on it doesn't update the right pane.
Here are the significant changes:
* The behavior for automatically clicking on 1st document to show on the right pane is now implemented on `DocumentsTabV2` and no longer driven by `DocumentsTableComponent`. This simplifies …
=> Fix click-to-show document bug

less/documentDB.less
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1867)
This change removes the extra vertical scrollbar caused by the top default limit RU message (or any other message that can appear at the top).
It becomes problematic when the current tab contains a vertical scrollbar on its own.
With this change, the tab container adapts its size to the content with flex. Scrollbar will appear only if the content cannot fit inside the container height. For example here on laptop screen:
=> Remove unnecessary vertical scrollbar on tabs container

src/ConfigContext.ts, test/README.md
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1869?feature.someFeatureFlagYouMightNeed=true)
This change configures dev/test execution to use the MPAC instances of the new backend services instead of Prod.
It also adds some more details to the README for running E2E tests locally.
=> Minor dev/test changes

src/Common/Constants.ts, src/Platform/Hosted/Components/ConnectExplorer.tsx, src/Utils/EndpointUtils.ts
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1868?feature.someFeatureFlagYouMightNeed=true)
This change enables the accountrestrictions API (used for checking whether connection string login is disabled) in the new backend for MPAC environment.
Tested locally against new backend.
=> Switch accountrestrictions call to use new backend in MPAC.

src/Explorer/Panes/AddCollectionPanel.tsx, src/Explorer/Panes/ChangePartitionKeyPane/ChangePartitionKeyPane.tsx, src/Explorer/Panes/__snapshots__/AddCollectionPanel.test.tsx.snap
This PR addresses an issue where unwanted ARIA attributes were present for an element's role in the 'New Container' section under 'Programmatic Access' of Azure Cosmos DB Data Explorer. The unnecessary aria-label has been removed to ensure compliance with accessibility standards and to improve the overall accessibility of the feature.
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1846?feature.someFeatureFlagYouMightNeed=true)
=> Ensures ARIA attributes are allowed for an element's role.

src/Explorer/Tables/TableDataClient.ts
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1879)
Currently, Data Explorer Cassandra experience does not handle row deletion when a table has multiple partition keys. More details can be found in this CRI. https://portal.microsofticm.com/imp/v5/incidents/details/514315661/summary
=> Cassandra: Delete a row for a table that has multiple partition keys

src/Explorer/Tabs/DocumentsTabV2/DocumentsTabV2.test.tsx, src/Explorer/Tabs/DocumentsTabV2/DocumentsTabV2.tsx
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1880)
Temporary workaround for a Cosmos DB JS SDK bug. For the affected legacy containers, in the DocumentsTab:
* disable multiple document selection
* call the single document delete API (which works. Since we disabled multiple selection, only document is selected at a time and can therefore be deleted)
This is only problematic with non partitioned collection and doing delete operation with bulk operation API from JS SDK. https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/migrate-containers-partitioned-to-nonpartitioned?tabs=dotnetv3 When partitionKeyDefinition.systemKey === true Backend expects [] as partitionKey but bulk delete operation through SDK sends {[]} value to the backend as a request.
We will …
=> Temporarily disable bulk Delete for old non-partitioned NoSQL containers 

src/hooks/useDatabaseAccounts.tsx, src/hooks/useSubscriptions.tsx
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1877?feature.someFeatureFlagYouMightNeed=true)
To get around error from Azure Graph
{
"error": {
"code": "BadRequest",
"message": "Please provide below info when asking for support: timestamp = 2024-06-14T17:30:09.6771530Z, correlationId = 81fdb7d2-3833-49a3-9cb0-b9421e6a0430.",
"details": [
{
"code": "ResponsePayloadTooLarge",
"message": "Response payload size is 29972004, and has exceeded the limit of 16777216. Please consider querying less data at a time and make paginated call if needed."
}
]
}
Making subscriptions and databaseaccounts RP call paginated.
=> pagination loading of subscription and databaseaccounts

src/Explorer/Tabs/MongoShellTab/MongoShellTabComponent.tsx
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1883)
After some refactoring in Mongo Proxy, a bug was introduced which blocked users from using Legacy Mongo Shell. Originally, the .NET driver's MongoClient was created differently via LMS vs normal Mongo operations. After some refactoring this logic was combined and the connection string parsing in the backend disagreed with the endpoint passed in from Legacy Mongo Shell frontend.
=> Fix legacy mongo shell regression

less/documentDB.less
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1911)
Here is an example where the filter is too wide and the `tabsManagerContainer` div width grows beyond it's parent.
With this change:
Underneath the command bar are two flex items: the resource tree and the `tabsManagerContainer`. The problem is that by default, flex items won’t shrink below their minimum content size. Setting [`min-width:0` or `overflow:hidden`](https://stackoverflow.com/a/36247448) solves this.
=> Prevent tabsManagerContainer width to grow beyond parent's width

src/Common/dataAccess/createDatabase.ts
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1924)
We got an [ICM ](https://portal.microsofticm.com/imp/v5/incidents/details/523269465/summary) where connectionstring users couldn't create collections for the mongo serverless accounts. After this was resolved via backend changes, they raised to our attention that they were not able to create a database when using connection string. This fix addresses that.
=> Allow connection string users to add database to their Mongo serverless account

src/Explorer/Sidebar.tsx
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1926)
In some cases, the "Create Container" button is not present, so the 2nd element (resource tree) incorrectly takes the size of the button.
The `makestyles()` method seems to create styles statically (I couldn't pass an argument to conditionally create a style for each option).
So this fix overrides the css `gridTemplateRows` property at runtime based on whether the "Create Container" button is displayed.
=> Fix resource tree styling

src/Explorer/Quickstart/QuickstartCarousel.tsx
Added heading level one to 'Welcome! What is Cosmos DB?' for programmatically defined heading.
This change ensures that the heading 'Welcome! What is Cosmos DB?' is programmatically defined at heading level one, addressing the need for consistency and clarity in our documentation structure.
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1882?feature.someFeatureFlagYouMightNeed=true)
=> [Programmatic Access-Try Cosmos DB-Welcome! What is Cosmos DB?]: 'Welcome! What is Cosmos DB?' is not defined programmatically as heading.

src/Explorer/Tabs/QueryTab/QueryTabComponent.tsx
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1896?feature.someFeatureFlagYouMightNeed=true)
When I rolled out the query results view vertical/horizontal toggle (https://github.com/Azure/cosmos-explorer/pull/1833) I used Vertical/Horizontal to refer to the stacking direction of the panes (Vertical -> Top to Bottom, Horizontal -> Left to Right). This aligned with how react-splitter-view's `vertical` property worked. However, after discussions with Meredith and Doug, we realized this was inverted from what a user would expect.
This PR is a simple change to flip Vertical and Horizontal to refer to the direction of the splitter. So, now the options look like this:
| Vertical | Horizontal |
| - | - |
| ![image](https://github.com/Azure/cosmos-explorer/assets/7574/ …
=> swap splitter directions in query results view

src/Utils/QueryUtils.test.ts, src/Utils/QueryUtils.ts
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1928)
There was a check where, when updating a document, it would only populate a partition key value if there was a non-empty value for that field in the document to begin with. This is incorrect behavior as a document in a container with hierarchical partitions can have an empty value for one of those partition key fields. The result of this would be the document would be sent with x number of partition key fields but only x - 1 partition key values which would fail backend validation.
This PR simply allows whatever was in that field to be passed on to the "partitionKeyValues" property. If that value is "" then so be it. Updating documents with empty values for partition key fields should now work as expected.
=> Removing check for value when populating partition key values

less/documentDB.less, src/Explorer/Tabs/Tabs.tsx
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1930?feature.someFeatureFlagYouMightNeed=true)
Fixes #1929 
This fixes an issue that arose after #1865 was merged. I used a grid layout there, but when there are multiple MessageBars we have more elements than rows and one of the MessageBars or Tab Nave ends up in the `1fr`-sized last row and takes up the rest of the space, covering the actual tab content. This can be worked around by closing MessageBars, but it's definitely not intended.
I did plan for a MessageBar to be present when designing that. However, I neglected to validate the behavior with _multiple_ MessageBars, which can often happen when firewall rules are not configured and you have the RU Threshold warning message up. I wanted to use a Grid …
=> fix #1929 by using flex instead of grid to lay out the tabs view

src/Explorer/Explorer.tsx, src/hooks/useKnockoutExplorer.ts
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1932?feature.someFeatureFlagYouMightNeed=true)
Often times, depends on timing, portal often sends 2 messages for initialization parameters which impacts how much times we are trying to show the NPS survey.
Either way, opening an NPS survey logic should not live inside of the window event listener as it can impact the telemetry we are collecting per user.
I moved the call to the reacthook that would run only once after Explorer has been initialized.
Before
After
=> move nps survey open dialog call to after explorer initialization

src/Explorer/QueryCopilot/QueryCopilotPromptbar.tsx
Resolved issue where the suggestions in the 'Copilot search' edit field were inaccessible via keyboard navigation. Users can now navigate through suggestions using arrow keys.
**Note:** When the user exits the suggestion box, the focus shifts away from the component. This issue will be addressed in a separate ticket.
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1893?feature.someFeatureFlagYouMightNeed=true)
https://github.com/Azure/cosmos-explorer/assets/107645008/9c4bf271-45ce-465e-a30b-ed38f07bff85
=> The suggestions of 'Copilot search' edit field are not accessible with keyboard.

src/Explorer/ContextMenuButtonFactory.tsx
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1939)
Remove this menu which contains "New Container" and "Delete Database" which is not applicable for read-only Fabric.
=> Remove Database context menu for Fabric read-only configuration

src/Explorer/Controls/TreeComponent/Styles.ts, src/Explorer/Controls/TreeComponent/__snapshots__/TreeNodeComponent.test.tsx.snap, src/Explorer/Sidebar.tsx
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1938)
@MeredithMooreUX got some feedback that the new resource tree layout doesn't react well at really narrow sizes. I did some work on the narrow layout in the initial PR but this PR iterates further on that with a few improvements:
1. When the sidebar is narrower than 150px (which is the point at which the "New Container" split button starts to wrap), the "Global Command" split button becomes a pure menu (i.e. instead of having a primary action and a dropdown menu, it just always drops down the menu) with the title "New...". Since the menu can overhang the sidebar, this makes it easier to see what operations are available. This behavior depends on CSS Container Queries which [are available in modern …
=> Improve sidebar UI layout when narrow

test/sql/query.spec.ts
The E2E playwright tests for query errors depend on getting accurate error details from the backend. However, there's an issue that causes some accounts to suddenly stop reporting error details. The query team is working on this, but until it's resolved I'm disabling the affected tests.
=> disable query error tests due to backend issue

src/Explorer/Tabs/DocumentsTabV2/DocumentsTabStateUtil.ts, src/Explorer/Tabs/DocumentsTabV2/DocumentsTableComponent.tsx
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1944)
The Documents tab currently saves the column width as:
```javascript
{
idealWidth: 10
minWidth: 50
}
```
which is the data structure returned by the fluent UI table.
We're only interested in persisting `idealWidth`, so we're changing the format to:
```javascript
{
widthPx: 10
}
```
The change is backward compatible and will ignore (and overwrite) any data in the previous format.
=> Change persistence format for column width in DocumentsTab

src/Explorer/Panes/SettingsPane/__snapshots__/SettingsPane.test.tsx.snap, src/Shared/StorageUtility.ts
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1946)
When I swapped the splitter orientation, I didn't change the default (when the default orientation hasn't been set in settings). As a result, the default is now the "Vertical" layout, which means a vertical splitter:
This is jarring for users who were used to the default (we've gotten NPS feedback about this too). This PR just flips that default. If any user has set their default in the settings, this PR won't affect them.
=> change default splitter orientation when the setting has not been set

less/documentDB.less, src/Explorer/Controls/TreeComponent/Styles.ts, src/Explorer/Controls/TreeComponent/TreeNodeComponent.tsx, src/Explorer/Controls/TreeComponent/__snapshots__/TreeNodeComponent.test.tsx.snap, src/Explorer/Sidebar.tsx, src/Explorer/Tabs/DocumentsTabV2/__snapshots__/DocumentsTableComponent.test.tsx.snap, src/Explorer/Tabs/Tabs.tsx, src/Explorer/Theme/ThemeUtil.tsx, src/Explorer/Tree/__snapshots__/treeNodeUtil.test.ts.snap, src/Explorer/Tree/treeNodeUtil.tsx
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1951)
After some user feedback that there's too much blank space in the new tree view, I went back in and looked for some things we could do to better fit DE into a small screen environment.
This PR is the result of that. Here's a video toggling between the old and new layouts. The screen size here is 1366x768, which is our standard "desktop" (as in not-mobile, laptops _are_ included) minimum size. You can see that there's quite a bit of space savings from these changes:
https://github.com/user-attachments/assets/d4eca67e-145b-48d2-88df-67a54cf55169
In addition, I've added some icons back to the tree, after discussing with Doug and Meredith. We don't have icons everywhere, but we've added icons to the Database, …
=> Reduce extra spacing in the new tree and items tab

src/Explorer/Tabs/DocumentsTabV2/DocumentsTabV2.tsx
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1955)
Add `ORDER BY c._ts ASC` and dynamically generated for each partition key `WHERE c.<partition key> = "foo"` to the list of default filters.
=> Add more default filters to Documents Tab

src/Common/Tooltip/InfoTooltip.tsx, src/Explorer/Panes/SettingsPane/SettingsPane.tsx, src/Explorer/Panes/SettingsPane/__snapshots__/SettingsPane.test.tsx.snap
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1945)
The current SettingsPane has too many options.
Move all items into an `<Accordion>`. Only one option can be opened at a time.
Move the Info tips (i) text into the accordion section.
=> Improve SettingsPane

src/Common/MongoProxyClient.ts, src/ConfigContext.ts, src/Explorer/Tables/TableDataClient.ts, src/Explorer/Tabs/Tabs.tsx
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1958)
Changes in this PR include:
- Point DE to Mongo and Cassandra Proxies regardless of network configuration
- Change banner from warning to alert
- Activate Cassandra Proxy in FF and MC
=> Point DE to new Mongo and Cassandra Proxies only and activate Cassandra Proxy in FF/MC

src/Explorer/Sidebar.tsx
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1953?feature.someFeatureFlagYouMightNeed=true)
I was opening the split button "Global Commands" menu and I noticed something:
Hey menu, what are you doing way up there?
Well, it turns out that when you put two DOM elements under a `<MenuTrigger>`, it gets a little confused and does all the positioning based on the _last_ element. In our case, the last element is only visible on small screens (we swap between the first and last element based on container width using CSS container queries). As a result, that messes with things when the first element (the SplitButton) is the one that's visible.
This PR wraps those elements in a new `div`. Unfortunately, that's not entirely enough, we also need the Menu to know to …
=> fix rendering of global commands menu

src/Explorer/Tabs/Tabs.tsx
This pull request addresses an accessibility issue within the Azure Cosmos DB Data Explorer pane. The "Close" button currently lacks discernible text, making it difficult for users relying on assistive technologies to identify its function.
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1949?feature.someFeatureFlagYouMightNeed=true)
=> [Programmatic Access - Azure Cosmos DB - Data Explorer]: Close button does not have discernible text under 'Data Explorer' pane.

src/Explorer/Tabs/DocumentsTabV2/DocumentsTabV2.tsx, src/Explorer/Tabs/DocumentsTabV2/DocumentsTabV2Mongo.test.tsx
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1964)
For all users who have IP rules but don't have the mongo proxy IP address in their IP rules we send them to the old backend.
We are updating the documentation to instruct users to add the mongo proxy, but for now, we disable bulk delete (a capability only available in the new mongo proxy) for these users.
=> Disable bulkdelete for users point to old mongo proxy

src/Shared/AppStatePersistenceUtility.test.ts, src/Shared/AppStatePersistenceUtility.ts
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1961)
Users might lose their settings if one of the segments contains uri character that gets encoded (e.g. a `/` in the name, since we use `/` as a separator).
To keep the code simple and free from legacy logic, I did not implement any migration from the old persistence.
Previous settings will disappear for some users who have `/` in the name (it should be the subset who use resource token). Persistence has been introduced only recently and for a few preferences, so the amount of lost user preferences should be very limited.
=> Allow slashes in persistence keys

package-lock.json, src/Explorer/Explorer.tsx, src/Explorer/Panes/TableColumnSelectionPane/TableColumnSelectionPane.tsx, src/Explorer/Tabs/DocumentsTabV2/DocumentsTabStateUtil.ts, src/Explorer/Tabs/DocumentsTabV2/DocumentsTabV2.test.tsx, src/Explorer/Tabs/DocumentsTabV2/DocumentsTabV2.tsx, src/Explorer/Tabs/DocumentsTabV2/DocumentsTableComponent.test.tsx, src/Explorer/Tabs/DocumentsTabV2/DocumentsTableComponent.tsx, src/Explorer/Tabs/DocumentsTabV2/SelectionHelper.ts, src/Explorer/Tabs/DocumentsTabV2/__snapshots__/DocumentsTabV2.test.tsx.snap, src/Explorer/Tabs/DocumentsTabV2/__snapshots__/DocumentsTableComponent.test.tsx.snap, src/Platform/Hosted/extractFeatures.ts, src/Shared/StorageUtility.ts, src/Utils/QueryUtils.test.ts, src/Utils/QueryUtils.ts
[Preview this branch](https://ms.portal.azure.com/?feature.enableDocumentsTableColumnSelection=true&dataExplorerSource=https%3A%2F%2Fcosmos-explorer-preview.azurewebsites.net%2Fcommit%2F6fea506bc61eb020b078d4251c571fced8bf65ad%2Fexplorer.html%3Ffeature.pr%3Dhttps%253A%252F%252Fgithub.com%252FAzure%252Fcosmos-explorer%252Fpull%252F1963%2523users%252Flanguye%252Fcolumn-selection-take2#@microsoft.onmicrosoft.com/dashboard/private/94577c65-bdf4-47a5-b69a-df64270bd023)
This a replay of [this PR](https://github.com/Azure/cosmos-explorer/pull/1881) including the following improvements:
* Bug fix for when partition key is "id": the old code would remove "id" from the query and the documents tab would be unable to read any selected document (which would be missing the "id" field).
* Improved logic …
=> Enable column selection and sorting in DocumentsTab (with persistence) with improvements

src/Common/QueryError.test.ts, src/Common/QueryError.ts, src/Explorer/Panes/SettingsPane/SettingsPane.tsx, src/Explorer/Panes/SettingsPane/__snapshots__/SettingsPane.test.tsx.snap, src/Explorer/Tabs/QueryTab/ErrorList.tsx, src/Explorer/Tabs/QueryTab/Styles.ts, src/Explorer/Tabs/Tabs.tsx
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1966)
Currently, if you open DE and don't have any "RU Threshold" value set in settings, you get this banner:
This takes up a fair amount of vertical space, especially in the portal, and is telling you something that you may not be interested in, and it may never be relevant for a user depending on the kinds of queries they run and the data they're querying. Plus, the only way to permanently dismiss it is to go to the settings and set an RU Threshold explicitly, which isn't easy.
So, this PR removes that banner. Instead of the banner, I've added logic to refine the error message when the RU limit is violated for a given query. Prior to this PR, that error looked like this:
The error message is coming from the JS …
=> Replace RU limit banner by clarifying the error when RU limit is exceeded

src/Explorer/Tables/Constants.ts, src/Explorer/Tables/DataTable/DataTableBindingManager.ts, src/Explorer/Tables/DataTable/DataTableOperationManager.ts, src/Explorer/Tables/DataTable/TableEntityListViewModel.ts, src/Explorer/Tables/Entities.ts
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1969)
Issue: In Tables API, it is legal to have two entities with the same row key as long as they have different partition keys. DE strictly looked at the row key when selecting an entity. So in this use case, when clicking a single entity, multiple entities would be selected (as many as shared the same row key). This affected updates as if a user selected the second entity with the same row key, it would update the first in the list.
This PR addresses this by adding an attribute to the table row tag for partition key, similar to what is being added for the row key. This new attribute is used in conjunction with the row key to determine the correct entity to select, edit, and delete.
=> Fixed issue with Tables API when selecting a row with the same row key in different partition keys

src/Common/MongoProxyClient.ts, src/ConfigContext.ts, src/Explorer/Tables/TableDataClient.ts, src/Explorer/Tabs/Tabs.tsx
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1971)
Currently, we are routing users to one of the old backend or Mongo/Cassandra Proxy based on their networking settings. This change is to force all users to the Mongo/Cassandra Proxies.
=> Force Mongo and Proxy users to switch to Mongo and Cassandra Proxy

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .devcontainer/oncreate
*This change doesn't affect the app functionality at all*
This PR adds a few config files to provide a standardized configuration for launching a GitHub Codespace or VS Code Dev Container (locally) for this repo. It doesn't require the use of codespaces at all, but makes it possible for a user to quickly open the repo up in a Codespace that is preconfigured to immediately run the app.
I've been using Codespaces more for development and trying it out on this repo (among others I'm working with, in particular the Azure SDKs) and it provides a useful alternative to having to install all the prereqs on my local box.
=> Add config files for Codespaces

src/Explorer/Panes/DeleteDatabaseConfirmationPanel.tsx, src/Explorer/Panes/__snapshots__/DeleteDatabaseConfirmationPanel.test.tsx.snap
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1974)
We got some customer feedback that the term `database id` in the Delete Database panel was confusing as they were thinking they needed to figure out some kind of internal identifier. I didn't want to _replace_ the current text, because we do use the term "database id" in lots of other places, but I felt a little clarification could be added without much confusion.
This is what it looks like after this change:
=> Clarifying copy-edit to delete database panel

src/Common/DatabaseUtility.ts, src/Explorer/Panes/AddCollectionPanel.tsx, src/Explorer/Panes/AddDatabasePanel/AddDatabasePanel.tsx, src/Explorer/Panes/AddDatabasePanel/__snapshots__/AddDatabasePanel.test.tsx.snap, src/Explorer/Panes/__snapshots__/AddCollectionPanel.test.tsx.snap, test/cassandra/container.spec.ts, test/gremlin/container.spec.ts, test/mongo/container.spec.ts, test/sql/container.spec.ts
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1981?feature.someFeatureFlagYouMightNeed=true)
Pulls the logic for determining the default value of enabling shared throughput when creating a new database into a common function and then changes that to false.
=> Set shared throughput default to false for New Databases

test/fx.ts, utils/cleanupDBs.js, webpack.config.js
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1982?feature.someFeatureFlagYouMightNeed=true)
This change modifies the E2E test configuration to use a new set of database accounts.
=> Switch E2E tests to use new accounts.

README.md, docs/index.html, preview/index.js, src/Common/Constants.ts, src/Common/CosmosClient.test.ts, src/Common/MongoProxyClient.test.ts, src/Common/MongoProxyClient.ts, src/ConfigContext.ts, src/Explorer/Tabs/DocumentsTabV2/DocumentsTabV2.tsx, src/Explorer/Tabs/MongoShellTab/MongoShellTabComponent.tsx, src/Utils/MessageValidation.test.ts, src/Utils/NetworkUtility.test.ts, src/Utils/NetworkUtility.ts, webpack.config.js
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1983)
As we move off the legacy backend, we need to remove the references in both Data Explorer and Azure Portal. This PR removes references in tests and local dev. Once migration is complete, we will remove all references.
=> Remove legacy backend references in tests and local dev

src/Common/EntityValue.tsx, src/Common/TableEntity.tsx
This pull request addresses an accessibility issue in the 'Add Table Row' pane within Azure Cosmos DB. Specifically, it corrects a missing descriptive label for the 'Value' edit fields, which was impacting screen reader users.
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1970?feature.someFeatureFlagYouMightNeed=true)
=> Descriptive Label is not provided for 'Value' edit fields under 'Add Table Row' pane.

src/Common/MongoProxyClient.ts, src/ConfigContext.ts, src/Utils/EndpointUtils.ts
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1984?feature.someFeatureFlagYouMightNeed=true)
When DE is deployed, config is added.  Allow pulling additional allowedCassandraProxyEndpoints and allowedMongoProxyEndpoints from that deployment config.
=> Pull Additional Allowed Cassandra and Mongo Proxy Endpoints from Deployed Config

src/Common/MongoProxyClient.test.ts, src/Common/MongoProxyClient.ts, src/ConfigContext.ts, src/Explorer/Tables/TableDataClient.ts
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1992?feature.someFeatureFlagYouMightNeed=true)
Adds ability to globally enable cassandra or mongo proxy APIs in all environments through config.json.
=> CP and MP API Overrides from Config.json

src/Common/Constants.ts
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1995?feature.someFeatureFlagYouMightNeed=true)
Correcting spelling of CreateDocumen to CreateDocument for the Mongo API list.  CreateDocumen does not exist anywhere else in backend or frontend.
=> Correct spelling of CreateDocumen to CreateDocuments

less/documentDB.less, less/documentDBFabric.less, src/Explorer/Sidebar.tsx
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1996?feature.someFeatureFlagYouMightNeed=true)
This PR changes the layout slightly so that the right side of the command bar doesn't push out past the containing element when rendered in Fabric.
Here's an example screenshot:
To fix this, I changed from having individual elements of DE include special margins for fabric to having the top-level _container_ apply a padding. I also had to wrap the split pane we use to hold the sidebar and center pane in a container, to prevent it trying to push past the padding on the right.
In addition, I made a little change to put the fabric background colors in the loading splash screen, which avoids a somewhat-jarring white background when DE is loading. Instead, the splash …
=> fix layout issues in fabric

src/Explorer/Tabs/DocumentsTabV2/DocumentsTabV2.tsx, src/Explorer/Tabs/DocumentsTabV2/DocumentsTableComponent.test.tsx, src/Explorer/Tabs/DocumentsTabV2/DocumentsTableComponent.tsx, src/Explorer/Tabs/DocumentsTabV2/__snapshots__/DocumentsTabV2.test.tsx.snap, src/Explorer/Tabs/DocumentsTabV2/__snapshots__/DocumentsTableComponent.test.tsx.snap
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1997)
When the table is sorted, the order of the original items array changes, so clicking on a row index highlighted the wrong document. The distinction is now made between `rowId` (the index of the original array passed to `DocumentsTableComponent`) and `index` (the index of the row in the table visible by the user, ie the index of the sorted array).
The initial first row selection is now done by `DocumentsTableComponent` as it is the only one that knows which index is the top row in the sorted array, because it is the component that sorts the array.
We use a `React.ref` to store the sorted array for later access instead of a state which triggers a render.
=> Fix row selection issue in DocumentsTab when sorting rows

src/Explorer/QueryCopilot/Modal/QueryCopilotFeedbackModal.tsx, src/Explorer/QueryCopilot/Modal/__snapshots__/QueryCopilotFeedbackModal.test.tsx.snap
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/2000?feature.someFeatureFlagYouMightNeed=true)
This change updates the privacy text when users submit feedback from the Query Advisor. It also updates the link 
to the privacy statement.
=> Update query advisor privacy statement and link

src/Common/QueryError.test.ts, src/Common/QueryError.ts
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/2003?feature.someFeatureFlagYouMightNeed=true)
The backend has shifted how errors are reported a bit. Now, when we get detailed query errors from newer backends, we get a payload that looks like this:
```json
{
"code": "BadRequest",
"message": "{\"code\":\"BadRequest\",\"message\":\"{\\\"errors\\\":[{\\\"severity\\\":\\\"Error\\\",\\\"location\\\":{\\\"start\\\":7,\\\"end\\\":18},\\\"code\\\":\\\"SC2005\\\",\\\"message\\\":\\\"'nonexistent' is not a recognized built-in function name.\\\"}]}\\r\\nActivityId: f9ef6130-d878-4eb9-89c9-1f525782b6c4, Windows/10.0.20348 cosmos-netstandard-sdk/3.18.0\"}"
}
```
Our current parsing doesn't support this (it's basically added another layer of JSON wrapping the error), so …
=> add more edge cases to Query Error parser

src/Explorer/Controls/InputDataList/InputDataList.tsx, src/Explorer/Tabs/DocumentsTabV2/DocumentsTabV2.test.tsx, src/Explorer/Tabs/DocumentsTabV2/DocumentsTabV2.tsx, src/Explorer/Tabs/DocumentsTabV2/__snapshots__/DocumentsTabV2.test.tsx.snap
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1998)
* Always keep filter editable
* Single "Apply filter"/"Cancel"
* Fluent UI-based dropdown for saved and default filters with link to learn more. 
* Clear button on the right clear filter
* Cleaned up old style and code (for example don't focus with outline)
* Input and dropdown navigation with tab for a11y compliance
* The input and dropdown menu is a React component.
* Dropdown will show when input gets focus
* Dropdown shows only when input has no text
* Clear button at the end of the input box becomes down button to reveal dropdown if input has no text. 
* Generally first dropdown item gets autofocus when dropdown opens (when input doesn't have focus)
* Arrow up/down move focus in the dropdown item. If …
=> Improve DocumentsTab filter input

.github/workflows/ci.yml
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/2006?feature.someFeatureFlagYouMightNeed=true)
This change updates the upload-artifact and download-artifact actions in CI to use v4. This is due to incoming deprecation of the v3 versions of these actions.
https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
=> Update upload/download-artifact actions to v4 due to v3 deprecation.

less/documentDB.less
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/2013)
When you open more tabs than can fit in the bar, the tabs don't wrap anymore and you simply can't access the extra tabs. This PR fixes the wrapping by enabling `flex-wrap` on the container and disabling the hard `32px` height cap on the tab bar. Once I did that though, the bottom border of the tab bar stopped lining up with the lines on the tree view, so I adjusted the individual tabs so they had a height of `32px` (to match our "layout row height"). And then, because CSS problems always tend to *casdade* ;), I had to adjut the border and margins a little bit to nudge everything in to place. Now we have wrapping and alignment!
https://github.com/user-attachments/assets/e8fb9bcc-f129-4bc5-8254-6c4873c6bb8d
=> fix tab wrapping with a lil' css tweak

src/hooks/useKnockoutExplorer.ts, src/hooks/useTabs.ts
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/2014)
In Fabric, the user can switch between artifacts resulting Data Explorer to call the "initialize" handler in `useKnockoutExplorer` multiple times. The handler re-instantiates Data Explorer by instantiating `Explorer`, but there is some leftover state like open tabs.
This closes the tabs, so the user will not see tabs from the old artifact when switching artifacts.
There should be a more comprehensive version that cleans up everything, but for now, this fix is the least risky change with minimal impact on the other use cases.
No more check for `firstContainerOpened`: in the new Trident-DI-extension, the "initialize" handler is always called first, so no need to check for this flag and always load container.
=> Close all tabs and always load first container when initializing Fabric

.github/workflows/ci.yml, src/Common/CosmosClient.ts, src/Explorer/Panes/SettingsPane/SettingsPane.tsx, src/UserContext.ts
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/2023?feature.someFeatureFlagYouMightNeed=true)
Once the RBAC setting changes, it sets userContext.hasDataPlaneRbacSettingChanged to true, but it never gets set back to false.
https://github.com/Azure/cosmos-explorer/blob/master/src/Common/CosmosClient.ts#L192
That causes a new cosmos client to be generated on each call to the client after any setting has changed in the settings menu.  After about 15 document reads, I had about 10 Cosmos Clients and 18 mb increase in memory usage.
Created a context variable to signal the client function to delete and regenerate the client when a client specific setting is changed.
Tested with memory profiling to make sure new cosmos clients are only generated when needed.  Garbage …
=> Settings Menu Client Refresh Bug Fix, Limit Client Options in APIs

.github/workflows/ci.yml, DataExplorer.proj, webpack.config.js
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/2026?feature.someFeatureFlagYouMightNeed=true)
This change updates the CI action to use dotnet CLI for nuget package operations (i.e. pack and publish) instead of Nuget.exe. This is necessary due to Nuget.exe no longer working on latest Ubuntu images as Mono is no longer installed by default.
More details here: https://github.com/NuGet/setup-nuget/issues/168
=> Use dotnet CLI for nuget operations in CI pipeline

.github/workflows/ci.yml
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/2030?feature.someFeatureFlagYouMightNeed=true)
This addresses a change in the v4 upload-artifacts action, which fails when duplicate artifact names are used. It was causing Publish Nuget tasks to fail.
=> Use unique names in upload artifacts tasks

src/Explorer/Controls/Settings/SettingsSubComponents/ThroughputInputComponents/ThroughputInputAutoPilotV3Component.tsx
This change removes the "Need to scale below 139000 RU/s? Reach out by filling this questionnaire" text from the Scale/Settings tab. The survey that the text linked to no longer exists and was causing customer confusion.
=> Remove survey text and link from Throughput section in Scale/Settings

webpack.config.js
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/2033?feature.someFeatureFlagYouMightNeed=true)
This change removes hard coded client and subscription Ids from the webpack config. These are used by the E2E test actions and are not necessary for local testing. These are provided by configured secrets in the CI Action.
=> Remove hard coded client and subscription Ids from webpack config.

src/Explorer/SplashScreen/SplashScreenButton.tsx
This PR improves accessibility in the Azure Cosmos DB Data Explorer by adding alt text to <img> elements and setting aria-hidden="true" for decorative images. These changes ensure that images are either properly described for screen readers or ignored, enhancing the experience for users with visual impairments.
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/2007?feature.someFeatureFlagYouMightNeed=true)
Before:
After:
=> [Programmatic Access- Azure Cosmos DB- Data explorer]: Ensures <img> elements have alternate text or a role of none or presentation.

less/documentDB.less, src/Explorer/Panes/SettingsPane/SettingsPane.tsx, src/Explorer/Panes/SettingsPane/__snapshots__/SettingsPane.test.tsx.snap
This pull request addresses an accessibility issue in the Azure Cosmos DB - Data Explorer where the keyboard focus indicator was not visible on controls inside the settings. This issue impacted users navigating with a keyboard, as they could not visually track focus on interactive elements within the settings panel.
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/2016?feature.someFeatureFlagYouMightNeed=true)
Before
https://github.com/user-attachments/assets/cdea2e53-297e-49ac-b10f-bfbf9ab846cd
After
https://github.com/user-attachments/assets/8ee82ace-c180-46e2-995b-8bceba15832b
=> [Programmatic Access - Azure Cosmos DB- Data Explorer]: Keyboard focus indicator is not visible on controls inside the settings.

src/Common/Constants.ts, src/Explorer/Panes/AddCollectionPanel.tsx, src/Explorer/Panes/__snapshots__/AddCollectionPanel.test.tsx.snap
This PR addresses an issue in Azure Cosmos DB - Data Explorer where the "Learn More" links under the settings were not sufficiently descriptive. The links have now been revised to offer clearer, more specific information, in line with the requirements outlined in the related tickets. Users will now have a better understanding of the relevant settings and their functionality, improving the overall user experience and accessibility.
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/2035?feature.someFeatureFlagYouMightNeed=true)
=> [Screen Reader- Azure Cosmos DB- Data Explorer]: The Learn more links are not descriptive present under the settings.

src/Explorer/Controls/Settings/SettingsSubComponents/PartitionKeyComponent.tsx
Disabled change button in Partition Keys section in data explorer 
https://msdata.visualstudio.com/CosmosDB/_workitems/edit/3607509
=> [Emulator][Data Explorer ]Disabled copy partition key feature from data explorer for emulator

src/Platform/Hosted/extractFeatures.ts, src/hooks/useKnockoutExplorer.ts
[Preview this branch](https://dataexplorer-preview.azurewebsites.net/pull/2039)
Enable restore tabs by default.
=> Remove feature switch on restore tabs

src/hooks/useKnockoutExplorer.ts
[Preview this branch](https://dataexplorer-preview.azurewebsites.net/pull/2045)
For Fabric mirroring, we always auto-open the first container of the database (the Documents tab shown as "Items") for convenience.
Now that Data Explorer restores open tabs, we prevent DE from auto-opening the first container if a tab is already open.
=> Bug fix: do not auto-open first container if a tab is already open (Fabric only)

utils/cleanupDBs.js
[Preview this branch](https://dataexplorer-preview.azurewebsites.net/pull/2051?feature.someFeatureFlagYouMightNeed=true)
Fix the Action that cleans up E2E test resources - we moved to @azure/identity package recently and this was missed in that change.
=> Modify E2E cleanup script to use @azure/identity for AZ credentials.

src/Contracts/MessageTypes.ts
[Preview this branch](https://dataexplorer-preview.azurewebsites.net/pull/2046?feature.someFeatureFlagYouMightNeed=true)
This change restores the DisplayNPSSurvey  message type enum value which was removed by a prior commit.
=> Restore DisplayNPSSurvey message type enum

src/Explorer/Sidebar.tsx
This PR addresses an issue where keyboard focus is lost when navigating to the Data Explorer page from the Overview page in Azure Cosmos DB. The problem was that after activating the "Data Explorer" menu item, the page did not correctly set focus on the expected element, impairing keyboard navigation.
**Note**: We are Using `setTimeout `with `0ms `ensures that the code runs asynchronously after the current execution context completes. Without it, the code is not working as expected due to JavaScript's synchronous execution model.
[Preview this branch](https://cosmos-explorer-preview.azurewebsites.net/pull/1927?feature.someFeatureFlagYouMightNeed=true)
https://github.com/user-attachments/assets/a1528b42-fb2b-4349-9065-a8755904ac47
=> [accessibility-1217621]: Keyboard focus gets lost on the page which opens after activating "Data Explorer" menu item present under 'Overview' page.

src/Explorer/Explorer.tsx, src/hooks/useKnockoutExplorer.ts, webpack.config.js
[Preview this branch](https://dataexplorer-preview.azurewebsites.net/pull/2047?feature.someFeatureFlagYouMightNeed=true)
This PR addresses a couple of optimizations on the Data Explorer build and runtime.
1. Removed compress:false flag from webpack configuration. This increases the build time at npm run pack:prod by ~75-100%, but it will reduce the bundle size by ~100-150%
2. Removed blocking async/await on the reading sample database call at the initialization.
- This introduces a refresh of the sidebar after the explorer is loaded, but at least they do not have to wait until this HTTP request is completed.
=> Remove blocking await on sample database

src/Common/CosmosClient.ts, src/Explorer/Panes/SettingsPane/SettingsPane.tsx, src/Utils/APITypeUtils.ts, src/hooks/useKnockoutExplorer.ts
[Preview this branch](https://dataexplorer-preview.azurewebsites.net/pull/2056?feature.someFeatureFlagYouMightNeed=true)
This change adds Tables API as being supported for Entra ID RBAC. Support is otherwise identical to existing NoSQL API.
=> Add Tables as an API type that supports dataplane RBAC.

src/SelfServe/SelfServe.tsx, src/SelfServe/SelfServeUtils.tsx
[Preview this branch](https://dataexplorer-preview.azurewebsites.net/pull/2057)
All of the strings used in self serve blades are stored in src/Localization/en/<selfServeTypeName>.json. The previous method to get the name of the  .json was to use SelfServeType.constructor.name. This works as expected in PROD (i.e. for SqlX, sqlx.constructor.name returns "SqlX). But this does not work in MPAC. It seems to return a minified name (i.e. for SqlX it would return "y"). Since there's no file called y.json the method would fail to load the strings for SqlX.
So this switches the method for getting the name by simply returning the value of the enum SelfServeType (which has also been changed to match the casing of the files on disk).
NOTE! If you want to test this PR, you need to change the URL's …
=> Fixing SelfServeType enum to work in MPAC

src/SelfServe/SelfServeUtils.tsx
[Preview this branch](https://dataexplorer-preview.azurewebsites.net/pull/2062?feature.someFeatureFlagYouMightNeed=true)
This change updates the value of `example` in the `SelfServeType` enum to match the corresponding localization file name.
This addresses one of the e2e tests which is currently failing.
=> Change value of the example SelfServeType enum to match file name.

src/Explorer/Menus/CommandBar/CommandBarComponentButtonFactory.test.ts, src/Explorer/Menus/CommandBar/CommandBarComponentButtonFactory.tsx, src/hooks/useKnockoutExplorer.ts
[Preview this branch](https://dataexplorer-preview.azurewebsites.net/pull/2060?feature.someFeatureFlagYouMightNeed=true)
This change adds Tables API to two api checks for data plane RBAC, that were missed in my previous change:
- Setup for Portal hosting
- Enabling the RBAC Login button in the Command Bar
=> Add Tables to missing api type checks for dataplane RBAC.

src/Common/dataAccess/createCollection.ts, src/Common/dataAccess/deleteCollection.ts, src/Common/dataAccess/readDatabaseOffer.ts, src/Common/dataAccess/updateCollection.ts, src/Common/dataAccess/updateOffer.ts, src/Explorer/ContextMenuButtonFactory.tsx, src/Explorer/Tree/__snapshots__/treeNodeUtil.test.ts.snap, src/Explorer/Tree/treeNodeUtil.test.ts
[Preview this branch](https://dataexplorer-preview.azurewebsites.net/pull/2069)
=> Fabric native: use SDK not ARM for update offers/collections. Enable Delete Container context menu item in resource tree

less/documentDB.less
[Preview this branch](https://dataexplorer-preview.azurewebsites.net/pull/2076)
Cherry-picking this [fix](https://github.com/Azure/cosmos-explorer/pull/2013) that was merged to [release/holidays2024](https://github.com/Azure/cosmos-explorer/tree/release/holidays2024), but didn't make it to `master`.
=> fix tab wrapping with a lil' css tweak (#2013)

src/Explorer/Controls/Settings/SettingsSubComponents/MaterializedViewComponent.test.tsx, src/Explorer/Controls/Settings/SettingsSubComponents/MaterializedViewSourceComponent.test.tsx
=> Test Cases Update: added explorer as a prop

src/Explorer/Tabs/DocumentsTabV2/DocumentsTabV2.tsx, src/Explorer/Tabs/DocumentsTabV2/__snapshots__/DocumentsTabV2.test.tsx.snap
Users want the container item "Refresh" button added back to outside the ellipses so it's easier to find and click.
We are keeping the "Refresh" button within the ellipses.
[Preview this branch](https://dataexplorer-preview.azurewebsites.net/pull/2083?feature.someFeatureFlagYouMightNeed=true)
=> Adding container item refresh button back to upper right corner of page

src/Explorer/Tabs/DocumentsTabV2/DocumentsTabV2.tsx, src/Utils/QueryUtils.test.ts, src/Utils/QueryUtils.ts
[Preview this branch](https://dataexplorer-preview.azurewebsites.net/pull/2085?feature.someFeatureFlagYouMightNeed=true)
This is to address the issue where the partition key was missing, causing the document to fail to load.
Previously we have made changes for paritition key null or "" cases, however when the partition key is entirely missing, which CosmosDB allows, passing in subset of the existing partitionkeys to the SDK will fail to load the document,
So adding the logic to always pull all partitionkeys in paths and always pass all partitionkeys in paths to the SDK as {} if missing.
=> fix partition key missing not being able to load the document

src/Explorer/Tabs/DocumentsTabV2/DocumentsTabV2.tsx, src/Explorer/Tabs/DocumentsTabV2/DocumentsTableComponent.tsx
[Preview this branch](https://dataexplorer-preview.azurewebsites.net/pull/2089?feature.someFeatureFlagYouMightNeed=true)
- Added the refresh button to Mongo DB
- Shifted the ellipsis so the refresh button doesn't hide it when only a single column exists
vs.
1 column
=> Add refresh button to Mongo DB RU and adjust ellipsis so refresh button on single column container doesn't hide it

src/SelfServe/SelfServe.tsx
[Preview this branch](https://ms.portal.azure.com/?selfservesource=https%3A%2F%2Fdataexplorer-preview.azurewebsites.net%2Fcommit%2F2875462bc64767c24273362a65350a828016e525%2FselfServe.html%3Ffeature.pr%3Dhttps%253A%252F%252Fgithub.com%252FAzure%252Fcosmos-explorer%252Fpull%252F2088%2523users%252Faisayas%252Fself-serve-fix-3#home)
Text rendering is currently broken in non local environments. 
Fix
=> Self Serve text render fix

src/Explorer/Tabs/ConnectTab.tsx
[Preview this branch](https://dataexplorer-preview.azurewebsites.net/pull/2095?feature.someFeatureFlagYouMightNeed=true)
Updates Connect tab to hide keys and connection strings by default.  Other changes include:
1. Moving URI to outside the Read-write/Read-only keys tabs since common between tabs.
2. Moves copy buttons to within the key field and only shows when the unhide button is selected.
3. Adds scrolling to keys section when window size is reduced.  Prevents connection strings lower in the section from being unreachable when window size is reduced.
=> Hide Keys and Connection Strings in Connect Tab

playwright.config.ts, src/Explorer/Tabs/DocumentsTabV2/DocumentsTabV2.tsx, src/Explorer/Tabs/DocumentsTabV2/__snapshots__/DocumentsTabV2.test.tsx.snap, src/Utils/QueryUtils.test.ts, src/Utils/QueryUtils.ts, test/fx.ts, test/sql/document.spec.ts, test/sql/testCases.ts
[Preview this branch](https://dataexplorer-preview.azurewebsites.net/pull/2094?feature.someFeatureFlagYouMightNeed=true)
- This is to address the issue where the partition key was missing, causing the document to fail to load.
Previously we have made changes for paritition key null or "" cases, however when the partition key is entirely missing, which CosmosDB allows, passing in subset of the existing partitionkeys to the SDK will fail to load the document,
So adding the logic to always pull all partitionkeys in paths and always pass all partitionkeys in paths to the SDK as {} if missing.
- If system partition key, the SDK will not support passing the system partition key value, so skipping the system partition key.
- E2E tests are written for testing different collections with different …
=> Pk missing fix

src/Common/dataAccess/readCollectionOffer.ts, src/Explorer/Controls/Settings/SettingsComponent.tsx, src/Explorer/Controls/Settings/SettingsSubComponents/PartitionKeyComponent.tsx, src/Explorer/Controls/Settings/__snapshots__/SettingsComponent.test.tsx.snap, src/Explorer/Tree/__snapshots__/treeNodeUtil.test.ts.snap, src/Explorer/Tree/treeNodeUtil.test.ts, src/Explorer/Tree/treeNodeUtil.tsx
[Preview this branch](https://dataexplorer-preview.azurewebsites.net/pull/2103)
Resource tree container node: 
* enable children
* hide script nodes (trigger, udf, sproc)
* Call it "Settings" (not "Scale and Settings")
In Settings page:
* Don't show "Scale"
* In Partition key, hide "Change" which requires control plane operations that are not allowed.
=> Enable original azure resource tree style for Fabric native and turn on Settings tab

src/Explorer/Sidebar.tsx, src/Explorer/SplashScreen/FabricHome.tsx, src/Explorer/Tree/treeNodeUtil.tsx, src/Platform/Fabric/FabricUtil.ts
[Preview this branch](https://dataexplorer-preview.azurewebsites.net/pull/2123)
Fabric native can be read-only if the user is shared an existing artifact as Viewer. The read-only flag is passed during initialization to data explorer and stored in the fabric user context.
* Fix resource tree css issue
* Fix Fabric home page (remove Sample Data and Create container buttons)
* Remove Settings item in container tree
=> Fix Fabric Native ReadOnly mode

src/Explorer/SplashScreen/FabricHome.tsx
[Preview this branch](https://dataexplorer-preview.azurewebsites.net/pull/2129)
Hide "Learn more" link until public doc is available.
=> Disable "Learn more" link in Fabric Home

src/Explorer/Tabs/CloudShellTab/CloudShellTerminalCore.tsx, src/Explorer/Tabs/CloudShellTab/ShellTypes/AbstractShellHandler.tsx, src/Explorer/Tabs/CloudShellTab/ShellTypes/CassandraShellHandler.test.tsx, src/Explorer/Tabs/CloudShellTab/ShellTypes/CassandraShellHandler.tsx, src/Explorer/Tabs/CloudShellTab/ShellTypes/MongoShellHandler.test.tsx, src/Explorer/Tabs/CloudShellTab/ShellTypes/MongoShellHandler.tsx, src/Explorer/Tabs/CloudShellTab/ShellTypes/PostgresShellHandler.tsx, src/Explorer/Tabs/CloudShellTab/ShellTypes/VCoreMongoShellHandler.tsx
[Preview this branch](https://dataexplorer-preview.azurewebsites.net/pull/2130?feature.enableCloudShell=true)
Already it mentioned that, request is from portal
=> CloudShell: Changed User Consent Message and Add appName in commands

src/Utils/QueryUtils.ts
[Preview this branch](https://dataexplorer-preview.azurewebsites.net/pull/2134?feature.someFeatureFlagYouMightNeed=true)
This is to handle the scenario of user-defined system partition key
- for update doc, will need to pass the user-defined key
- for updating doc with non-user-defined system key, we have to omit from the partitionkey header but in all other cases, we will need to provide a default value "{}"
=> get the user defined system key value for updating

src/Explorer/Tabs/DocumentsTabV2/DocumentsTabV2.tsx
[ADO](https://msdata.visualstudio.com/CosmosDB/_workitems/edit/4123680)
[Preview this branch](https://dataexplorer-preview.azurewebsites.net/pull/2132?feature.someFeatureFlagYouMightNeed=true)
=> fix: Correct documentId method call in error logging for deletion failures

src/Explorer/Controls/Settings/SettingsSubComponents/ThroughputInputComponents/ThroughputInputAutoPilotV3Component.tsx
[Preview this branch](https://dataexplorer-preview.azurewebsites.net/pull/2141?feature.someFeatureFlagYouMightNeed=true)
Updating the number of RUs in manual mode, used to estimate incorrect cost
Reason: we were applying cost for Autoscale by marking false in the manual update function
PRODUCTION
FIXED
=> Incorrect cost estimation for Manual Throughput

src/Explorer/Controls/Settings/SettingsComponent.tsx
[Preview this branch](https://dataexplorer-preview.azurewebsites.net/pull/2146?feature.someFeatureFlagYouMightNeed=true)
Need to hide the throughput bucketting settings for non shared non dedicated throughput container as it's not supported
=> Hide throughput bucket settings conditionally

src/Contracts/ViewModels.ts, src/Explorer/Explorer.tsx, src/Explorer/Panes/UploadItemsPane/UploadItemsPane.tsx, src/Explorer/Tabs/DocumentsTabV2/DocumentsTabV2.tsx, src/Explorer/Tree/Collection.ts, src/Utils/GalleryUtils.ts
- Refactor UploadItemsPane to support onUpload callback
- Enhance bulk insert result type
- Insert uploaded documents to the grid
[ADO](https://msdata.visualstudio.com/CosmosDB/_workitems/edit/4123695)
[Preview this branch](https://dataexplorer-preview.azurewebsites.net/pull/2131?feature.someFeatureFlagYouMightNeed=true)
=> fix: Update grid after uploading documents

web.config
[Preview this branch](https://dataexplorer-preview.azurewebsites.net/pull/2167?feature.someFeatureFlagYouMightNeed=true)
This change addresses CSP errors seen recently when user's refresh token expires.
e.g. 
Refused to frame 'https://login.microsoftonline.com/' because it violates the following Content Security Policy directive: "frame-src 'self' frame-ancestors portal.azure.com *.portal.azure.com portal.azure.us portal.azure.cn portal.microsoftazure.de df.onecloud.azure-test.net *.fabric.microsoft.com *.powerbi.com *.analysis-df.windows.net dataexplorer-preview.azurewebsites.net".
=> Add login.microsoftonline.com to CSP.

web.config
[Preview this branch](https://dataexplorer-preview.azurewebsites.net/pull/2169?feature.someFeatureFlagYouMightNeed=true)
Removing frame-src from Content-Security-Policy as it is causing livesite issues and I don't believe it is necessary for the VS Code integration.
=> Remove frame-src from CSP.

src/Common/dataAccess/readCollections.ts, src/Contracts/DataModels.ts, src/Utils/arm/generatedClients/cosmos/cassandraResources.ts, src/Utils/arm/generatedClients/cosmos/collection.ts, src/Utils/arm/generatedClients/cosmos/collectionPartition.ts, src/Utils/arm/generatedClients/cosmos/collectionPartitionRegion.ts, src/Utils/arm/generatedClients/cosmos/collectionRegion.ts, src/Utils/arm/generatedClients/cosmos/database.ts, src/Utils/arm/generatedClients/cosmos/databaseAccountRegion.ts, src/Utils/arm/generatedClients/cosmos/databaseAccounts.ts, src/Utils/arm/generatedClients/cosmos/graphResources.ts, src/Utils/arm/generatedClients/cosmos/gremlinResources.ts, src/Utils/arm/generatedClients/cosmos/locations.ts, src/Utils/arm/generatedClients/cosmos/mongoDBResources.ts, src/Utils/arm/generatedClients/cosmos/operations.ts, src/Utils/arm/generatedClients/cosmos/partitionKeyRangeId.ts, src/Utils/arm/generatedClients/cosmos/partitionKeyRangeIdRegion.ts, src/Utils/arm/generatedClients/cosmos/percentile.ts, src/Utils/arm/generatedClients/cosmos/percentileSourceTarget.ts, src/Utils/arm/generatedClients/cosmos/percentileTarget.ts, src/Utils/arm/generatedClients/cosmos/sqlResources.ts, src/Utils/arm/generatedClients/cosmos/tableResources.ts, src/Utils/arm/generatedClients/cosmos/types.ts, src/hooks/useKnockoutExplorer.ts, utils/armClientGenerator/generator.ts
[Preview this branch](https://dataexplorer-preview.azurewebsites.net/pull/2171)
1. Upgrade ARM Client API version to 2025-05-01-preview
This is needed because when we fetch containers, we need to read their `materializedViews` property which is available in this API version. Previously we were working around this by not using strict types.
2.  Fetch `enableMaterializedViews` account property from ARM
This flag was not available via ARG and thus standalone Data Explorer for it retrieves account properties from there. This is hack to fetch flag from ARM until it is supported in ARG.
=> Upgrade ARM Client API version to 2025-05-01-preview & Fetch enableMaterializedViews account property from ARM

src/Contracts/ActionContracts.ts, src/Explorer/OpenActions/OpenActions.tsx
[Preview this branch](https://dataexplorer-preview.azurewebsites.net/pull/2175?feature.someFeatureFlagYouMightNeed=true)
Adding a flag for Opening up Collections pane as quick start from the portal
=> Added Quickstart open action

src/Common/dataAccess/__snapshots__/queryDocuments.test.ts.snap, src/Common/dataAccess/queryDocuments.ts
[Preview this branch](https://dataexplorer-preview.azurewebsites.net/pull/2179)
Data Explorer currently sets `disableNonStreamingOrderByQuery` documents query flag to tree if vector search is not enabled on an account. This is no longer required.
=> Do not set disableNonStreamingOrderByQuery flag

src/Explorer/Panes/SettingsPane/SettingsPane.tsx
When applying changes in the Settings pane, the console logs message `Updated query setting to null` no matter which setting is edited. This log will now be removed as it does not provide useful information.
=> Remove unneeded and misleading console log

src/HostedExplorer.tsx, src/hooks/useAADAuth.ts
[Preview this branch](https://dataexplorer-preview.azurewebsites.net/pull/2184?feature.someFeatureFlagYouMightNeed=true)
**_Problem:_**
Currently, the useAADAuth hook is called by HostedExplorer to perform auth in Standalone Data Explorer.  useAADAuth creates an msalInstance as module-level state and calls getMsalInstance.  getMsalInstance uses the AAD_ENDPOINT in the configContext as the authority.  
Since the msalInstance is created as module-level state, it loads and uses the default AAD_ENDPOINT in the configContext before the useConfig() hook can retrieve state from config.json and other sources.  We need to force useAADAuth to only continue after the configContext is fully initialized.
**_Approach:_**
Move the MSAL instance creation into a useEffect within the useAADAuth hook and …
=> Use Config.json to Set Environment Specific AAD Auth Settings

src/Explorer/Tabs/CloudShellTab/ShellTypes/AbstractShellHandler.test.tsx, src/Explorer/Tabs/CloudShellTab/ShellTypes/AbstractShellHandler.tsx, src/Explorer/Tabs/CloudShellTab/ShellTypes/CassandraShellHandler.test.tsx, src/Explorer/Tabs/CloudShellTab/ShellTypes/CassandraShellHandler.tsx, src/Explorer/Tabs/CloudShellTab/ShellTypes/MongoShellHandler.test.tsx, src/Explorer/Tabs/CloudShellTab/ShellTypes/MongoShellHandler.tsx, src/Explorer/Tabs/CloudShellTab/ShellTypes/PostgresShellHandler.test.tsx, src/Explorer/Tabs/CloudShellTab/ShellTypes/PostgresShellHandler.tsx, src/Explorer/Tabs/CloudShellTab/ShellTypes/VCoreMongoShellHandler.test.tsx, src/Explorer/Tabs/CloudShellTab/ShellTypes/VCoreMongoShellHandler.tsx, src/Explorer/Tabs/CloudShellTab/Utils/AttachAddOn.tsx
[Preview this branch](https://dataexplorer-preview.azurewebsites.net/pull/2195?feature.someFeatureFlagYouMightNeed=true)
- We are upgrading the mongoshell version to 2.5.5 
- Suppressing multiple statements from being added to the terminal.
- The 'disable telemetry' command shows a message the first time it runs. We suppress this message to prevent displaying any telemetry-related information.
**Previous**
**Updated**
=> Disabling telemetry for mongo shell

src/Explorer/Tabs/CloudShellTab/CloudShellTerminalCore.tsx, src/Explorer/Tabs/CloudShellTab/Utils/RegionUtils.tsx
This pull request updates the logic for determining and validating CloudShell regions, with a particular focus on supporting the "fairfax" environment and US government regions. The main changes include adding new region constants, updating the region selection logic, and expanding the set of valid regions.
Region selection improvements:
* Added the `DEFAULT_FAIRFAX_CLOUDSHELL_REGION` constant to `CloudShellTerminalCore.tsx` to support the "fairfax" environment.
* Updated the `determineCloudShellRegion` function to select `usgovvirginia` as the default region when the portal environment is "fairfax", otherwise defaulting to `westus`.
Region validation updates:
* Added `usgovvirginia` and `usgovarizona` to the set of valid CloudShell regions in `RegionUtils.tsx`.
[Preview this …
=> Fix fairfax default cloud shell region.

src/Explorer/Panes/SettingsPane/SettingsPane.tsx, src/Explorer/QueryCopilot/QueryCopilotTab.tsx, src/Explorer/SplashScreen/SplashScreen.tsx, src/Explorer/SplashScreen/SplashScreenButton.tsx, src/Explorer/Tabs/QueryTab/QueryTabComponent.test.tsx, src/Explorer/Tabs/QueryTab/QueryTabComponent.tsx
[Preview this branch](https://dataexplorer-preview.azurewebsites.net/pull/2209)
This PR hides any instance of Query Advisor (known internally as Query Copilot). However, none of the functionality was removed. In fact, it is likely that this feature will be reintroduced. So I have opted to comment references rather than delete them. A major reason to comment as opposed to delete is that often, there are some checks or conditions which might not be obvious to a future dev who reinstates this feature.
The following areas are affected with a screenshot of the old then the new:
Splash screen
Settings
Query tab
=> Commenting or deleting UI references to Query Advisor

src/Explorer/SplashScreen/FabricHome.tsx
Fixes: [ADO](https://msdata.visualstudio.com/CosmosDB/_workitems/edit/4223825/)
[Preview this branch](https://dataexplorer-preview.azurewebsites.net/pull/2206?feature.someFeatureFlagYouMightNeed=true)
=> chore: Update help link in FabricHome component to point to the new documentation

.github/workflows/ci.yml, test/fx.ts, test/testExplorer/TestExplorer.ts
[Preview this branch](https://dataexplorer-preview.azurewebsites.net/pull/2220?feature.someFeatureFlagYouMightNeed=true)
This change adds support for using RBAC in the playwright tests that target MongoDB and Cassandra API accounts.
=> Support RBAC in E2E tests for Mongo & Cassandra
